### ISSUE TITLE
Wrong endpoint trying to delete a scan history

### ISSUE THREAD

**Issue by matiasBusco** [tenable/pyTenable#101]
When trying to delete a specific scan history the path is wrong specified:
The correct one should be **DELETE** /scans/{scan_id}/history/{history_id}

**Error** is scans/{scan_id}/**hostory**/{history_id}

The error is present in:
tests/io/cassettes/test_scan_delete_history_notfounderror.yaml (line 12)
tenable/io/scans.py (line 357)

**To reproduce it**
1. `tio.scans.delete_history(scan_id=value,history_id=value)`

**Expected behavior**
It should delete the scan history

**Screenshots**
Error output
![image](https://user-images.githubusercontent.com/18237644/55107616-80fc5f00-50b0-11e9-835d-bcc5162ee968.png)

**Additional context**
We need it becaus is a vital function to us so we can purge the scans we made

**Comment by SteveMcGrath** [comment]
v0.3.14 uploaded to correct for this issue.  Thanks for reporting!
