### ISSUE TITLE
Cannot schedule Tenable.SC scan to launch NOW/Immediately

### ISSUE THREAD

**Issue by Sorsnce** [tenable/pyTenable#102]
**Describe the bug**
After version 0.3.9 of PyTenable I am unable to perform a scan with "sc.scans.create" and setting the schedule to now. This issue exists in all versions of python i.e. 2.7, 3.5, 3.6, 3.7. Please see below for details.

**To Reproduce**
1. Use the following python code:

from tenable.sc import TenableSC
from pprint import pprint

sc = TenableSC('10.10.10.1)
sc.login('username', 'password')
sc.scans.create("test scan", 5, policy_id=17, targets=["192.168.8.1"], schedule={'type': 'now'}, email_complete=True, creds=[3])

2. Notice the "schedule={'type': 'now'}"

3. tenable.errors.UnexpectedValueError: schedule:type has value of now.  Expected one of ical,dependent,never,rollover,template

**Expected behavior**
Launchs a new Tenable.SC scan "NOW" rather than schedule the scan for a specific time.

**Screenshots**
![image](https://user-images.githubusercontent.com/24528578/55352506-ff7d4600-548e-11e9-8cb2-f57ddeb53f79.png)

**System Information (please complete the following information):**
 - OS: Windows 10 1607
 - 64-bit
 - PyTenable 0.3.10+
- Python 3.7

**Additional context**
This code was working on PyTenable version 0.3.9

**Comment by Sorsnce** [comment]
Found the issue, on line 140 in tenable\sc\base.py the following line reads

`resp = {'type': self._check('schedule:type', item['type'], str, 
            choices=['ical', 'dependent', 'never', 'rollover', 'template'],
            default='never')}`

I changed the following too:

`        resp = {'type': self._check('schedule:type', item['type'], str, 
            choices=['ical', 'dependent', 'never', 'rollover', 'template', 'now'],
            default='never')}`

And it fixed the issue!

**Comment by SteveMcGrath** [comment]
The reasoning behind the breakage is that the schedule dict is no longer being flattened.  It was creating issues in other packages, so instead the solution was to just pass the dict as it would be passed in the api:

https://github.com/tenable/pyTenable/blob/master/tenable/sc/scans.py#L262-L264

https://pytenable.readthedocs.io/en/stable/sc.html#schedule-dictionaries

My apologies on the breakage.

**Comment by Sorsnce** [comment]
Gotcha, I provided a quick fix in a pull request #103

**Comment by SteveMcGrath** [comment]
Yeah, the issue is that your master is pretty far back, and some things have changed since then:

https://github.com/tenable/pyTenable/compare/0.3.9...master

**Comment by Sorsnce** [comment]
yup just updated Pull request to reflect master 0.3.15
