### ISSUE TITLE
Tenable.py Script Issue

### ISSUE THREAD

**Issue by helpMeTen** [tenable/pyTenable#107]
We are receiving 429 errors when trying to run simple CURL commands to Tenable.io.

The CURL commands were previously working, but something on the Tenable side is saying that we're sending too many requests, or too fast.

Here is the specific CURL command that shows the error: curl -X POST -H 'Content-Type: application/json' --data '{"chunk_size":10000}' -H 'X-ApiKeys: 
accessKey=access-key
secretKey=secret-key 

https://cloud.tenable.com/assets/export {"status":429,"message":"Duplicate export not allowed. Please modify request or wait until existing export is complete."} 

We have reduced the chunk size to 5000, and we still see the same issue.

Please help, and let us know what else we can try.

**Comment by SteveMcGrath** [comment]
While this isn't a pyTenable issue (running a CURL command against the API isn't something thats a pyTenable issue), the problem your running against is that your trying to run multiple exports from the API using the same filters.  The 429 call it informing you that you already have another export processing and that you need to wait until that export finishes processing (and that means processing on the Tenable.io end, not the client) before initiating a replica.
