### ISSUE TITLE
issue with version 0.3.18 and previous

### ISSUE THREAD

**Issue by altmvogi** [tenable/pyTenable#112]
issue with export, for whatever reason the vulnerability export stopped working a couple of days ago. I always get error HTTP 429 back and the program finishes with error. This time I am attaching the log. multiple attempts are made to download results with different UUIDs but does not work.

Could you guide me?

Connected to pydev debugger (build 191.6605.12)
INFO:__main__:DEBUG = False
INFO:__main__:CONNECT_DB = XXXX
INFO:__main__:EXPORT_ASSETS = True
INFO:__main__:Starting export vulnerabilities
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID 3de42ee3b3510a6ab655851a16ac001b for https://cloud.tenable.com/vulns/export
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:Resetting dropped connection: cloud.tenable.com
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID 28740713045da090f8f29de223956f68 for https://cloud.tenable.com/vulns/export
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID f634f74ca00c4895c17e6790ab88e6c4 for https://cloud.tenable.com/vulns/export
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID 28348b8c6750197af35f61cdf7842590 for https://cloud.tenable.com/vulns/export
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID b739c85ba5641a7c762e6f24ef4b17de for https://cloud.tenable.com/vulns/export
DEBUG:tenable.io.TenableIO:path=vulns/export, query={}, body={'filters': {'severity': ['critical', 'high', 'medium', 'low'], 'state': ['FIXED', 'OPEN', 'REOPENED']}, 'num_assets': '50'}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /vulns/export HTTP/1.1" 429 None
DEBUG:tenable.io.TenableIO:Request-UUID 3cd699443f6015fa12afc042828bffa8 for https://cloud.tenable.com/vulns/export
ERROR:tenable.errors.RetryError:POST https://cloud.tenable.com/vulns/export >> 6 attempts made, last returned 3cd699443f6015fa12afc042828bffa8:429 Duplicate export not allowed. Please modify request or wait until existing export is complete.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/altmvogi/OneDrive - Flextronics/Desktop/Tenable.io/tenabel_io.py", line 705, in <module>
    export_vulnerabilities()
  File "C:/Users/altmvogi/OneDrive - Flextronics/Desktop/Tenable.io/tenabel_io.py", line 389, in export_vulnerabilities
    state=['FIXED', 'OPEN', 'REOPENED'])
  File "C:\Program Files\Python37\lib\site-packages\tenable\io\exports.py", line 231, in vulns
    'vulns/export', json=payload).json()['export_uuid']
  File "C:\Program Files\Python37\lib\site-packages\tenable\base.py", line 459, in post
    return self._request('POST', path, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tenable\base.py", line 423, in _request
    raise RetryError(resp, retries)
tenable.errors.RetryError: 6 attempts made, last returned 3cd699443f6015fa12afc042828bffa8:429 Duplicate export not allowed. Please modify request or wait until existing export is complete.

Process finished with exit code 1

**Comment by altmvogi** [comment]
for whatever reason this seems to resumed working after a couple of hours wait time. this is really strange. Case can be closed, however if you have an explanation for this behavior please share.Michael

**Comment by SteveMcGrath** [comment]
This specific issues isn't one with pyTenable specifically, but is an issue with running multiple exports with the same parameters at the same time.  The 429 response specifically details that in the response.

```
3cd699443f6015fa12afc042828bffa8:429  Duplicate export not allowed. Please modify request or wait until existing export is complete.
```

There is an unrelated issue that was addressed a while back of being able to resume/restart an export using the UUID of the original export.  This has been addressed by passing the uuid parameter into the export methods.

**Comment by altmvogi** [comment]
Thanks Steven.



Steven McGrath <notifications@github.com> schrieb am Do., 2. Mai 2019,
17:04:
