### ISSUE TITLE
KeyError: 'was_scan'

### ISSUE THREAD

**Issue by s-ritik16n** [tenable/pyTenable#116]
**Describe the bug**
call to TenableIO scans.create() function results in error-

    File "C:\Python27\lib\tenable\io\scans.py", line 319, in create
        scan = self._create_scan_document(kw)
    File "C:\Python27\lib\tenable\io\scans.py", line 112, in _create_scan_document
    scanners = self._api.scanners.allowed_scanners()
    File "C:\Python27\lib\tenable\io\scanners.py", line 67, in allowed_scanners
    was_tmpl = self._api.policies.templates()['was_scan']
    KeyError: 'was_scan'

**To Reproduce**
1. Create a TenableIO object from tenable.io and initiate with `TenableIO('ACCESS_KEY','SECRET_KEY')`
2. Call 'scans.create()' on the object with `policy='', targets=[...], scanner=''`
    - eg.- tio.scans.create(policy='myPolicy', targets=[targets], scanner='myScanner')
3. See error

**Expected behavior**
Scan created successfully

**System Information (please complete the following information):**
 - OS: Windows
 - Architecture  64bit
 - Memory 8GB

**Comment by SteveMcGrath** [comment]
I'm assuming that you do not have the WAS scanner?

**Comment by s-ritik16n** [comment]
Yeah. I only have the scanner for tenable.io Vulnerability Management.

**Comment by SteveMcGrath** [comment]
Linking PR #117
