### ISSUE TITLE
tenable.errors.InvalidInputError: 400 {"error":"Invalid 'name' field"}

### ISSUE THREAD

**Issue by s-ritik16n** [tenable/pyTenable#118]
**Describe the bug**
call to TenableIO scans.create() function results in following error - 

    Traceback (most recent call last):
    scan = tio.scans.create(policy=policy_id, targets=[targets], scanner=self.scanner)
    File "C:\Python27\lib\tenable\io\scans.py", line 323, in create
        return self._api.post('scans', json=scan).json()['scan']
    File "C:\Python27\lib\tenable\base.py", line 463, in post
        return self._request('POST', path, **kwargs)
    File "C:\Python27\lib\tenable\base.py", line 416, in _request
        raise self._error_codes[status](resp)
    tenable.errors.InvalidInputError: babe89548aba74496e6160b615ab5fa1:400 {"error":"Invalid 'name' field"}

**To Reproduce**
1. Create a TenableIO object from tenable.io and initiate with TenableIO('ACCESS_KEY','SECRET_KEY')
2. Call 'scans.create()' on the object with policy='', targets=[...], scanner=''
    - eg.- tio.scans.create(policy=policy_id, targets=[targets], scanner='myScanner')
3. See error

**Expected behavior**
Scan created successfully

**System Information (please complete the following information):**
 - OS: Windows 
 - Architecture 64bit
 - Version 10
 - Memory 8GB

**Comment by s-ritik16n** [comment]
on passing the parameter `name` to the `create()` function, this error can be avoided, but the [documentation](https://pytenable.readthedocs.io/en/latest/io.html#tenable.io.scans.ScansAPI.create) says `name` is one of the optional fields passed to `create()` function.

**Comment by SteveMcGrath** [comment]
thats an error on my part, the name field is obviously required.
