### ISSUE TITLE
Tenable Error.py catching exception

### ISSUE THREAD

**Issue by TCalaelen** [tenable/pyTenable#119]
Hi there,
I was doing some testing on the APIError to catch some exception but couldn't catch all of it. 
I got the exception and got out my custom message, but I still have the error message in my console.

**To Reproduce**
So here is the code I execute to have this error, it's supposed to juste print my message then exit.
```
    try:
        sc = TenableSC(url)
        sc.login(username, password)
    except APIError as error:
        if error.code == 403:
            print("Mate you need to have valid credentials: {}".format(username))
        sys.exit(1)
    except ConnectionError as error:
        print("Mate you need to send me to a valid url/IP: {}".format(url))
        sys.exit(1)
```

Here is the output

> No Tenable.sc Instance at XXX
Mate you need to send me to a valid url: XXX

Instead of:

> Mate you need to send me to a valid url: XXX

**Comment by SteveMcGrath** [comment]
The reason for this is that upon instantiation the TenableSC object will make a call to system to pull the version information.
