### ISSUE TITLE
Cannot create credentials in tenable

### ISSUE THREAD

**Issue by remzi-e** [tenable/pyTenable#122]
**Describe the bug**
When trying to create a credential as per the examples on the wiki or in the code itself, i get the following error:
```
Traceback (most recent call last):
  File "tenable_draft.py", line 103, in <module>
    public_key = keyfile1)
  File "<path>\lib\site-packages\tenable\sc\credentials.py", line 674, in create
    kw = self._upload_files(**kw)
  File "<path>\lib\site-packages\tenable\sc\credentials.py", line 407, in _upload_files
    kw[key] = self._api.files.upload(fobj)
NameError: name 'fobj' is not defined
```
The call used was:
```
with open('{}ssh_key.pub'.format(win_temp_folder), 'rb') as keyfile1:
    cred = sc.credentials.create(
        'test ssh key', 'ssh', 'publickey',
        username = 'centos',
        public_key = keyfile1)
```
This seems to be the faulty line:
https://github.com/tenable/pyTenable/blob/master/tenable/sc/credentials.py#L407
There's no `fobj` defined anywhere before this.

**System Information (please complete the following information):**
 - OS: Win 10
 - Ran via gitbash and in pipenv

**Comment by SteveMcGrath** [comment]
please validate that 0.3.20 no longer has this issue.

**Comment by remzi-e** [comment]
no longer get that error now.
but i do get a:
```
tenable.errors.APIError: None:403 
    {"type":"regular",
    "response":"",
    "error_code":146,
    "error_msg":"Map not found for authType 'publickey'.\n",
    "warnings":[],
    "timestamp":1559561202}
```
i'm trying to upload a private key and create a credential from that key.
@SteveMcGrath should i open a separate bug for this?

**Comment by SteveMcGrath** [comment]
Try using the private key instead?  If that doesn't work I'll have to do some further investigation.

```with open('{}ssh_key.pub'.format(win_temp_folder), 'rb') as keyfile1:
    cred = sc.credentials.create(
        'test ssh key', 'ssh', 'publickey',
        username = 'centos',
        private_key = keyfile1)```

**Comment by remzi-e** [comment]
@SteveMcGrath no dice. same error.
were you able to create a tenable ssh credential using the example in your code?
the example specifies a `publickeyfile.pub` but i assume you guys are referring to a private key, right? 'cause that's the was you manually create a ssh credential in tenable.

**Comment by SteveMcGrath** [comment]
I was looking at the SC API docs for that.  If that didnt work, then i'll have to start investigating myself.  I was relying on the API docs that stated (note that pyTenable converts camelCase to snake_case):

```
 authType "publickey"
    --------------------
    "privateKey" : <string>,
    "passphrase" : <string> DEFAULT "",
    "privilegeEscalation" : <string> "none" | "su" | "sudo" | "su+sudo" | "dzdo" | "pbrun" | "cisco" | ".k5login",
```

However if those aren't correct, then its something more entertaining.

**Comment by remzi-e** [comment]
@SteveMcGrath do you guys have a nessus instance where you could try out this credentials creation example?

**Comment by SteveMcGrath** [comment]
I've identified the issue after some poking around.  The API docs are incorrect, and it should be "publicKey" instead of "publickey" for the auth_type.  As I'm strictly checking the type, this will need to be adjusted.

**Comment by SteveMcGrath** [comment]
I validated on my SC 5.8 instance that the above commit now works.  This'll get rolled out with 0.3.21.  You could either pull directly from git or wait until I get 0.3.21 pushed ;)

**Comment by remzi-e** [comment]
works like a charm. thanks!
quick question about the fix, though:
should the type checking be relaxed to avoid issues like this in the future? there will be no autocomplete since it's a string, but it would be helpful if the request construction ignores case for any of the choices.

**Comment by SteveMcGrath** [comment]
the validation is based on the API docs, so when there is a deviation (like this one) I'll raise it to the doc teams internally to get it addressed and make the necessary changes here.  The validation is generally to make sure that your only passing valid calls to the API and providing the user with some meaningful input as to why the API is failing.  In this example, the following error:

```
UnexpectedValueError: auth_type has value of publicKey.  Expected one of cyberark,lieberman,password,BeyondTrust,certificate,kerberos,publickey,thycotic,lm,ntlm
```

Is really obvious as to what failed, whereas the API-provided error of

```
APIError: None:403 {"type":"regular","response":"","error_code":146,"error_msg":"Map not found for authType 'publickey'.\n","warnings":[],"timestamp":1559571389}
```

is considerably more vague.

That being said, you can almost always bypass the validation by passing the parameter the API expects (instead of the validated snake_cased variant).  As auth_type is a required param, this is one of the few cases where this isnt the case, however pyTenable is constructed to generally allow for both (note the link below).

https://pytenable.readthedocs.io/en/stable/sc.html#tenable-sc-crud-within-pytenable

**Comment by remzi-e** [comment]
great.

last question: when will 0.3.21 be released?

**Comment by SteveMcGrath** [comment]
week or two max.  all depends on if I can roll in one of the last of the Phase 1 core tickets in with this within a decent timeframe or not.  Neither of them are small:

https://github.com/tenable/pyTenable/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Phase+1%22

**Comment by jeromesheerin** [comment]
This is still an issue in version 1.2.1

Error received from server is:

  File "/usr/local/lib/python3.7/dist-packages/tenable/sc/credentials.py", line 683, in create
    return self._api.post('credential', json=payload).json()['response']
  File "/usr/local/lib/python3.7/dist-packages/tenable/base/v1.py", line 578, in post
    return self._request('POST', path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tenable/base/v1.py", line 531, in _request
    raise self._error_codes[status](resp)
tenable.errors.APIError: None:403 {"type":"regular","response":"","error_code":146,"error_msg":"Map not found for authType 'publickey'.\n","warnings":[],"timestamp":160518


My custom Code:
`    cred = sc.credentials.create('user1', 'ssh', 'publicKey', username='cloud-user',privilege_escalation='sudo', escalation_username='root',private_key=privatekeyfile)
`
Faulty Code : /usr/local/lib/python3.7/dist-packages/tenable/sc/credentials.py
` kw['authType'] = self._check('auth_type', kw['auth_type'], str,
                choices=['cyberark', 'lieberman', 'password', 'BeyondTrust',
                         'certificate', 'kerberos', 'publickey', 'thycotic',
                         'lm', 'ntlm'])
            del(kw['auth_type'])
`

Fixed code : /usr/local/lib/python3.7/dist-packages/tenable/sc/credentials.py
` kw['authType'] = self._check('auth_type', kw['auth_type'], str,
                choices=['cyberark', 'lieberman', 'password', 'BeyondTrust',
                         'certificate', 'kerberos', '**publicKey**', 'thycotic',
                         'lm', 'ntlm'])
            del(kw['auth_type'])
`

**Comment by SteveMcGrath** [comment]
The change below is related to issue #210 and reverted the change that broke #122.  This is in 1.2.2 and 1.2.3 as notes in the tags

https://github.com/tenable/pyTenable/commit/2a130b8d0f544f5fb8a1be842b96f2ed4bd27bdf
