### ISSUE TITLE
TSC AssetAPI

### ISSUE THREAD

**Issue by SteveMcGrath** [tenable/pyTenable#13]
the asset_lists.py module should handle the Asset and Asset Template APIs.  These APIs should be fully tested.

**Comment by sanju1111** [comment]
for rule in sc.accept_risks.list():
AttributeError: 'TenableSC' object has no attribute 'accept_risks'

**Comment by SteveMcGrath** [comment]
That looks correct for 0.3.11.  The property was commented out as it was untested and we were originally gearing for a 1.0 release for RSA.  Unfortunately that didnt happen, however i seem to have missed this one.

**Comment by d4t4king** [comment]
Hello,

I don't know if you're doing these in any particular order, but if I could +1 this for priority, that'd be awesome.

My organization is using static Asset groups as targets in scans.  I need to sync these Asset groups with external sources (AD, etc.).  I don't even see 'assets' in `dir(sc)` after logging in.

**Comment by SteveMcGrath** [comment]
its one of the last things to write for phase 1
