### ISSUE TITLE
Bug- Scan number 2145

### ISSUE THREAD

**Issue by jayala518** [tenable/pyTenable#131]
The issue that I noticed in case of pyTenable is that for getting the details of scan number 2145, when executing: 

from tenable.io import TenableIO 

tio = TenableIO(AKEY, SKEY) 

tio.scans.details(2145) 

The last statement crashes with an error: 

File "<stdin>", line 1, in <module> 

File "C:\Users\Jedrzej.Gajek\AppData\Local\Programs\Python\Python37\lib\site-packages\tenable\io\scans.py", line 428, in details 

editor['compliance']['data']) 

File "C:\Users\Jedrzej.Gajek\AppData\Local\Programs\Python\Python37\lib\site-packages\tenable\io\editor.py", line 74, in parse_audits 

resp['custom'].append({ 

AttributeError: 'dict' object has no attribute 'append' 

The error exists in the pyTenable code, in the newest version as well as previous ones. It has so far happened only for this particular scan, which is a compliance scan. The scan itself has been successfully executing. The statement works for all other scans I have checked – but I did not see anything that would make this scan special, so it might happen again for a new scan.

**Comment by SteveMcGrath** [comment]
The scans.details method is trying to construct the response from the editor API, and as such we'll run into edge cases like this from time to time.  Due to the sensitivity of some of the items in the response, and the nature of how the response is constructed, can I ask you to use the following code to save the editor response to disk and then email the resulting JSON file to me at smcgrath _at_ tenable.com?

``` python
import json
from tenabble.io import TenableIO
tio = TenableIO(access_key, secret_key)
with open('editor_2145.json', 'w') as jfile:
    resp = tio.editor.details('scan', 2145)
    json.dump(resp, jfile)
```

**Comment by SteveMcGrath** [comment]
The issue appears to be a problem with the custom audit file constructor.  I'll have to perform a few tests to see how this is handled properly and make the appropriate changes.

**Comment by SteveMcGrath** [comment]
Please test for validation by pulling the current dev branch and let me know if this resolves the issue.

```
pip install git+git://github.com/tenable/pytenable.git
```
