### ISSUE TITLE
tenable/sc/audit_files.py export_audit should be a get request

### ISSUE THREAD

**Issue by joelcarlton** [tenable/pyTenable#132]
**Describe the bug**
I was not having success exporting audit files. I debugged the code and noticed it was using POST. The API docs instruct to use a GET request.
[Code](https://github.com/tenable/pyTenable/blob/master/tenable/sc/audit_files.py#L342)
[Documentation](https://docs.tenable.com/sccv/api/AuditFile.html#AuditFileRESTReference-/auditFile/{id}/export)

**To Reproduce**
1. Tried to export

**Expected behavior**
Expected the audit file to download

**Screenshots**

**System Information (please complete the following information):**

**Additional context**

**Comment by SteveMcGrath** [comment]
good catch!

**Comment by joelcarlton** [comment]
Do you have an ETA on this change? I have a project currently breaking on this.

**Comment by SteveMcGrath** [comment]
the current codebase should work, Itll get rolled into the next release within a week or two now that the holiday week is over.

**Comment by joelcarlton** [comment]
Awesome, Thanks.
