### ISSUE TITLE
sc.alerts.details(id) field "action" should be a dict, not list

### ISSUE THREAD

**Issue by OtharSmirnow** [tenable/pyTenable#134]
**Describe the bug**
sc.alerts.details(id) field "action" is data type "list", but it is returning value in the "dict" format

**To Reproduce**
run the code:
`file = open("alertsList.csv","w")
header = True
print('Processing ...')
for alert in sc.alerts.list(fields=['id'])['manageable']:
	alertID = alert['id']#   alertID = int(alert.split(':')[1].split('u\'')[1].split('\'')[0])
	print('Alert ID: ' + alertID)
	alertDetails = sc.alerts.details(str(alertID))

	#header rows in CSV
	if header:
		for h in alertDetails:
			first = True
			if isinstance(alertDetails[str(h)],dict):
				detail = alertDetails[str(h)]
				for hd in detail:
					if first:
						file.write(str(h)+'|')
						first = False
					else:
						file.write('|')
			else:
				file.write(str(h)+'|')
		file.write('\n')
		for h in alertDetails:
			if isinstance(alertDetails[str(h)],dict):
				detail = alertDetails[str(h)]
				for hd in detail:
					file.write(str(hd)+'|')
			else:
				file.write(str(type(alertDetails[str(h)]))+'|')
		file.write('\n')
		header = False

	#data rows in CSV
	for h in alertDetails:
		if isinstance(alertDetails[str(h)],dict):
			detail = alertDetails[str(h)]
			for hd in detail:
				if isinstance(detail[str(hd)],dict):
					writeVal = str(detail[str(hd)])
				else:
					writeVal = detail[str(hd)]
				file.write(str(writeVal)+'|')
		else:
			file.write(str(alertDetails[str(h)])+'|')
	file.write('\n')`
2. Open the CSV file with deliminator '|'
3. column 'T' will have in row:
   1. action - key name
   2. <type 'list'> - key data type
   3. `[{u'status': u'0', u'definition': {u'assignee': {u'username': u'', u'lastname': u'', u'id': u'2', u'firstname': u''}, u'notes': u'', u'name': u'', u'description': u''}, u'users': [], u'objectID': None, u'type': u'ticket', u'id': u''}]`

**Expected behavior**
as a 'dict' data type it could be correctly processed

**System Information (please complete the following information):**
 - OS: Ubuntu 19.04
 - Architecture 64bit]
 - Version 2.7.16
 - Memory 16G

**Comment by SteveMcGrath** [comment]
Action actually should be a list, is tested as a list, and follows the spec as a list.  You can have multiple actions associated to a single alert.  Note the following response:

https://docs.tenable.com/sccv/api/Alert.html#AlertRESTReference-/alert/{id}

Also the following test code:

https://github.com/tenable/pyTenable/blob/master/tests/sc/test_alerts.py#L112-L192
