### ISSUE TITLE
Can't create ldap user: Error retrieving LDAP

### ISSUE THREAD

**Issue by habullock** [tenable/pyTenable#135]
**Describe the bug**

This error generated when creating user under security context of "Administrator" or "Security Manager" in the Org=1 using this Python code:
newuser = sc.users.create(UserName, '', 1000001, group = 1, auth_type='ldap', org=1)

tenable.errors.APIError: None:403 {"type":"regular","response":"","error_code":147,"error_msg":"Error retrieving LDAP #-1 in Organization #0.\nLDAP #-1 does not exist or is not accessible by Organization 1.\n","warnings":[],"timestamp":1563927750}

**To Reproduce**
1. Attempt to create an ldap user in a defined organization. We have one org with ID:1
2. A similar error occurs when attempting to edit an existing user when attempting to change authType from 'tns' to 'ldap'

**Expected behavior**
1. We expect an ldap user to be created
2. We expected that the authType could be changed from 'tns' to 'ldap'

**System Information (please complete the following information):**
 - OS: [Windows 10]
 - Architecture  64bit,
 - Version 1803
 - Memory 16GB

**Additional context**

**Comment by SteveMcGrath** [comment]
you will need to specify the ldap config to use.  Right now you will need to specify `ldap={'id': 1}` (or whatever the id is for your ldap config.  In 0.3.23, you'll be able to pass `ldap_id=1` as well, and have the constructor build that subdoc for you.
