### ISSUE TITLE
Agent Group Filters don't appear to be working

### ISSUE THREAD

**Issue by I-Am-Buggy** [tenable/pyTenable#137]
**Describe the bug**
When searching for agents by group, I should be able to use filters.  It works via the API directly, but I can't make it work using pyTenable. For example, using the API via https://developer.tenable.com/reference#agents-list I can filter agents with the following: groups:neq:99999 (number made up for the sake of this example)

**To Reproduce**
for agent in tio.agents.list(('groups', 'eq', '99999'))
That call should be identical to the one above.  Instead, it just returns ALL agents and doesn't perform any filtering.

**System Information (please complete the following information):**
 - OS: Windows 10
 - Architecture 64bit
 - Version 3.7
 - Memory 16GB

**Additional context**
PyCharm 2019.2 (Community Edition)
Build #PC-192.5728.105, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: 
Non-Bundled Plugins:

**Comment by I-Am-Buggy** [comment]
BTW...Version of PyTenable in use is the latest: 0.3.22

**Comment by SteveMcGrath** [comment]
can you enable debug logging and post logs of the query?

**Comment by I-Am-Buggy** [comment]
Sure! I've replaced my group ID with 99999 and redacted anything else that seemed like it may be sensitive.

**PyTenable**:
21684-DEBUG-Starting new HTTPS connection (1): cloud.tenable.com:443
21684-DEBUG-https://cloud.tenable.com:443 "GET /filters/scans/agents HTTP/1.1" 200 None
21684-DEBUG-Request-UUID <redacted> for https://cloud.tenable.com/filters/scans/agents
21684-DEBUG-path=scanners/1/agents, query={'f': ['groups:neq:99999'], 'limit': 50, 'offset': 0}, body={}
21684-DEBUG-https://cloud.tenable.com:443 "GET /scanners/1/agents?f=groups%3Aneq%3A99999&limit=50&offset=0 HTTP/1.1" 200 None
21684-DEBUG-Request-UUID <redacted> for https://cloud.tenable.com/scanners/1/agents
21684-DEBUG-path=scanners/1/agents, query={'f': ['groups:neq:99999'], 'limit': 50, 'offset': 50}, body={}

**TenableAPI**:
url = "https://cloud.tenable.com/scanners/1/agents"

querystring = {"offset":"0","f":"groups:neq:99999"}

headers = {
    'accept': "application/json",
    'x-apikeys': "<redacted>"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

**Comment by SteveMcGrath** [comment]
that all looks correct.  what happens when you pass the following params?
```
{'f': ['groups:neq:99999'], 'limit': 50, 'offset': 0}
```

**Comment by I-Am-Buggy** [comment]
It works as expected if I change the manual call query string to:

querystring = {'f': ['groups:neq:110135'], 'limit': 50, 'offset': 0}

I still can't get it to work within PyTenable though.

**Comment by SteveMcGrath** [comment]
So i was finally in a position to test this, however I can't seem to replicate the problem your running into.  The filters seem to work fine for me.

```
>>> agents = tio.agents.list(('groups', 'eq', '107579'))
>>> agents.next()
{'id': 187, 'uuid': 'c2d9e0b8-d88e-46ed-b7f4-86062e3ab42b', 'name': 'FREELANCER'
, 'platform': 'WINDOWS', 'distro': 'win-x86-64', 'ip': '192.168.100.114', 'last_
scanned': 1564339084, 'plugin_feed_id': '201907262133', 'core_build': '322', 'co
re_version': '7.4.1', 'linked_on': 1486148817, 'last_connect': 1564409805, 'stat
us': 'on', 'groups': [{'name': 'Agents', 'id': 102}, {'name': 'Freelancer', 'id'
: 107579}], 'supports_remote_logs': True}
>>> agents.next()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    agents.next()
  File "/Users/steve/.pyenv/versions/3.6.7/envs/py3tenable-dev/lib/python3.6/sit
e-packages/tenable/base.py", line 74, in next
    raise StopIteration()
StopIteration
>>> agents = tio.agents.list(('groups', 'neq', '107579'))
>>> agents.next()
{'id': 186, 'uuid': 'ad68f5eb-8b38-4047-b710-bcf1002f49b2', 'name': 'bastion.home.cugnet.net', 'platform': 'LINUX', 'distro': 'es7-x86-64', 'ip': '192.168.101.146', '
last_scanned': 1564339072, 'plugin_feed_id': '201907262133', 'core_build': '322', 'core_version': '7.4.1', 'linked_on': 1486146546, 'last_connect': 1564409819, 'statu
s': 'on', 'groups': [{'name': 'Agents', 'id': 102}], 'supports_remote_logs': True}
>>> agents.next()
{'id': 182, 'uuid': 'dd1e509a-1ff4-49ec-afe9-20603321c3e1', 'name': 'herfio.home.cugnet.net', 'platform': 'LINUX', 'distro': 'es7-x86-64', 'ip': '192.168.101.140', 'l
ast_scanned': 1559156625, 'plugin_feed_id': '201905302042', 'core_build': '281', 'core_version': '7.4.0', 'linked_on': 1486146510, 'last_connect': 1559317218, 'status
': 'off', 'groups': [{'name': 'Agents', 'id': 102}], 'supports_remote_logs': False}
>>> agents.next()
{'id': 179, 'uuid': '16ee04f6-e9fa-4394-a9d9-f3823c3b1919', 'name': 'plex.home.cugnet.net', 'platform': 'LINUX', 'distro': 'es7-x86-64', 'ip': '192.168.101.117', 'las
t_scanned': 1564338974, 'plugin_feed_id': '201907262133', 'core_build': '322', 'core_version': '7.4.1', 'linked_on': 1486146471, 'last_connect': 1564409987, 'status':
 'on', 'groups': [{'name': 'Agents', 'id': 102}], 'supports_remote_logs': True}
>>> agents.next()
{'id': 185, 'uuid': 'dc236707-4829-40b1-81f4-576342f4a919', 'name': 'rproxy.home.cugnet.net', 'platform': 'LINUX', 'distro': 'es7-x86-64', 'ip': '192.168.101.133', 'l
ast_scanned': 1564339110, 'plugin_feed_id': '201907262133', 'core_build': '322', 'core_version': '7.4.1', 'linked_on': 1486146538, 'last_connect': 1564410092, 'status
': 'on', 'groups': [{'name': 'Agents', 'id': 102}], 'supports_remote_logs': True}
>>> agents.next()
{'id': 178, 'uuid': 'eb6c151b-166f-44ee-8e40-4db763d3a43d', 'name': 'torrents.home.cugnet.net', 'platform': 'LINUX', 'distro': 'es7-x86-64', 'ip': '192.168.101.130',
'last_scanned': 1562697438, 'plugin_feed_id': '201907091052', 'core_build': '322', 'core_version': '7.4.1', 'linked_on': 1486146462, 'last_connect': 1562758652, 'stat
us': 'off', 'groups': [{'name': 'Agents', 'id': 102}], 'supports_remote_logs': False}
>>> agents.next()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    agents.next()
  File "/Users/steve/.pyenv/versions/3.6.7/envs/py3tenable-dev/lib/python3.6/site-packages/tenable/base.py", line 74, in next
    raise StopIteration()
StopIteration
>>>
```

**Comment by I-Am-Buggy** [comment]
The problem may be how pyTenable is handling agents that are in multiple groups. That's the only thing I can think of that may be different between my environment and yours. I don't quite understand how that would be since you're essentially making the same API call, but that's all I've got.

The problem I'm trying to solve is we have a default group for all agents.  That default group isn't used for scanning.  I need to distribute these new agents on a weekly basis into one of the scan groups...this is done to keep the agent scan groups to a reasonable size.  My strategy was to query all agents not in one of the scan groups and then distribute them evenly.  Do you see a better way of doing this? In hindsight, it would have been best to remove the agents from the default group when they were redistributed.  That was an oversight on my part.

**Comment by SteveMcGrath** [comment]
Why not instead query all of the agents and look into the "groups" sub-doc and use that as your basis of what needs rebalancing?

I'll be honest, that group I used as a basis is a single-agent group, however that agent exists is several other groups as well and the API seems to perform as I expected it to.  pyTenable itself has no concept of what groups the agents are in, it just passes the request on to the API and then handles pagination through the iterator.  The calls all seem good, so I'm at a loss.  I'm going to mark this as a wont-fix question for now as I can't replicate the output you are receiving.  If you have any new information, please file in this issue and we can re-open and continue.
