### ISSUE TITLE
Ability to down and upload compliance audit files to tenable.io

### ISSUE THREAD

**Issue by maaren** [tenable/pyTenable#138]
**Is your feature request related to a problem? Please describe.**
Unless I am mistaken, I don't think it is possible to up- and download audit compliance files.

**Describe the solution you'd like**
We have our audit files under version control. I want to download them, compare them to the lastest in the repo, if they are different upload the latest in the repo and use that for the scan, so we know we always scan with the latest audit files available in the repo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SteveMcGrath** [comment]
Uploading is handled by passing the appropriate parameters in the compliance parameter dictionary && uploading the audit file using the files.upload method.  To understand how to construct the compliance parameter, I don't have a better answer right now other than inspecting the UI when creating a scan or policy with a custom audit.  Unfortunately I don't know of a way to download the audit file to validate, however I don't think thats the right pathway to be honest.

If it were me, I would be wiring a post-receive hook to your git repo that would automatically update your policies with the new audit files after every commit.  You could further fence this if you wish to only post on tagged commits, only do this on master, etc. depending on how you're managing that repo.  Downloading and comparing would be highly inefficient when its easier to just assume that this process is handling that instead ;)

**Comment by maaren** [comment]
OK, thanks! Will have a look.
