### ISSUE TITLE
Please provide access to the scans/history API

### ISSUE THREAD

**Issue by TYeung-esentire** [tenable/pyTenable#141]
Steve McGrath (Tenable Network Security, Inc.)

Secondly, the history is provided as part of the GET call to /scans/{id}, which you can fetch with TenableIO.scans.results(scanId). If you'd rather make the history call however, I could easily add it in, just file an issue ticket on the repo and I'll get it fit in.

I did code up a method directly to the history endpoint last night, and if you submit an issue to the repository, I can link that code to it for tracking purposes.

**Comment by SteveMcGrath** [comment]
Code to support this endpoint has been added and 0.3.25 will be released sometime next week to support it.  In the meantime, you can always pull from the dev branch with:

```
pip install git+git://github.com/tenable/pytenable.git#egg=pytenable
```
