### ISSUE TITLE
Schedule Format Documentation Errors

### ISSUE THREAD

**Issue by archer31** [tenable/pyTenable#144]
Documentation specifies that the schedule must include a `rrule` and a `start` if it is of the ical type. this is not what the code is actually looking for. the code looks for `repeatRule`.

I would submit a pull request to fix this but don't know if you want to change the code or the documentation.
likely should throw and error if type `ical` is specified without the other two names.

**Comment by SteveMcGrath** [comment]
can you be more specific and possibly link to some examples?

**Comment by archer31** [comment]
This issue relates to tenable.sc. the documentation states that the schedule dict should contain 1 or 3 keys. if it is an `ical` type then it should also include `start` and `rrule` as seen in the below example.
```
{
    'type': 'ical',
    'start': 'TZID=America/New York:20190214T090000',
    'rrule': 'FREQ=DAILY;INTERVAL=1'
}
```
I could only get the server to give a successful response (or a different error message as seen in #145) after i changed `rrule` to `repeatRule` (example below). which is what is being checked for in [base.py](https://github.com/tenable/pyTenable/blob/2f7476c00333bcc53b2aa9f8eb9fc97e64b017fe/tenable/sc/base.py#L204) of tenable.sc.
```
{
    'type': 'ical',
    'start': 'TZID=America/New York:20190214T090000',
    'repeatRule': 'FREQ=DAILY;INTERVAL=1'
}
```

**Comment by menri005** [comment]
#150 I made a small tweak in the schedule constructor that addresses this problem and makes it more consistent with the documentation
