### ISSUE TITLE
Timezone validation checking && Documentation

### ISSUE THREAD

**Issue by archer31** [tenable/pyTenable#145]
There is no documentation on how the `TZID` needs to be formatted (with a space `New York`, an underscore `New_York`, no space `NewYork`/ with a slash `America/NewYork` or a dash `America-NewYork`)

should do some error checking on client side rather than just blind printing the server error.

**Comment by SteveMcGrath** [comment]
for which package?

TenableIO has ScansAPI.timezones()
TenableSC has it stored away in the TenableSC.info param.

I do agree it should eventually be checked against, however it has a lower priority to getting some of the gaps in TenableSC's lib filled in.

**Comment by archer31** [comment]
This issue relates to tenable.sc. It would be useful to add more information about the timezone formatting to the help pages or add a comparable module to SC.
one of these discrepancies shows up in [base.py](https://github.com/tenable/pyTenable/blob/2f7476c00333bcc53b2aa9f8eb9fc97e64b017fe/tenable/sc/base.py#L70) and [repositories.py](https://github.com/tenable/pyTenable/blob/2f7476c00333bcc53b2aa9f8eb9fc97e64b017fe/tenable/sc/repositories.py#L299)

**Comment by SteveMcGrath** [comment]
refer to the info dict thats populated at instantiation.

```python
sc.info['timezones']
```
