### ISSUE TITLE
Very inconsistent performance with tio.exports.vulns

### ISSUE THREAD

**Issue by tonyyng** [tenable/pyTenable#146]
**Describe the bug**
Very inconsistent performance from tio.exports.vulns.  Occasionally takes hours to return.

**To Reproduce**
```
def cacheVulnerabilities():
    print(">>>> cacheVulnerabilities() starting")
    results = list()
    start = time.time()
    for v in tio.exports.vulns(severity=['low', 'medium', 'high', 'critical'], state=['open', 'reopened', 'fixed']):
        results.append(v)
    e = int(time.time() - start)
    elapsed = '{:02d}:{:02d}:{:02d}'.format(e // 3600, (e % 3600 // 60), e % 60)
    print(">>>> cacheVulnerabilities() cached %s items in %s" % (len(results), elapsed))
```

**Expected behavior**
Return within minutes.

**Screenshots**
One client with 255 vulns, usually returns within 5 seconds, takes 90 minutes.
Another client with 25000 vulns, usually returns within 1 minute takes 23 minutes
Another client with 10000 vulns, consistently takes 2 to 4 hours to return

**System Information (please complete the following information):**
 - OS: Windows 10
 - Architecture 64bit
 - Version python 3.7.3, pytenable 0.3.26
 - Memory 16GB

**Additional context**
Supporting multiple clients (containers?)  
Please contact me for the specific clients

**Comment by SteveMcGrath** [comment]
This isn't an issue with the library, more that the platform is loaded and your waiting in queue for your export to be processed.  The library simply queries the status endpoint until a chunk is available and then processes the chunk into the page list and iteratively returns the data in that list.
