### ISSUE TITLE
Since this morning I get: could not upload file 'filename.audit': duplicate filename limit exceeded

### ISSUE THREAD

**Issue by maaren** [tenable/pyTenable#147]
**Describe the bug**
I assume it is a backend problem, but I guess it could be solved in pyTenable. Not sure what the plan is. Since this morning my scripts using tenable.io give the following error: could not upload file 'filename.audit': duplicate filename limit exceeded. In the past and underscore number was added to the uploaded filename.
Yesterday this was working fine.

**To Reproduce**
Steps to reproduce the behavior using the GUI:
1. Go to the compliance tab and upload an existing file again. This triggers the same error.

**Expected behavior**
Upload the file with an underscore number.

**Comment by SteveMcGrath** [comment]
Thats something that the API is handling.  I know I had hit that in the past as well, however that has nothing to do with pyTenable.

**Comment by maaren** [comment]
Do you remember how you resolved it? I seem to be stuck... I have a policy with two audit files. I have deleted both files. I can upload only one, for the other I can only upload it if I use a different name, eg filename_1.audit.

**Comment by SteveMcGrath** [comment]
easiest way right now is to randomize the filename.

**Comment by SteveMcGrath** [comment]
I have added it as a late-stage FR.  low prio for now, but I have been known to pick off easy ones further down the stack for a quick win from time to time ;)

**Comment by maaren** [comment]
OK, I will add a few random characters for now. Still weird you cannot upload a file that you cannot see in the web GUI...

**Comment by maaren** [comment]
Well, it seems to be working again... Garbage collection in the background?
