### ISSUE TITLE
Cna't create credentials

### ISSUE THREAD

**Issue by igaralf** [tenable/pyTenable#154]
Hello
I am trying to create a credential with the below code:

from tenable.sc import TenableSC
import logging
logging.basicConfig(level=logging.DEBUG)
sc = TenableSC('servername')
sc.login('username', 'password')
cred = sc.credentials.create('Example SQL Server', 'database', 'SQL Server',username='sa',password='sekretpassword',sql_server_auth_type='SQL',sid='database_name')
sc.logout()

However, i am gettng the below error (other functions are working ok):
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): denueemap030:443
DEBUG:urllib3.connectionpool:https://servername:443 "GET /rest/system HTTP/1.1" 200 None
DEBUG:tenable.sc.TenableSC:path=token, query=REDACTED, body=REDACTED
DEBUG:urllib3.connectionpool:https://servername:443 "POST /rest/token HTTP/1.1" 200 282
Traceback (most recent call last):
  File "creds.py", line 13, in <module>
    cred = sc.credentials.create('Example SQL Server', 'database', 'SQL Server',username='sa',password='sekretpassword',sql_server_auth_type='SQL',sid='database_name')
AttributeError: 'TenableSC' object has no attribute 'credentials'

**Comment by SteveMcGrath** [comment]
Which version of pyTenable are you using?

**Comment by igaralf** [comment]
Hi.
Solved it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
