### ISSUE TITLE
Cannot set plugin preference in TSC policy

### ISSUE THREAD

**Issue by matteverson** [tenable/pyTenable#157]
**Describe the bug**
I cannot set a plugin preference in TSC. The preference displays in an exported scan result, but is unchanged. I can confirm no visible change is happening when using the Policies.edit method, by viewing the policy details immediately after setting the preference.

**To Reproduce**
1. Create TenableSC object and login
2. Run this code

```
sc.policies.edit(6, preferences={"Global variable settings[checkbox]:Thorough tests (slow)":"yes"})
policy = sc.policies.details(6)
pprint(policy)
```

This does not show the plugin preference in the policy, only scanner preferences.

**Expected behavior**
Using one of the scanner preference names, the change is displayed successfully.
For example:

```
sc.policies.edit(6, preferences={"arp_ping":"yes"})
policy = sc.policies.details(6)
pprint(policy)
```

**Comment by SteveMcGrath** [comment]
Thats because the preference you mentioned above isn't a valid one.  instead of `Global variable settings[checkbox]:Thorough tests (slow)` you'd instead use the setting `thorough_tests`.
