### ISSUE TITLE
TSC Accept_risks - All Hosts

### ISSUE THREAD

**Issue by jacobntr** [tenable/pyTenable#162]
pyTenable accept_risks does not accept "All hosts" and requires a int for the IP option.

The Tenable API accepts the the All hosts option. Can we please add this?

**Comment by SteveMcGrath** [comment]
IPs are passed as a list of string values as described here:

https://github.com/tenable/pyTenable/blob/master/tenable/sc/accept_risks.py#L62-L67

As for "all hosts".  That should be implicitly set in the create action, however isn't.
