### ISSUE TITLE
PyTenable Issue with library: Session/Networking?

### ISSUE THREAD

**Issue by ehgps** [tenable/pyTenable#164]
I'm having an issue with the pyTenable library (please see screenshot) in a python3 script. I have not gotten this error before. It looks like there is an error at 'tio = TenableIO(access_key=akey, secret_key=skey)'. Please see screenshot [here](https://community.tenable.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=0683a0000075Mxt&operationContext=CHATTER&contentId=05T3a00000NWx27), or attached
<img width="871" alt="Screen Shot 2019-11-05 at 10 31 24 AM" src="https://user-images.githubusercontent.com/57411199/68232198-916fa300-ffca-11e9-960d-03883ce2f8cb.png">

Background: This is on a new workstation than the initial workstation that the script works well on. Both workstations are windows based, and have all the required libraries installed.

What we know:
1. The new workstation can connect out to the internet,
2. This user can login to Tenable.io from the new workstation,
3. The API keys work on the initial workstation to run the script (the script, and API keys work fine),
4. We can run other scripts from the new workstation under a different (non-admin) user,
5. The user with the api keys, is not logged in elsewhere,
6. We have tried using different versions of python (it works on 3.7 and 3.8),
7. We have tried using a third workstation (with a different OS) and the script still works as expected,
8. As far as I can tell, I'm doing this exactly as documented here: https://pytenable.readthedocs.io/en/latest/io.html

**To Reproduce**
None.

**Expected behavior**
Normally, the script connects to Tenable IO fine.

**Screenshots**
Please see screenshot [here](https://community.tenable.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&versionId=0683a0000075Mxt&operationContext=CHATTER&contentId=05T3a00000NWx27), or attached

**System Information (please complete the following information):**
 - OS: Windows 
 - Architecture: 64x
 - Version: Multiple
 - Memory: 4+ GB

**Additional context**
N/A

**Comment by tenableAndrew** [comment]
Hi @ehgps it looks like this may be related to a recent change in version v0.3.28. In the meantime I _think_ reverting back to the previous version (v0.3.27) may resolve this error for you. You should not lose any functionality by revering to the earlier release.

The crux of the issue is in python's built-in library's portability across platforms. Specifically, the `os.uname` method is not available on Windows without cygwin. We will look into a platform agnostic replacement for this in an upcoming release.

**Comment by SteveMcGrath** [comment]
Note 0.3.29 is now released addressing this issue.  The underlying issue was a result of the new UA code, which was tested on posix systems w/o issue, however it was (wrongly) assumed that os.uname would work the same on non-posix (Windows) platforms.  If there are still any issues, please re-open.
