### ISSUE TITLE
SSLError("bad handshake...) while using pytenable from internal network

### ISSUE THREAD

**Issue by prabhakarcsetce** [tenable/pyTenable#166]
I am getting following error while using pytenable framework within company's internal network.
Is there any way to configure SSL for pytenable to resolve this issue? Thanks.

requests.exceptions.SSLError: HTTPSConnectionPool(host='cloud.tenable.com', port=443): Max retries exceeded with url: /scanners/1/agent-groups (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by SteveMcGrath** [comment]
Sounds like a problem with a proxy in between you and tenable.io.  The error is that the cert failed.
