### ISSUE TITLE
TIO Exports (vulns) Not Working Properly

### ISSUE THREAD

**Issue by ehgps** [tenable/pyTenable#169]
**Describe the bug**
Previously, tio.exports.vulns has been used to export vulnerability data. Today I cannot see vulnerability data.

**To Reproduce**
Create python script and add: 
```
vulnerability = tio.exports.vulns(num_assets=500, since=946684800)
for vuln in vulnerability:
    pprint(vuln)
```
NOTE: This is exactly as referenced [here](https://pytenable.readthedocs.io/en/0.3.29/io.html#exports) under vulns.
All of the vulnerability data is over 90 days old. I have tried using the epoch for 1/1/2000 to ensure we have vulnerability data

**Expected behavior**
This should note what vulnerabilities are available.

**Screenshots**
Nothing is happening. There is no list to go though. There is no iterable, even when passing in the UUID.
<img width="496" alt="Screen Shot 2019-12-16 at 11 46 40 AM" src="https://user-images.githubusercontent.com/57411199/70925819-ea831b80-1ff9-11ea-95ec-13533d2c09f6.png">

**System Information (please complete the following information):**
 - OS: Any
 - Version: 0.3.29+
 - Memory: 4GB +

**Additional context**
We have tried creating a new user, and giving them administrative permissions. We are using the format `tio = TenableIO(access_key=akey, secret_key=skey, retries=10, backoff=60.0)` to generate the tio object. We can use things like: user = tio.session.details() to note the username. This is correct, so the tio object is working. NOTE: tio.exports.assets works properly. tio.exports.vulns does not.

**Comment by SteveMcGrath** [comment]
I don't think this is a pyTenable issue, more of an exports API issue.  Can I ask you to file a ticket with Tenable support?

**Comment by ehgps** [comment]
I have submitted a ticket to support@tenable.com for this. Also, the developer portal is not working as expected ([here](https://developer.tenable.com/reference#exports-vulns-request-export)) I will proceed with the tenable support route. Looks like a larger issue here. Thanks Steve!
