### ISSUE TITLE
Adding a native way to retry if the other sides throws an error

### ISSUE THREAD

**Issue by SaltySolomon** [tenable/pyTenable#170]
**Is your feature request related to a problem? Please describe.**
Include a way to retry communication with the api, especially if I am calling the TenableSC API more I get a lot of API Errors due to SQLight DB Locks

**Describe the solution you'd like**
A way to define, possible during the creation of a tenable(SC) Object how often a call to the API should be retried and how often the back up should work. This could be achived via a decorator function the one I thought up is:

`def retry(retries=3, delay_multiplier=2, base_delay=60, jitter=10, allowed_exceptions=()):
    """
    Decorator Function. This Function retries the function if any of the allowed exceptions are thrown by the function.
    In this script it is primarily used to catch errors while trying to communicate with tenable.sc. This is primarily
    due to sqlite database locks
    :param retries: Number of retries that are attempted
    :type retries: int
    :param delay_multiplier: Multiplies the last retry time after each retry for exponential growth in retry time
    current delay = base_delay * backoff_multiplyer ^ (attempt - 1)
    :type delay_multiplier: int
    :param base_delay: The base time in seconds before retrying to execute a function
    :type base_delay: int
    :param jitter: This randomly adds to the back-off time for a try, the value given is the maximum
    :type jitter: int
    :param allowed_exceptions: The Exceptions that will trigger a retry, can be an Exception or tuple. If None it will
    retry on any exception
    :type allowed_exceptions: Exception or tuple
    """
    def decorator(f):

        @functools.wraps(f)
        def wrapper(*args, **kwargs):
            current_tries = retries
            current_delay = base_delay
            while current_tries != 0:
                try:
                    return f(*args, **kwargs)
                except allowed_exceptions as e:
                    msg = "%s, Retrying in %d seconds..." % (str(e), current_delay)
                    print(msg)
                    time.sleep((current_delay + random.randint(0, jitter)))
                    current_tries -= 1
                    current_delay *= delay_multiplier
            return f(*args, **kwargs)
        return wrapper
    return decorator`

**Describe alternatives you've considered**
I have created a wrapper function that retries it but its not possible to slim it down and for simple skripts it is a lot of additional work to get it to work right.

**Comment by SaltySolomon** [comment]
After reading the docs I feel like an idiot.

**Comment by SteveMcGrath** [comment]
The right path here would be to modify the error check code like so:

```
from tenable.sc import TenableSC

class TenableSCRetry(TenableSC):
    def  _resp_error_check(self, response, **kwargs):
        if not kwargs.get('stream', False):
            try:
                d = response.json()
                if d['error_code']:
                    if 'database is locked' in d['error_msg']:
                        response.status_code = 429
                    else:
                        raise APIError(d['error_code'], d['error_msg'])
            except ValueError:
                pass
        return response
```

from there you'd instantiate TenableSC slightly differently:

```
sc = TenableSCRetry('HOSTNAME', backoff=60)
sc.login('USER', 'PASS')
```

As for supporting this in the code itself, if you're running into a lot of these, it may be a health issue on the Tenable.sc instance you're running.  Database locks means that the host is likely undersized and/or on slow disk.
