### ISSUE TITLE
Get list of devices

### ISSUE THREAD

**Issue by mihaiobytex** [tenable/pyTenable#172]
Is there any way to get the list of devices with all the information associated ( id, name, ips, macAddress, etc) ? 

sc.asset_lists.list is returning asset lists: 
usable [{'id': '0', 'name': 'All Defined Ranges', 'description': 'All defining ranges of the Group in whose context this Asset is being evaluated.'}]

**Comment by SteveMcGrath** [comment]
Asset lists would return asset list metadata.  If you're looking for individual assets of data within the API, you may want to make an analysis call with the sumip tool.

https://pytenable.readthedocs.io/en/stable/sc.html#tenable.sc.analysis.AnalysisAPI.vulns
