### ISSUE TITLE
Password field does not update

### ISSUE THREAD

**Issue by huserasdorin** [tenable/pyTenable#173]
**Describe the bug**
The fields **name** and **username** does update in the SC, but **password** does not change using **sc.credentials.edit** call.

**To Reproduce**
1. Create a new Credential (Windows - Password) in tenable SC, and save the id for  in **credentialId** variable 
2. Setup the connection using: 
sc = TenableSC(tenableScUrl)
sc.login(tenableUser, userPassword)
3. Edit the credentials with the id: **credentialId**
sc.credentials.edit(credentialId, name="newName", username="newUsername", password= "newPassword")

**Expected behavior**
All the fields should be changed to the the ones previously set. 
**Actual results**
The **name** of credential is set to "newName", the **username** is set to "newUsername" but the **password** is **not changed**. 

**Dev System Information:**
 - OS: Windows 10 Enterprise 
 - Architecture 64 bit
 - Memory 16 G

**Tenable SC System Information:**
 - OS: CentOS 7.7.1908 Core
 - Architecture 64bit (arch x86_64)
 - Version Kernel 3.10.0-1062.1.1.el7.x86_64
 - Memory 125 G

**Comment by SteveMcGrath** [comment]
how are you validating that the password hasn't changed?  the API will always return the value of "SET" for the password when querying for the credential.  It's never exposed after being inserted into the platform.

**Comment by huserasdorin** [comment]
Hello, 
To validate that the authentication with credential is working, I do have a **Active Scan** template in the SC console. 

- For that template I'm using the credential with **credentialId**(mentioned early), and a host. 

- When i set manually the username and password( "newUsername", "newPassword") using the SC console, in the scan results, I can see that the authentication worked with the given credentials. 

- This is the base line, this is how I can check if the credential set is good, the scanner is set up correctly and that the credentials are working for the host that I provided. 

In order to check if the python script is working:

- Open the SC console and change for the "credentialId" the user and password to some random ones

- In the python script I will add the correct username and password(that i previously checked)
sc.credentials.edit(credentialId, username="newUsername", password= "newPassword")
-  After the python script had ran, I will open the credential in SC console  with the **credentialId**  and i can see that the "Last Modified" date had updated, and also the username is changed to "newUsername". 

- When I trigger again the **Active Scan** template, this time the authentication is not working.

- So doing all those steps I can conclude that the password filed is not updating correctly.

**Comment by SteveMcGrath** [comment]
Honestly i don't know whats happening there.  I looked at what the UI does && what pyTenable does and the calls are functionally identical.  Further when I submit the PUT the fields all now have a different hash.  It all looks work on my test 5.8 instance and my 5.13 instance...

```python
>>> with TenableSC('tenablesc.home.cugnet.net', username='steve', password='XXX') as sc:
...     c = sc.credentials.edit(c['id'], password='newpass2')
...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tenablesc.home.cugnet.net:443
DEBUG:urllib3.connectionpool:https://tenablesc.home.cugnet.net:443 "GET /rest/system HTTP/1.1" 200 None
DEBUG:tenable.sc.TenableSC:path=token, query=REDACTED, body=REDACTED
DEBUG:urllib3.connectionpool:https://tenablesc.home.cugnet.net:443 "POST /rest/token HTTP/1.1" 200 286
DEBUG:tenable.sc.TenableSC:path=credential/1000001, query={}, body={'password': 'newpass2'}
DEBUG:urllib3.connectionpool:https://tenablesc.home.cugnet.net:443 "PATCH /rest/credential/1000001 HTTP/1.1" 200 800
DEBUG:urllib3.connectionpool:https://tenablesc.home.cugnet.net:443 "DELETE /rest/token HTTP/1.1" 200 100
```
