### ISSUE TITLE
Upload File Obj to Asset List API

### ISSUE THREAD

**Issue by joseph3325** [tenable/pyTenable#177]
Hello, I am trying to create/update a large static IP asset list through Tenable.sc

The docs say this is done by passing a File Like Object to the `fobj` keyword in the `sc.asset_lists.edit()` method. However, when I do this I receive this error: `NameError: name 'fobj' is not defined`

Looking at line 154 of the `asset_lists.py` file it looks like the variable `fobj` is being passed as an arg without ever being declared. Am I understanding this right or am I missing something???

**Comment by SteveMcGrath** [comment]
can you please enable debug logging and post the debug logs?
