### ISSUE TITLE
Tenable API: pyTenable tenable.sc.analysis.AnalysisResultsIterator object, can only iterate over object once 

### ISSUE THREAD

**Issue by AJLabozzo** [tenable/pyTenable#183]
**Describe the bug**
When working in the Tenable Nessus API if I attempt to iterate through an analysis.scan() object for information I can only do so once. Any further attempts will result in no values being returned. Why is this the case? If I want to loop through the same object multiple times I will have to repeatedly query sc.analysis.scan(scanID).

**To Reproduce**
1. Log into Tenable API 

2. repeat code 
>>> vuln132 = sc.analysis.scan(132) # 132 is changeable with any Scan Results ID
>>> ip = []
>>> for vuln in vuln132:
... ip.append(vuln.get('ip'))
...
>>> print(len(ip))
35
>>> ip = []
>>> for vuln in vuln132:
... ip.append(vuln.get('ip'))
...
>>> print(len(ip))
0
>>> print(vuln132)
<tenable.sc.analysis.AnalysisResultsIterator object at 0x7fc38bffde50>

ProductPlease choose the product this support case is for
Tenable.sc
Product VersionWhat version of this product is this case for
5.13.x

**Expected behavior**
I expected to duplicate the results of the first for loop I ran appending IP address to an empty list. But if repeating the same process without recalling to a variable sc.analysis.scan(ScanID) will return nothing.

**Screenshots**
![pyTenableObjectIteration](https://user-images.githubusercontent.com/33766261/73784918-477e9080-4764-11ea-9dc7-a9ece9a4de78.PNG)

**System Information (please complete the following information):**
 - OS: Fedora Linux
 - Architecture: 64-bit
 - Version:
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
 - Memory: 4096 MB

Product
Tenable.sc
Product Version
5.13.x

**Additional context**
I'm using the API in a ORACLE VM VirtualBox machine. I log into Tenable.SC using  API key pair credentials to query for scan results to retrieve vulnerability information.

**Comment by AJLabozzo** [comment]
Previous Tenable community case: 00966717
Support Engineer said:
Feb 4, 2020 1:29:00 PM
Hello,
For questions regarding pyTenable and all of it's components, you'll want to open an Issue with the pyTenable team here:
https://github.com/tenable/pyTenable/issues
Standard support is unable to assist with these but our API team behind the pyTenable github page answers the issues posted there.

Please let me know if that helps with your question or issue, or if you have any further questions please feel free to ask. If I answered all your questions, am I able to close this case? Thank you

Contact Support:
https://community.tenable.com/s/
Kind regards, 
 - Security+ 
Tenable Technical Support Engineer 
Tenable.com
ref:_00D30pZp._5003ayOx0S:ref

**Comment by adammike** [comment]
This is standard python generator behavior. if you want to iterate over the results multiple times I would suggest casting it as a list() object.

```python
vuln132 = list(sc.analysis.scan(132))
ip = []
for foo in vuln132:
  ip.append(foo.get('ip))
len(ip)

ip = []
for foo in vuln132:
  ip.append(foo.get('ip))
len(ip)
```

**Comment by SteveMcGrath** [comment]
Echoing @adammike’s comments, you’re only supposed to be able to iterate over a Iterator once, as the iterator is maintaining state.  This is both pythonic and by design.

Why not perform all of the actions you need within the first loop?
