### ISSUE TITLE
Trouble with the fobj argument

### ISSUE THREAD

**Issue by dshock2** [tenable/pyTenable#184]
This is actually tied to a previous post i read earlier this week.  I am having similar issue to this post:

Pytenable Post I read before but didn't quite follow:
fobj should be kw[‘fobj’] #177

**I am able to get the following to work perfectly:**
sc.asset_lists.create(name = 'DevAssetList3', list_type = 'static', ips = ['192.1.1.2', '192.2.2.3'])

However I CANNOT get this to work.  
The error i get is:  NameError: name 'fobj' is not defined

**Code I am using that gets the error above:**
sc.asset_lists.create(name = 'DevUpload', list_type = 'upload', fobj = ('devlist.txt'))

**Method:**
1. I am trying to create an Asset list named DevUpload.
2. I have a txt file, named devlist.txt, with a list of IP addresses.
3.  I am trying to upload the list of IP addresses to the DevUpload Asset list

I think I am getting the fobj syntax all wrong.  (I am fairly new to python/api).  

Can someone share what the syntax for fobj is supposed to be...please?

Thank you in advance.

**Comment by SteveMcGrath** [comment]
yes your syntax is wrong, however first you may want to make sure you're on the latest version of pyTenable (1.0.5 as of writing).  To see that, simply use pip show:

```bash
❱ pip show pytenable                                                                                                                                                                   1
Name: pyTenable
Version: 1.0.5
Summary: Python library to interface into Tenable's products and applications
Home-page: https://github.com/tenable/pytenable
Author: Tenable, Inc.
Author-email: smcgrath@tenable.com
License: MIT
Requires: requests, python-dateutil, semver, ipaddress
```

Now once you have the latest version, you can do the following:

```python
>>> with TenableSC('ADDRESS', username='USER', password='PASS') as sc:
...     with open('devlist.txt') as listfile:
...         sc.asset_lists.create('DevUpload', 'upload', fobj=listfile)
```

You have to pass a FileObject, not a string of the name of the file.
