### ISSUE TITLE
Question Pytenable and Analysis

### ISSUE THREAD

**Issue by zepernick03** [tenable/pyTenable#185]
Beginner using Pytenable:
What is the next step to write this output to a CSV file? Is there a forum or community resource?

from tenable.sc import TenableSC
import pprint
import getpass

#Tenable login info
username = 'name'
p = getpass.getpass(prompt='Password:')

sc = TenableSC('URL')
sc.login(username,p)
      
for vuln in sc.analysis.vulns(('pluginID','=','125063,125073,125060,125313'),tool='vulndetails'):
    print('{ip}:{pluginID}:{pluginName}:{severity}'.format(**vuln))
     
  
sc.logout()

**Comment by SteveMcGrath** [comment]
You may want to look at the CSV library.

https://docs.python.org/3/library/csv.html

**Comment by zepernick03** [comment]
Can I simply write my output to a text file? Using something like this?
def main():
    file = open("alerts.txt","w")

    file.write("here is the query"
    file.close()

if __name__== "__main__":
    main()

**Comment by SteveMcGrath** [comment]
thats all up to you at that point.
