### ISSUE TITLE
TIO Access Group Criteria automatically parse out required information

### ISSUE THREAD

**Issue by jwoodsj-net** [tenable/pyTenable#190]
When creating an access group from a list of IP addresses, these addresses must be in CIDR notation (X.X.X.X/32) in order for the access group in TIO to correctly interpret them. However, when passing a CIDR notation single IP through the access_groups.create() function, it automatically strips out the CIDR notation, meaning that the access group does not include those criteria.

To reproduce:
Create an access list and attempt to create a group from it:
>>> alist = [('ipv4','eq',['192.168.0.1/32','192.168.1.1/32'])]
>>> tio.access_groups.create('Test',alist)
{u'status': u'PROCESSING', u'processing_percent_complete': 0, u'all_assets': False, u'container_uuid': u'XXXXXX', u'rules': [{u'operator': u'eq', u'terms': [u'192.168.0.1', u'192.168.1.1'], u'type': u'ipv4'}], u'created_by_name': u'XXXXXXXXX', u'created_at': u'2020-02-28T08:36:20.548Z', u'updated_at': u'2020-02-28T08:36:20.548Z', u'all_users': False, u'updated_by_name': u'XXXXXXXXX', u'version': 1, u'created_by_uuid': u'XXXXXXXXX', u'updated_by_uuid': u'XXXXXXXXX', u'id': u'XXXXXXX', u'name': u'Test'}

You can see from the output creation the differences between the rules specificed and the rules actually created.

**Comment by SteveMcGrath** [comment]
The library does no modification to the rules you have specified beyond converting the tuple into the correct format.  As verification, you may want to enable debug logging and see what is actually being passed to the API.
