### ISSUE TITLE
Audit_files method template_list() is unusable

### ISSUE THREAD

**Issue by galenr** [tenable/pyTenable#195]
**Describe the bug**
Non-existent id argument being checked by the audit_files.template_list endpoint. Code throws an error complaining about built-in id function being passed instead of an expected int. 

**To Reproduce**
1. Call the audit_files.template_list() method

**Additional context**
Looks like the api call to /auditFileTemplate in template_list() was copied from template_details() with type checking on an id that isn't being passed into the function.
https://github.com/tenable/pyTenable/blob/5c8374539bc766721def9fbb7fdee0819e3b6bb5/tenable/sc/audit_files.py#L437

**Comment by SteveMcGrath** [comment]
easy enough to fix ;)
