### ISSUE TITLE
Tenable.IO Scan Exports Contain No Data

### ISSUE THREAD

**Issue by d0n601** [tenable/pyTenable#196]
**Bug Description**
Tenable.IO scans only display column when exported via the `scans.export` function. I first wrote my own code and assumed I'd been doing something incorrect. After running the demo from this repository though, I've confirmed that the results are the same.

**To Reproduce**
1. Go to the [demo](https://github.com/tenable/pyTenable/tree/master/examples/io/download_scans).
2. Run the demo. I've been trying to use the --search flag, both with nessus and csv file types.
3. Open up the csv files and see only the column  names.
4. Export the same scan via the Tenable.IO web console, and compare the csv file that has many rows.

**Expected behavior**
I would expect the exported csv from the API to match the exported scan csv from the web UI.

**Screenshots**
Blank csv

![Screenshot from 2020-03-26 13-40-54](https://user-images.githubusercontent.com/8961705/77694622-92987100-6f67-11ea-93ae-ba13435bf152.png)

I cannot include my expected output as it is corporate information. But you imagine what it looks like by picturing 99 rows of information instead of none. 

**System Information (please complete the following information):**
 - OS: Windows 10
 - Architecture 64bit
 - Python Version 3.7

**Comment by SteveMcGrath** [comment]
I ran the example script as described and cannot replicate.  Everything appears to be working as expected.

```
❱ ./download_scans.py -r csv -s test
Scan completed at 2020-01-17T20:16:19+00:00 downloading to ./Test_Scan-28b921b2-38d7-4c55-b886-80f81a2e3c37.csv
Scan completed at 2019-11-01T17:01:48+00:00 downloading to ./Rune_Test-6a2fea81-5d06-4fad-934e-5eef6e24acc2.csv
Scan completed at 2019-07-25T17:23:18+00:00 downloading to ./Test_Scan-0de5d6ed-6b56-432b-bbce-3b668ab286f4.csv
Scan completed at 2019-03-08T22:16:45+00:00 downloading to ./test_abort-df4538cb-41d4-4f79-8c12-da3bed8f30cf.csv
Scan completed at 2019-11-14T22:13:48+00:00 downloading to ./testbox_agent_scan.-574bb786-f1fc-4693-bd1d-4de104d70c17.csv
```

Further opening the files yields the correct data

**Comment by d0n601** [comment]
I switched over to the standard REST API using python and the requests library, I'm getting the same issue over there. It's becoming clear to me now that there's simply something I must be missing about how exporting these reports is supposed to work through the API. That's something I'll need to figure out, but I don't think there's an issue with the pyTenable library. Closing the issue.
