### ISSUE TITLE
Export_audit without a provided file-like object fails.

### ISSUE THREAD

**Issue by galenr** [tenable/pyTenable#197]
**Describe the bug**
BytesIO is not imported from io in tenable/sc/audit_files.py

If you call the export_audit() method without providing a file object the function attempts to instantiate a BytesIO object and fails with

NameError: name 'BytesIO' is not defined

**Comment by SteveMcGrath** [comment]
yeah looks like i forgot about that.  Thankfully an easy fix ;)
