### ISSUE TITLE
exports.vulns plugin_family argument not case insensitive

### ISSUE THREAD

**Issue by 0secure** [tenable/pyTenable#199]
**Describe the bug**
When attempting to export vulnerabilities using the exports.vulns function, the plugin_family argument is not case sensitive.  Documentation states it should be:

> plugin_family (list, optional) – list of plugin families to restrict the export to. values are interpreted with an insensitivity to case.

**To Reproduce**
1. Attempt to export vulnerabilities with the plugin family in all lowercase.  Nothing is returned.  
Example: `vulns = tio.exports.vulns(plugin_family=['settings',])`
Note that no vulnerabilities are returned
2. Attempt the same export with proper case: `tio.exports.vulns(plugin_family=['Settings',])`
Note that vulnerabilities are returned.

**Expected behavior**
the 'plugin_family' argument to exports.vulns is case insensitive.

**System Information (please complete the following information):**
 - OS: Kali Linux via WSL on Windows 10
 - Architecture: 64bit
 - Version: 1.1.1
 - Memory 16GB

**Additional context**
Documentation referencing case insensitivity found at https://pytenable.readthedocs.io/en/latest/io.html#exports

**Comment by SteveMcGrath** [comment]
The upstream API that pyTenable is interacting with is case sensitive.  To support insensitivity in this case would require additional calls to be made.

**Comment by 0secure** [comment]
Thanks, Steve.  In that case, I recommend updating the pyTenable documentation to reflect that the field is case sensitive.
