### ISSUE TITLE
SecurityCenter Scan Policy API Endpoints

### ISSUE THREAD

**Issue by SteveMcGrath** [tenable/pyTenable#20]
The following API endpoints shall by pythonized and reside within the policies.py module.  These methods shall be fully tested:

* Scan Policy
* Scan Policy Templates

**Comment by mikeadamz** [comment]
Hi. I was just about to write my own library to do integrate some tooling with the security center API. I am in the position to contribute to this project instead. Is there a way we can chat and discuss this?

**Comment by SteveMcGrath** [comment]
Happily.  Hit me up on email: smcgrath@tenable.com

**Comment by SteveMcGrath** [comment]
df032ede
