### ISSUE TITLE
Documentation of sc.scanners.create

### ISSUE THREAD

**Issue by rs904c** [tenable/pyTenable#200]
The documentation at https://pytenable.readthedocs.io/en/stable/sc.html#scanners
Specifically for sc.scanners.create

I noticed that this documentation is missing parameters for:
"authType"
"username"
"password"

These paramaters exists, but aren't documented on the read the docs site.

**Comment by SteveMcGrath** [comment]
as those parameters are passed through directly, you just specify them.  As a rule, the SC docs only detail the parameters that either differ from the API, or are explicitly required for some reason.  This is the same reason why every possible parameter isn't defined for scans, for example.

**Comment by SteveMcGrath** [comment]
For reference, see: https://pytenable.readthedocs.io/en/stable/sc.html#common-themes

**Comment by rs904c** [comment]
If it isn't documented, then many users won't know to pass them.

**Comment by SteveMcGrath** [comment]
While i get where you're going, its a documentation nightmare to do that with all of the endpoints.  The point of the common themes part of the docs was to outline that anything not explicitly called out, can be implicitly passed in the keyword arguments.

**Comment by rs904c** [comment]
This is exactly the reason why I can't trust your documentation!!!!
I have to use a proxy with the web interface to verify interactions with SC.

**Comment by SteveMcGrath** [comment]
You could simply goto the linked official API docs.  It's why every endpoint links to the appropriate API docs.  In this specific example, the scanners.create method has the link labeled "scanner: create" that links to the official docs:

https://pytenable.readthedocs.io/en/stable/sc.html#tenable.sc.scanners.ScannerAPI.create

links to:

https://docs.tenable.com/tenablesc/api/Scanner.htm#scanner_POST
