### ISSUE TITLE
Documentation is not clear that the settings object is already set

### ISSUE THREAD

**Issue by ambrosy-eric** [tenable/pyTenable#202]
**Is your feature request related to a problem? Please describe.**
When trying to use in api call in a **kw parameter, the api documentation lays out the format required as {"settings":{"target_groups":[null]}}, but for pytenable the settings object is already assumed in https://github.com/tenable/pyTenable/blob/master/tenable/io/scans.py#L176-L178 and so the documentation is not clear.

**Describe the solution you'd like**
Changing 

> **kw (dict, optional) – The various parameters that can be passed to the scan creation API. Examples would be name, email, scanner_id, etc. For more detailed information, please refer to the API documentation linked above.

to something like _The various parameters that can be passed to the scan creation API assume the settings object and it does not need to be passed to the endpoint..._

**Describe alternatives you've considered**
Another place in the documentation that summarizes parameters use and includes that references to api setting parameters assume the setting object

**Additional context**
This issue opened in reference to https://community.tenable.com/s/feed/0D53a00006wY0ABCA0

**Comment by SteveMcGrath** [comment]
API documentation affected:

https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.configure
https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.create
