### ISSUE TITLE
IO Connectors API

### ISSUE THREAD

**Issue by jelatta** [tenable/pyTenable#204]
**Is your feature request related to a problem? Please describe.**
Would like to automate AWS connectors with pytenable. When we create new AWS accounts, configure Tenable AWS Connector.  Will use the RAW API in the meantime.

**Describe the solution you'd like**
A class for dealing with the Connector API

**Describe alternatives you've considered**
Tenable provides the APIs

**Additional context**

**Comment by jelatta** [comment]
these APIs, sorry https://developer.tenable.com/reference#connectors

**Comment by SteveMcGrath** [comment]
these endpoints have largely fluid definitions.  I'd likely just end up presenting a kwargs for the params dict and perform no checking within it.

**Comment by jelatta** [comment]
Good point, that's fine with me.

**Comment by SteveMcGrath** [comment]
These APIs are to be included in the v2 codebase (already coded up infact), however will likely not make their way in until then.  In the meantime, you can always use the raw verbs

https://pytenable.readthedocs.io/en/stable/io.html#raw-http-calls

**Comment by jelatta** [comment]
That's fine, thank you!
