### ISSUE TITLE
Casing incorrect for SSH publickey credentials

### ISSUE THREAD

**Issue by db4soundman** [tenable/pyTenable#210]
https://github.com/tenable/pyTenable/blob/8f44d390709d783f3ce6687848843f82deed5b51/tenable/sc/credentials.py#L610
https://github.com/tenable/pyTenable/blob/8f44d390709d783f3ce6687848843f82deed5b51/tenable/sc/credentials.py#L667

Per the credential API page (https://docs.tenable.com/tenablesc/api/Credential.htm) the auth type for key pairs is cased as "publickey" while credentials.py shows an example, and checks against "publicKey"

**Comment by ggolawski** [comment]
This change reintroduces https://github.com/tenable/pyTenable/issues/122. When I use auth type `publickey`, I get `Map not found for authType 'publickey'.` error.

It seems that the API documentation is wrong and the correct auth type is `publicKey`.
