### ISSUE TITLE
Export the history of a scan containing "all assets with their vulnerabilities"

### ISSUE THREAD

**Issue by hectorbolivar** [tenable/pyTenable#213]
Good afternoon, I am trying to export the history of a scan containing "all assets with their vulnerabilities", but I have only found through the following link https://developer.tenable.com/reference#scans-export-request to export the vulnerabilities of a single asset within a specific scan.

How could I carry out this consultation?

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.export
