### ISSUE TITLE
Limit on agents list endpoint has no effect

### ISSUE THREAD

**Issue by jakemalley** [tenable/pyTenable#216]
**Describe the bug**
Result limiting on the agents list endpoint does not work via the `limit` keyword.

**To Reproduce**
Steps to reproduce the behaviour:
```
>>> from tenable.io import TenableIO
>>> tio = TenableIO()
>>> agents = [agent for agent in tio.agents.list(limit=1)]
>>> len(agents)
3
>>> 
```

**Expected behavior**
Expected `len(agents)` to be `1` rather than `3`
(3 is the total number of agents linked in this case)

**System Information:**
- Python Version: 3.6.8
- pyTenable Version: 1.3

**Comment by SteveMcGrath** [comment]
That behavior is correct.  I'm confused as to why you're trying to convert the iterator into a list.

**Comment by jakemalley** [comment]
The list was a simple example to show the expected behaviour did not work, if this is as designed, then fair enough, however the documentation for the limit parameter describes it as "the number of records to retrieve", I think one would reasonably expect this to be the total number of records to be retrieved rather than "the number of records to retrieve per page".

To be more precise the use case for the limit parameter here is to display a list of Agents using DataTables (https://datatables.net/reference/option/ajax) using an AJAX request. So if I wanted to return a JSON object containing the 2nd page of 15 Agents, via the API I would use the parameters `?limit=15&offset=15`. I have currently solved this by using `agents_iterator` = tio.agents.list(limit=15, offset=15)` and then `itertools.islice(agents_iterator, 15)` is this as expected?

**Comment by SteveMcGrath** [comment]
Now im extra confused.  If you're using datatables, why not just have datatables make the request directly?  Your effectively trying to undo the pagination logic the iterator is handling for you.

**Comment by SteveMcGrath** [comment]
or just proxy the connection and add the header at the proxy in transit.

**Comment by jakemalley** [comment]
Well yes, that is what I am attempting to do using the pyTenable library essentially, but thanks for the help I will close this issue and just directly proxy the HTTP request.
