### ISSUE TITLE
Editing Schedule to dependent scan

### ISSUE THREAD

**Issue by CodeHunterX** [tenable/pyTenable#219]
I've struggled with implementing an api call to modify a scan to be dependent from on demand.

`jsonLoad = {"start":"","repeatRule":"","dependentID":644,"type":"dependent"}
result = sc.scans.edit(1573,schedule=jsonLoad)`

The above API line gives the error:
{"type":"regular","response":"","error_code":147,"error_msg":"Dependent Schedule
requires a Scan.\n","warnings":[],"timestamp":1593196757}

This was working in version 0.X. Can someone point me to the changes?

**Comment by SteveMcGrath** [comment]
looks like the problem revolves around the schedule constructor and centralization of schedules.  As the parameters are poorly documented in this regard, the attribute wasn't being checked for.
