### ISSUE TITLE
Tenable.io Import Scan (Example)

### ISSUE THREAD

**Issue by hectorbolivar** [tenable/pyTenable#221]
Good afternoon, I request your support with the following query: there is an example that allows importing a scan into T.io, we are starting to work with the APIs and we have very little knowledge.

We tried from the Tenable APi Explorer, but it does not give us positive results.

**Comment by SteveMcGrath** [comment]
you mean? https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.import_scan

**Comment by hectorbolivar** [comment]
Yes, I have reviewed the document, but as I commented at the beginning of the post, I have little knowledge in the area, but I would like to know if this code that we are using is correct because it does not compile correctly:

`from tenable.io import TenableIO
dude = TenableIO ('TIO_ACCESS_KEY', '')
with open ('TIO_SECRET_KEY')
with open ('example.nessus') as reportobj:
    tio.scans.import (reportobj)`

I get the following error:

> File "import.py", line 4
    tio.scans.import (reportobj)
              ^
SyntaxError: invalid syntax

**Comment by SteveMcGrath** [comment]
I dont know what that is, but if you use the example, it should look like this:

```python
from tenable.io import TenableIO

tio = TenableIO('ACCESS_KEY', 'SECRET_KEY')

with open('example.nessus') as nessus_file:
    tio.scans.import_scan(nessus_file)
```

**Comment by hectorbolivar** [comment]
Thanks for the support, your answer has worked.

What I was doing in my code is that it didn't replace the "reportobj" with nessus_file, for example it executed the code like this:

with open('myscan.nessus') as reportobj:
... tio.scans.import(reportobj)

But I see that it had to be replaced.

By the way, do you have a glossary that indicates that some sentences should be replaced? (As I have mentioned I am a beginner in the use of the API).

**Comment by SteveMcGrath** [comment]
variable naming should not matter. Unless you're using "..." to denote spaces, i dont know what your issue is.  In either case, as the example works, you should be able to work it out from there ;)
