### ISSUE TITLE
Cannot get a list of hosts when calling `scans.details`

### ISSUE THREAD

**Issue by Hex052** [tenable/pyTenable#225]
**Describe the bug**

Cannot get a list of hosts when calling `scans.details`, as I would expect from the [API](https://developer.tenable.com/reference#scans-details).

**To Reproduce**
```py
from tenable.io import TenableIO
tio = TenableIO('ACCESS_KEY', 'SECRET_KEY')
for key in tio.scans.details(98): # Put whatever a real scan ID is in your env here
    print(key)
```
There is no key `hosts`.

**Expected behavior**
There is a member `hosts` containing a list of hosts, and their asset and host IDs.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows 10
 - Architecture: 64-bit
 - Version: Python 3.8.5
 - Memory: 16GiB

**Additional context**

**Comment by Hex052** [comment]
Ahh, heck. Figured it out as soon as I created this. So in case anyone else comes across this, you're looking for [`scans.results`](https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.results) and not `scans.details`. Should a note maybe be added to the [docs](https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.scans.ScansAPI.details) to tell people that?

**Comment by SteveMcGrath** [comment]
Yeah, its one of those cases where the API breaks REST.  the current structure _makes sense_ from the perspective of the details method pulls the definition of the scan (as a PUT updates the definition) whereas the results method handles the GET call to get the last scan results/details.

I can make a note to look at the results method, I just assumed that the distinction was clear.
