### ISSUE TITLE
pip3 install pytenable does not include restfly in its list of dependencies

### ISSUE THREAD

**Issue by starblast** [tenable/pyTenable#226]
/]# python3    
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tenable.sc import TenableSC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/tenable/sc/__init__.py", line 69, in <module>
    from tenable.base.v1 import APISession
  File "/usr/local/lib/python3.6/site-packages/tenable/base/__init__.py", line 1, in <module>
    from .v1 import *
  File "/usr/local/lib/python3.6/site-packages/tenable/base/v1.py", line 26, in <module>
    from tenable.utils import url_validator
  File "/usr/local/lib/python3.6/site-packages/tenable/utils.py", line 1, in <module>
    from restfly.utils import dict_merge, url_validator
ModuleNotFoundError: No module named 'restfly'

]/:# pip3 install pytenable
Requirement already satisfied: pytenable in /usr/local/lib/python3.6/site-packages (1.2.0)
Requirement already satisfied: requests>=2.19 in /usr/local/lib/python3.6/site-packages (from pytenable) (2.24.0)
Requirement already satisfied: python-dateutil>=2.6 in /usr/local/lib/python3.6/site-packages (from pytenable) (2.8.1)
Requirement already satisfied: semver>=2.8.1 in /usr/local/lib/python3.6/site-packages (from pytenable) (2.10.2)
Requirement already satisfied: ipaddress>=1.0.22restfly>=1.3.5 in /usr/local/lib/python3.6/site-packages (from pytenable) (1.0.23)
Requirement already satisfied: marshmallow>=3.6 in /usr/local/lib/python3.6/site-packages (from pytenable) (3.7.1)
Requirement already satisfied: python-box>=4.0 in /usr/local/lib/python3.6/site-packages (from pytenable) (5.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.19->pytenable) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.19->pytenable) (1.25.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.19->pytenable) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.19->pytenable) (2.10)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2.6->pytenable) (1.15.0)

**Comment by SteveMcGrath** [comment]
Thanks for that catch!

**Comment by SteveMcGrath** [comment]
As the codebase starts to use restfly more, the testing suite will be updated to match and perform a much closer to "cleanroom" testing regimen to catch stupid issues such as this.  Thankfully the requirements almost never get new stuff in them, as this is the first set of new requirements in over a year.

**Comment by SteveMcGrath** [comment]
Released in 1.2.1
