### ISSUE TITLE
help with csv export for tenable sc

### ISSUE THREAD

**Issue by umpa385** [tenable/pyTenable#232]
I took a look at the documentation, but still having issues exporting as a csv file for scan results. I know I can export as a nessus file, but is there a way to export it like how I can in the GUI, using export as csv?

**Comment by SteveMcGrath** [comment]
"exports" to CSV are reports in SC.  Generally speaking exporting to CSV without some additional context is a "bad idea" as there are some fields that can overflow the fields in CSV & Excel.  That said, you _can_ do it, it's just not something that comes up often, as CSV exports are easy to setup in the GUI, and JSON data is much easier to process for machine-to-machine communication.

**Comment by umpa385** [comment]
Is there a way I can export it as a json object instead?

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/sc.html#tenable.sc.analysis.AnalysisAPI.vulns

**Comment by umpa385** [comment]
Ty for your help on this, hitting one small snag, I'm trying to get data
from the patched source as well as filter on vpr, is it possible to have
two filters like that?
