### ISSUE TITLE
Tenable.sc Credentials - Password shown in clear text in debug

### ISSUE THREAD

**Issue by thathaneydude** [tenable/pyTenable#236]
When creating or updating credentials, the password in the payload is shown in the debug logs. The "credential" endpoint should be added to the restricted endpoints to hide any credentials being logged. 

https://github.com/tenable/pyTenable/blob/f7063d70fef250adb6b0807f1198e6494169dc81/tenable/sc/__init__.py#L187

**Comment by levwais** [comment]
@thathaneydude - do you still see this issue? can we close it?
thanks.
