### ISSUE TITLE
Agents API Call Returns Tenable UUID instead of Asset ID 

### ISSUE THREAD

**Issue by dominicsalas** [tenable/pyTenable#238]
**Is your feature request related to a problem? Please describe.**

API documentation https://developer.tenable.com/reference#agents states **"The UUID of the agent. Note: This value corresponds to the ID of the asset where the agent is installed. You can use this attribute to match agent data to asset data."** This is incorrect. The Agent UUID is actually the Tenable UUID which is different from the Asset ID. 

**Describe the solution you'd like**

It would be helpful to be able to filter assets comparable to what is currently being done with agents when you call `tio.agents.list()`

Tenable UUID that is returned by Agent API calls, which looks identical to the Asset ID. 
 
`agent_uuid = '00000000-0000-0000-0000-000000000000'`
- Not sure if you'd need to remove the hyphens since the teanble uuid in the UI doesn't contain any hyphens

```
agent_uuid = '00000000000000000000000000000000'

>>> asset = tio.assets.list(('tenble_uuid', 'eq', 'agent_uuid') )
```

**Describe alternatives you've considered**

The Tenable.IO API would need to be fixed to have Agents return the Asset ID instead of the Tenable UUID. 

**Additional context**

You will see the Agents UUID if you use `tio.agents.list()` or `tio.agents.details(id)`. I have manually tested the tenable.io API and have tested it using the pyTenable module. I also double checked with the UI to verify which values were being returned.

**Comment by SteveMcGrath** [comment]
I know the APIs in this case can be counter intuitive, however as the UUIDs are just returning in different formats, getting the value transformed from the textual format returned by the agents API and fed into the filter for the assets API like so:

```python
from uuid import UUID

agent_uuid = '7b7807db-a55b-4b38-ba55-d7dcc884aeba'
tenable_uuid = UUID(agent_uuid).hex
```

It's also worth noting that the asset export has all of the asset metadata laid out for you already, and that you can use the iterable in pyTenable to handle all the backend logic on getting to the data for you.  If you are storing the data, this would be the recommended approach as it is less overall calls, lighter on the backend, and would be considerably faster on your end.
