### ISSUE TITLE
WAS API support

### ISSUE THREAD

**Issue by barbich** [tenable/pyTenable#240]
Hi
this might be a bug or a misunderstanding on the use of the package. Download of WAS results via the package was working until 1st of October and is not anymore.

**Is your feature request related to a problem? Please describe.**
Since the migration from old interface to new interface in Teanble.IO the WebApp scan results are not reported any more in the "scans" API (https://cloud.tenable.com/scans) but in the WAS APIv2 (https://developer.tenable.com/reference#was-v2-scans-list)

**Describe the solution you'd like**
Native support for the WAS APIv2 should be provided.

**Describe alternatives you've considered**
- direct call to python requests is the temporary alternative that can be considered
- file a bug report with Tenable

**Comment by SteveMcGrath** [comment]
I completely agree with you, and it's slated as part of the larger changes to the library that are to be coming as part of the larger refactor going on.

The current library is very Tenable.io-VM focused at the moment, as the APIs for CS and WAS didnt exist when it was written.  To better support those apps and future apps, the object structure (and dot-notation) will change.  For example:

```
tio.scans.create()
```

Would become

```
tio.vm.scans.create()
```

This would also mean things like was scans would be:

```
tio.was.scans.list()
```

Some of the other changes to bring the code much closer to 100% tested involves some major refactoring, so all of this is tied together.  The hope is to have a lot of these changes in place by early 2021.  In the mean time, you can take advantage of the [raw methods](https://pytenable.readthedocs.io/en/stable/io.html#raw-http-calls) to make these calls to the underlying library, yet still take advantage of things like the auth header, retry logic, etc.

**Comment by barbich** [comment]
Thanks for feedback.
Indeed I reverted to the raw calls ... sadely.
I might have missed a communication on Tenable about removing the capabilities otherwise I'd consider it as a regression on the API itself and will file a bug report. 

Will consider the request closed.
