### ISSUE TITLE
Unable to call workbench/export for assets

### ISSUE THREAD

**Issue by tonyyng** [tenable/pyTenable#243]
I'm trying to reproduce the Web UI's asset export functionality in a python script.

In the Asset View > Assets, clicking on the "[-> Export  Last 30 Days" button shows the following underlying communcations:
POST http://cloud.tenable.com/workbenches/export

Here is a subset of the Request Payload from the Web UI interaction.
```
{"format":"csv","type":"assets","chapter":"vuln_by_asset","date_range":30,"filters":{"and":[]},"columns":["agent_name","id", snip
```

With the pytenable API, I'm getting back vulnerabilities instead of assets:
```
    results = list()
    export = csv.DictReader(
                 TextIOWrapper(
                     io.workbenches.export(format='csv'
                                          ,type='assets'
                                          ,chapters=['vuln_by_asset']
                                          ,age=30
                                          ,date_range=30))
                          ,dialect='excel')
    for v in export:
        results.append(v)  # each of these is a vulnerability, not an asset
DEBUG:estenable.esTenableClient:path=workbenches/export, query={'report': 'vulnerabilities', 'chapter': 'vuln_by_asset', 'format': 'csv'}, body={}
```
Can you tell me how to replicate the Web UI behaviour?

Thanks

**Comment by tonyyng** [comment]
I ended up copying some of the logic from the class WorkbenchesAPI into my script.  It seems messy, but it is doing what I want now:

```
def export(io, params):
    fobj = BytesIO()

    # I had to change this to "post" from "get"
    fid = io.workbenches._api.post('workbenches/export', json=params).json()['file']

    # Next we will wait for the state of the export request to become
    # ready.  We will query the API every half a second until we get the
    # response we're looking for.
    io.workbenches._wait_for_download(
        'workbenches/export/{}/status'.format(fid),
        'workbenches', 'export', fid)

    # Now that the status has reported back as "ready", we can actually
    # download the file.
    resp = io.workbenches._api.get('workbenches/export/{}/download'.format(
        fid), stream=True)

    # Lets stream the file into the file-like object...
    for chunk in resp.iter_content(chunk_size=1024):
        if chunk:
            fobj.write(chunk)
    fobj.seek(0)
    resp.close()
    return fobj

def exportAssets(io):
    params = dict()
    params['type'] = 'assets'
    params['chapter'] = 'vuln_by_asset'
    params['format'] = 'csv'
    params['date_range'] = 30
    return export(io, params)

def getAssets(io, client):
    results = list()
    export = csv.DictReader(TextIOWrapper(exportAssets(io)),dialect='excel')
    for v in export:
        results.append(v)
    return results
```
I'd appreciate your advice as to whether there is an easier solution.

Thanks

**Comment by SteveMcGrath** [comment]
Why arent you using the asset export api?

**Comment by tonyyng** [comment]
My task was given to me based on replicating the steps that the requestor took to perform his task manually.

That started with using the Web UI to export assets for the last 30 days.  Monitoring the underlying communications, I determined that the Web UI was using workbenches/export.  

I wanted to be certain I was getting the same set of data.  If you are telling me that I can get the same results using the asset export api, I can take a look at that.  How do I pass the date_range parameter that is used by the Web UI?  I don't see that in the asset export docs.

**Comment by SteveMcGrath** [comment]
use updated_at.

**Comment by tonyyng** [comment]
Okay.  Thanks
