### ISSUE TITLE
tags.create error when using category name not uuid

### ISSUE THREAD

**Issue by Mooey28** [tenable/pyTenable#246]
**Describe the bug**
When calling tio.tags.create(), it is successfully creating a new tag value against the given category, but it is still displaying an error in the console: 

_category has value of Account. Does not match pattern ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$_

**To Reproduce**
Create a CSV, containing some reference information, a name (what you want the tag value to be), and an IP address (1:many name:IP)
`csvAccountsListDf = pandas.read_csv('allaccounts.csv', names=['Account ID', 'Account Name', 'IP Address'], header=None)`
`allAccountsDf = csvAccountsListDf['Account Name'].drop_duplicates()`
`accountNames = set(allAccountsDf.values)`

some other code here where, amongst other tasks, I'm finding the current tag values' names for this category in Tenable via the API (parameter tagValues, below) and comparing these names against the list of names in the spreadsheet to see which ones need creating.

`newAccountNames = accountNames.difference(tagValues)`
`if len(newAccountNames) > 0:`
`    for newAccountName in newAccountNames:`
`        tio.tags.create(category='Account', value=newAccountName)`

**Expected behavior**
tio.tags.create(category='Account', value=newAccountName)` should create a new tag value and assign it to the stated category (in this case the category called "Account"). It does this - but throws the error stated above about regex to the console.

**System Information (please complete the following information):**
 - Python Version 3.8
 - pyTenable Version 1.2.3

**Additional context**
I have also posted onto the Tenable Community Forums, before remembering about the GitHub. 
I found an older post from 10 months ago on the forums referencing the regex error, and that there was a mistake in tags.py. I have checked my local package's copy of tags.py and it has:

`        try:`
`            payload['category_uuid'] = self._check('category', category, 'uuid')`
`        except UnexpectedValueError:`
`            payload['category_name'] = self._check('category', category, str)`

**Comment by SteveMcGrath** [comment]
The error is expected based on the current code, and the error can be safely ignored.  Until the type checking logic has been refactored, this will continue to be the case
