### ISSUE TITLE
Scan Stop action does not allow specifying discard, import, or import with rollover

### ISSUE THREAD

**Issue by 0secure** [tenable/pyTenable#247]
Please add an argument to the Tenable.sc scan_instance.stop function to allow the user to specify the action to take with the scan results.  While this option does not appear to be documented in the Tenable.sc API documents, inspection of the Tenable.sc web requests indicates that adding POST content of the form '{type: "import"}' would achieve the desired results.

**Comment by SteveMcGrath** [comment]
I'll have to confer with the SC development teams first.  As a general rule, this library tries to stick to the publicly documented endpoints and attributes.

**Comment by levwais** [comment]
TODO: check with SC Eng team.

**Comment by levwais** [comment]
this is a feature request that will need to be added to Tenable.SC first before it can be done / added in PyTenable.
I've contacted the SC Eng team, I'll update here once I hear back.
