### ISSUE TITLE
Missing pagination support in Tenable.io agent_groups.details

### ISSUE THREAD

**Issue by elliotkendall** [tenable/pyTenable#249]
When you use pyTenable to fetch details of an agent group, you are limited to a list of only the first 50 member agents. This is because per the API docs, the "agents" field is paginated - you must specify offset, limit, sort, filter, etc. to get everything. However, there is no way in pyTenable to supply any of those arguments to agent_groups.details(). The only two documented arguments are group_id and scanner_id, and the source code confirms that nothing else can be passed.

https://developer.tenable.com/reference#agent-groups-details
https://pytenable.readthedocs.io/en/latest/io.html#tenable.io.agent_groups.AgentGroupsAPI.details
https://pytenable.readthedocs.io/en/latest/_modules/tenable/io/agent_groups.html#AgentGroupsAPI.details

I would suggest that a possible solution would be for functions like this one to accept arbitrary named parameters. In the case where they don't know how to deal with the natively, they would pass them through unmodified to the backend API. That would be a major change, however. Alternately, we could simply add pagination support to this specific function, following the example of agents.list(), say.

https://pytenable.readthedocs.io/en/latest/io.html#tenable.io.agents.AgentsAPI.list

**Comment by SteveMcGrath** [comment]
I think the right approach here would be to rework the endpoint to return an iterator instead and convert the results of the unenveloped data into attributes within the iterator.  It would allow for wrapping in a for loop like you can do with most other paginated responses as well as making that whole experience transparent.

**Comment by elliotkendall** [comment]
Thanks. Is there any existing code that does something similar in the codebase? I feel like we should try to be consistent.

**Comment by SteveMcGrath** [comment]
this endpoint is one of the only ones with paginated content enveloped within non-paginated metadata to my understanding.  However in general when pagination exists, the response is an iterator.

**Comment by elliotkendall** [comment]
Okay, I think I see what would need to happen. Are we concerned about breaking API compatibility by returning an iterator rather than a dictionary? Thanks.

**Comment by SteveMcGrath** [comment]
I think I may be able to do it in a backwards-compatible way.

**Comment by elliotkendall** [comment]
Oh, are you going to write a patch? I was planning to do it, but I'm sure you'd do a better job.

**Comment by SteveMcGrath** [comment]
how about this, as there is existing code already utilizing this, why not submit a patch for the added fields.  The v2 codebase I keep trying to work on will be entirely breaking, but will be utilizing Box pretty heavily for the response objects, which would make this seem a lot cleaner in the long run.

I would say file the PR, but we wont close this out.

**Comment by elliotkendall** [comment]
Okay, here's a PR. The code is heavily stolen from agents.list and audit_log.events, so I think it should be fairly straightforward.
