### ISSUE TITLE
Gathering vulnerability by severity count using export api

### ISSUE THREAD

**Issue by Kumrix** [tenable/pyTenable#250]
I am using a tenable_io export api i.e (tio.exports.vulns()) to get vulnerability report and from the return response of the API we process the data and keeping the asset_id as reference we calculate the count of critical ,high, medium, low severity count .

The problem is in tenable dashboard UI we see  15 medium vulnerabilities against the asset_id but from the API we get just 3 medium vulnerabilities for the same asset_id . In both the cases the default is 30days . 

There is some issue with the export api where the UI count and the API count dosen't match .

**Comment by SteveMcGrath** [comment]
you may want to ensure that you pass a last_found filter that matches the timeframe.

```python
import arrow
from tenable.io import TenableIO

tio = TenableIO()
vulns = tio.exports.vulns(last_found=arrow.get().shift(days=-30).floor('day').timestamp)
```
