### ISSUE TITLE
Releases are missing

### ISSUE THREAD

**Issue by fabaff** [tenable/pyTenable#260]
**Describe the bug**
The tarball for the latest release are not available. The Fedora RPM package and maybe other distribution packages are using the source published on GitHub.

Could you please publish it in addition to the PyPI release? Thanks
**To Reproduce**
1. Go to https://github.com/tenable/pyTenable/releases

**Expected behavior**
Be able to build packages without changing the location of the source. Thanks.

**Screenshots**
na
**System Information (please complete the following information):**
na

**Additional context**
na

**Comment by fabaff** [comment]
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1903811

**Comment by SteveMcGrath** [comment]
forgot to push updated tags when i built the new machine ;). Should work now.
