### ISSUE TITLE
Disable certificate verification for TenableIO

### ISSUE THREAD

**Issue by marboi** [tenable/pyTenable#265]
I'm trying to extract vulnerabilities from T.SC and T.IO. T.SC is all right but my Python script does not work with T.IO:
_Requests Error: HTTPSConnectionPool(host='cloud.tenable.com', port=443): Max retries exceeded with url: /assets (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))_

Obviously, the Python code does not like our internal CA which is used by the web proxy.
I googled this topic and found many recipes to disable the verification or install my company certificates for Python. None of it worked.

I would  prefer to disable this verification as checking our proxy certificate is utterly useless and I don't want the future users of this script to struggle with their own Python installation.

My code looks like:
```
from tenable.io import TenableIO
# Read config and get access keys
tio = TenableIO(timeout=IOtimeout, access_key=IOaccessKey, secret_key=IOsecretKey)
for asset in tio.assets.list():
	pprint(asset)
```

**Comment by andrewspearson** [comment]
Obligatory warning...this code could compromise your network. Don't use it.
https://gist.github.com/andrewspearson/f8551d52c730325a736117b649e47bbd

**Comment by SteveMcGrath** [comment]
Another option is to instantiate a Requests Session yourself and then inject it into the library.  This way anything you need to do to the session  you can do and then inform pyTenable to use this session instead of creating it's own.

```python
from requests import Session
from tenable.io import TenableIO

session = Session()
session.verify = False
tio = TenableIO(access_key='', secret_key='', session=session)
```

https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.TenableIO

**Comment by marboi** [comment]
Le dim. 21 févr. 2021 à 02:28, Andrew Pearson
<notifications@github.com> a écrit :

> https://gist.github.com/andrewspearson/f8551d52c730325a736117b649e47bbd

Thanks! This works!

> Obligatory warning...this code could compromise your network. Don't use it.

Actually no. Verifying the enterprise proxy certificate does not
really improve our overall security.
The proxy is in charge of verifying the remote web site certificate --
well, I hope it does, and if it does not, I cannot do anything about
it.

Kind regards,

M.A.

**Comment by SteveMcGrath** [comment]
ssl_verify parameter has been added in 1.2.8

https://github.com/tenable/pyTenable/commit/68ec325eed589cb2e7b9a40cbf5c054ac8c7de53
