### ISSUE TITLE
Plugin list can't find "severity" field

### ISSUE THREAD

**Issue by wizardous23** [tenable/pyTenable#267]
Hello,

I am making a request to the plugin endpoint (https://docs.tenable.com/tenablesc/api/Plugin.htm) to list all plugins with a specific "severity" level but there seems to be no "severity" field? Is this correct? If so, is there another way about finding the "Severity" field?

**Comment by SteveMcGrath** [comment]
use the CVSS score.

https://community.tenable.com/s/article/CVSS-Severity-Changes-for-plugins-in-Tenable-products

**Comment by wizardous23** [comment]
> use the CVSS score.
> 
> https://community.tenable.com/s/article/CVSS-Severity-Changes-for-plugins-in-Tenable-products

Thanks for the response. I notice a lot of these CVSSV3BaseScore's are "None" but when viewing them on the tenable website are different. For example this plugin (https://www.tenable.com/plugins/nessus/34797) shows up as None for its CVSSV3BaseScore but when looking at the site it says the severity is "High." Why is this the case?
