### ISSUE TITLE
[Tenable.sc] Cannot create scan with both policy_id and plugin_id

### ISSUE THREAD

**Issue by bdesbiolles** [tenable/pyTenable#268]
**Description**
When I try to create a scan for tenable sc, with both policy_id and plugin_id, I get: a _tenable.errors.UnexpectedValueError: specify either a plugin_id or a policy_id for a scan, not both._
If I remove the plugin_id the scan create the the API response is 403  with a message "A scan containing a context Policy must include a pluginID" 

**To Reproduce**
create a scan for tenable sc with both plugin_id and policy_id, get the error message
create a message with a policy_id without plugin and get the 403.

**Expected behavior**
Be able to launch a scan for a plugin_id

**System Information**
pytenable version 1.2.6
Tenable.sc 5.17.0

**Comment by aelharda** [comment]
Can you share your a redacted version of your code?

**Comment by levwais** [comment]
@bdesbiolles - is this still an existing issue or can this be closed?

**Comment by SteveMcGrath** [comment]
closing for lack of response
