### ISSUE TITLE
Documentation error - `enabled` in io.exclusions

### ISSUE THREAD

**Issue by nzig** [tenable/pyTenable#273]
The docs for pyTenable state that `enabled` means "Is the exclusion enabled?" ([link](https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.exclusions.ExclusionsAPI.create)), while the API docs say that it means "If `true`, the exclusion schedule is active." ([link](https://developer.tenable.com/reference#exclusions-create)).

From my experimentation, the API docs are correct.

**Comment by nzig** [comment]
I don't think this was addressed correctly. The key difference is that enabled controls enabling the exclusion *schedule*, not the exclusion itself. Passing `enabled=False` makes an "Always Active" exclusion, not a disabled one.

Thanks!

**Comment by SteveMcGrath** [comment]
thats true, more of a doc issue at this point.

**Comment by nzig** [comment]
Yes, only a doc issue.

**Comment by nzig** [comment]
@SteveMcGrath maybe re-open the issue to address the docs problem? The docs for this are still wrong.

**Comment by levwais** [comment]
@mvalliammal  - please fix documentation in PyTenable as suggested

**Comment by mvalliammal** [comment]
@levwais - fix done in https://github.com/tenable/pyTenable/pull/352
