### ISSUE TITLE
UnboundLocalError in io.target_groups.edit

### ISSUE THREAD

**Issue by nzig** [tenable/pyTenable#274]
Making a call like 
```py
tio.target_groups.edit(999, members=[])
```
Will raise `UnboundLocalError("local variable 'craw' referenced before assignment")` if there is no target group with id 999.

The method should handle this case an raise an appropriate exception.

Version: 1.2.7

**Comment by SteveMcGrath** [comment]
Should be addressed in 1.2.9 release.
