### ISSUE TITLE
[Tenable.io] Can't create a system target group

### ISSUE THREAD

**Issue by nzig** [tenable/pyTenable#275]
**Describe the bug**
I'm trying to create a system target group, but it doesn't seem to be possible.

**To Reproduce**
```py
tio.target_groups.create("systemGroup", ["0.0.0.0"], type="system")
```
The created target group will be a user target group.

**Expected behavior**
The created target group would be a _system_ target group.

**System Information (please complete the following information):**
Version: 1.2.7

**Additional context**
It seems pyTenable passes a `type` parameter in the POST request, but such a parameter does not exist in [the API](https://developer.tenable.com/reference#target-groups-create).

Is there a way to do this through the API?

**Comment by SteveMcGrath** [comment]
System target groups were deprecated for access groups some time ago.  the developer docs state that, however this method was never revisited to address that.
