### ISSUE TITLE
How to sort analysis.vulns using sortField by date?

### ISSUE THREAD

**Issue by wizardous23** [tenable/pyTenable#277]
I am using the analysis endpoint (specifically the vulns method) to get a list of plugins. I want this list to be sorted by the date but am not sure what to pass in the sortField parameter to sort by date.

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/sc.html#tenable.sc.analysis.AnalysisAPI.vulns

Use `sort_field` and `sort_direction`
