### ISSUE TITLE
Roles create issue

### ISSUE THREAD

**Issue by PavtheDog** [tenable/pyTenable#279]
**Describe the bug**
In the RoleAPI, can_scan (bool, optional).  Does not work.  I found that SC returns full, policy, or none.

I made a change to the code in my lib for now;
if key in kw:
  if key != 'can_scan':
      kw[mapping[key]] = str(self._check(key, kw[key], bool)).lower()
      del(kw[key])
  else:
     kw[mapping[key]] = str(self._check(key, kw[key], str)).lower()
      del(kw[key])

I also found permAgentsSync is missing.

**Comment by SteveMcGrath** [comment]
Should be addressed in the 1.2.9 release
