### ISSUE TITLE
Documentation missing for Recast Risk

### ISSUE THREAD

**Issue by parksddd** [tenable/pyTenable#280]
**Describe the bug**
The recast risk documentation only references read access to the Recast Risk endpoints.

**To Reproduce**
View the docs

**Expected behavior**
Recast Risk has been implemented for creation/deletion/etc. It would be nice if the docs reflected this.

**Comment by levwais** [comment]
@parksddd  - can you please add more information? which endpoints are you referring to? which documentation? thank you
