### ISSUE TITLE
Allow port to be optional

### ISSUE THREAD

**Issue by rirze** [tenable/pyTenable#286]
**Is your feature request related to a problem? Please describe.**
We have a custom endpoint where a URL points to the correct Tenable port. The path looks something like this: `https://sub.domain.com/tenable`. This automatically forwards the traffic to the Tenable's 443 port through the proxy.

Currently there's no way (that I can determine) to create a `TenableSC` client to connect to this endpoint. The default port is forced and I cannot find an API way to disable specifying ports on the endpoint.   

Using the example above, the endpoint generated looks like this: `https://sub.domain.com/tenable:443`, which will obviously fail.

**Describe the solution you'd like**
Enable a way to forcibly disable attaching port # to the endpoint, i.e.
```python3
client = TenableSC('mycustom.endpoint.com', port=False)
```

**Describe alternatives you've considered**
I've considered monkey patching the `client._url` to point the the right URL, but I can't create the client without it checking for the validity of the endpoint.
 
I know changing the proxy forward is an option, yet this lack of flexibility in the API seems like an unnecessary restriction on this library. If this is intentional, please let me know. 

**Additional context**
I've made a local patch to the library and altered to enable the behavior above. However, the endpoint doesn't propagate properly through the logging/debugging messages. I can submit a PR for the work I've done so far, but it's pretty simple, and there may be cascading changes that I, an outside developer, may not anticipate.

**Comment by SteveMcGrath** [comment]
instead of monkeypatching, you might wan to look into the `base_path` argument instead.  You can override it with `tenable/rest` and it should construct the URL as you'd expect.

**Comment by rirze** [comment]
Ah, that works. Thanks
