### ISSUE TITLE
tio.tags.details and tio.tags.list Asset counts

### ISSUE THREAD

**Issue by brianp9906** [tenable/pyTenable#292]
**Describe the bug**
Both the above tags requests do not provide the assigned asset counts.  The assigned asset counts are useful to delete tag values with 0 assets assigned.  The details API also does return assigned asset counts but they're randomly 0 for certain ones which is different than the tag/values API call in Tenable documentation.

**To Reproduce**
Review tag Value details for the above 2 PyTenable methods and compare to Tenable API: https://cloud.tenable.com/tags/values?offset=0&limit=0&optionalfields=assignment_count&sort=category_name:asc,value:asc

**Expected behavior**
asset counts should be optionally present and accurate

**System Information (please complete the following information):**
 - OS: MacOS BigSur
 - Architecture 64bit
 - Version: Python 3.8
 - Memory: 32GB (OS)

**Additional context**
Tenable Case 01192736

**Comment by levwais** [comment]
hi @brianp9906 , just to make sure i understand you request - are you saying that the API returns the counts wanted but PyTenable doesn't add it to the returned object?

**Comment by SteveMcGrath** [comment]
This isn't an issue with the library, but with the API.  I'd suggest contacting Tenable support in regards to this issue.
