### ISSUE TITLE
sc.scan_instances.list start_time

### ISSUE THREAD

**Issue by ve2tmq** [tenable/pyTenable#297]
**Describe the bug**
I'm unable to pass start_time on scan_instances.list

**To Reproduce**
    list_scan = sc.scan_instances.list(start_time=7)['usable']
    print(list_scan)

**Expected behavior**
Trying to get last 7 days (now-7days), but I've got all scans.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Linux
 - Architecture 64bit
 - Version RHLE 8
 - Memory [e.g. 4G]

**Additional context**

**Comment by SteveMcGrath** [comment]
Note that the parameter expects epoch time.  '7' would mean "7 seconds after epoch".  epoch is `1970-1-1 00:00:00 UTC`.  You may want to consider the following:

```python
import arrow

age = arrow.now().shift(days=-7).timestamp()

scans = sc.scan_instances.list(start_time=age)['usable']
```

**Comment by ve2tmq** [comment]
> Note that the parameter expects epoch time. '7' would mean "7 seconds after epoch". epoch is `1970-1-1 00:00:00 UTC`. You may want to consider the following:
> 
> ```python
> import arrow
> 
> age = arrow.now().shift(days=-7).timestamp()
> 
> scans = sc.scan_instances.list(start_time=age)['usable']
> ```

Thanks for replying, start_time is an int (days), arrow.timestamp is a float.  I tried your code, but doesn't works :(.

**Comment by levwais** [comment]
@ve2tmq - is the suggestion by @SteveMcGrath works for you? can I close this issue?
thanks.

**Comment by ve2tmq** [comment]
Ho, oh yes, you can close it.  I'll try this solution.

--... ...--
Mathieu Therrien, ing, M's, VE2TMQ
._._.
