### ISSUE TITLE
Tenable IO Exception Handling Question

### ISSUE THREAD

**Issue by brianp9906** [tenable/pyTenable#298]
**Describe the bug**
I'm trying to handle the case where if I create a tag value for a tag category that already exists (duplicate).

**To Reproduce**
```
from tenable.io import TenableIO
global tio_conn
tio_conn = TenableIO(AKEY,SKEY)
#create tag and value
tio_conn.tags.create(category='Test', value='Test1')
#create it again and catch the exception
try:
  tio_conn.tags.create(category='Test', value='Test1')
except tenable.errors.InvalidInputError as tio_error:
  print(type(tio_error))
  print(tio_error)
```

```
# Doing the above results in: 
tenable.errors.InvalidInputError: ###################:400 {"errors":[{"property":"value","rule":"duplicate","message":"Duplicate tag value 'Test1' cannot be be created."}],"error":"Duplicate tag value 'Test1' cannot be be created."} 

but then Python sends up the error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'tenable' is not defined
```

**Expected behavior**
I should be able to catch the duplicate tag error and just acknowledge its a duplicate and move on.

**System Information (please complete the following information):**
 - OS: MacOS BigSur Python 3.8
 - Architecture 64bit
 - pyTenable==1.2.8

**Additional context**
Maybe I'm making a newbie mistake, but any guidance here would be great.  Thanks!

**Comment by dheerajrp** [comment]
Addressed the issue -
I have added the exceptions to take care of creating tags when tried to create the tags with the existing tag category, 
as well as the tag value. Now, if it encounters with the tag value or the tag category that already exists, it will except 
and move on. I have logged the exceptions. Excepting Exceptions instead of the InvalidInputError would help not to get the 
name error exception. I hope I have solved your issue. Thanks

**Comment by mvalliammal** [comment]
@brianp9906,

We had fixed the problem in PR #354, 
We gave a new release 1.3.3

Can you verify?

thanks

**Comment by brianp9906** [comment]
I just came across the same error using pyTenable 1.3.3 version.

`>>> import tenable.errors
>>> try: 
...   my_script.tio_conn.tags.create(category='Asset_Type',value='Production')
... except tenable.errors.InvalidInputError as inputerror:
...   print('handled')
... except Exception as ex:
...   print('other: ' + str(ex))
... 
2021-09-22 09:20:03 ERROR    POST https://cloud.tenable.com/tags/values >> 131b7df3b59ffecf7c3bbc7815b6c10e:400 {"errors":[{"property":"value","rule":"duplicate","message":"Duplicate tag value 'Production' cannot be be created."}],"error":"Duplicate tag value 'Production' cannot be be created."}
handled
`

You'll notice I catch the exception and it prints "handled" but it still logs out the ERROR message from pyTenable which gets logged out.

**Comment by SteveMcGrath** [comment]
have you considered importing the error and catching it that way?

```python
from tenable.errors import InvalidInputError
from tenable.io import TenableIO

tio = TenableIO(AKEY,SKEY)

#create tag and value
tio.tags.create(category='Test', value='Test1')

#create it again and catch the exception
try:
    tio.tags.create(category='Test', value='Test1')
except InvalidInputError as tio_error:
    print(type(tio_error))
    print(tio_error)
```
