### ISSUE TITLE
scans.history ignores limit when offset is zero

### ISSUE THREAD

**Issue by nikothome** [tenable/pyTenable#300]
**Describe the bug**
Goal is to pull the metadata of the two most recent scans. Therefore I call tio.scans.history(<id>, limit=2, offset=0). However, the method returns an iterator with the full history of all records.

**To Reproduce**
1. pull the ID of a scan with more than two history entries
2. Call tio.scans.history(<id>, limit=2, offset=0).
3. pprint the iterator and see more than two historic scan records

**Expected behavior**
Only two (the latest two) scans are returned

**sample code**
`#!/usr/bin/python3

import pprint
from datetime import datetime
from tenable.io import TenableIO

tio_prod = TenableIO("aaaa", "bbb")

pp = pprint.PrettyPrinter()

filter = "my_test_scan"

def __init__():
    try:
        for scan in tio_prod.scans.list():
            if (scan["name"].startswith(filter)):
                print(("scan: {}").format(scan["name"]))
                for historic_scan in tio_prod.scans.history(int(scan["id"]), limit=2, offset=int(0)):
                    pp.pprint(historic_scan)
    except:
        print("Error")
        exit()

__init__()`

**Comment by tushar-balwani** [comment]
you can use pages param to limit result
`for historic_scan in tio.scans.history(int(scan["id"]), limit=2, offset=int(0), pages=1)`
this will return latest 2 records.

**Comment by nikothome** [comment]
true that - I worked around it with zip(), but I still think its a bit counterintuitive to send back more records than specified in the limit param.

**Comment by SteveMcGrath** [comment]
The issue you're running into is that you actually are being handed back an iterator, and not the raw results.  The iterator is handling pagination for you as the results are being returned, so @tushar-balwani's response is correct that if you only want 2  items back, then you should set the limit and then set the number of pages of data you want back as well.  The page counter will force the iterator to terminate when it reaches that number.

**Comment by levwais** [comment]
@nikothome - is the suggestion by @SteveMcGrath and @tushar-balwani  work for you? may I close this issue?
