### ISSUE TITLE
tags.create() function throws an error after successful tag creation

### ISSUE THREAD

**Issue by fgardner** [tenable/pyTenable#304]
**Describe the bug**
When calling tio.tags.create(), output throws an error:
`category has value of environment.  Does not match pattern ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$`

category passed is a string ('environment') and value passed is a string ('testing')

The tag is still created successfully, but throws this error anyways.

**To Reproduce**
1. Initialize TenableIO client with pytenable
2. Call  tio.tags.create(category, value)
3. See error

**Expected behavior**
No error should be thrown. 

**System Information (please complete the following information):**
 - OS: MacOS
 - Architecture 64bit

**Additional context**

**Comment by tushar-balwani** [comment]
The error is expected based on the current code, and the error can be safely ignored. Until the type checking logic has been refactored, this will continue to be the case

**Comment by levwais** [comment]
@tushar-balwani , @mvalliammal  - based on the documentation - calling tags.create("enviroment", "testing") should be allowed. can you please check why this is not working?
thanks.

**Comment by mvalliammal** [comment]
@fgardner,
We had completed this issue and it is fixed in PR #357

It is currently available in the new release 1.3.3
Please verify

thanks
