### ISSUE TITLE
Update to support for WAS API V2

### ISSUE THREAD

**Issue by d0n601** [tenable/pyTenable#310]
Interacting with WAS scans is now done completely through the `/was/v2/` endpoints. The `/scans` endpoint can no longer be used for WAS related things.

Are there any plans for this wrapper to support WAS scan interactions?

**Comment by SteveMcGrath** [comment]
yes, we plan on supporting WASv2

**Comment by mukilarasan-ravi** [comment]
@SteveMcGrath , is this feature released? If not, is there any workaround to get it down using current version?

**Comment by SteveMcGrath** [comment]
WAS bulk export APIs have been released.  Support has been mainlined with an anticipated release before December
