### ISSUE TITLE
Retry/backoff logic doesn't include HTTP 500 in retry_codes or allow user to specify retry_codes

### ISSUE THREAD

**Issue by mzpqnxow** [tenable/pyTenable#374]
**Describe the bug**

Tenable uses its own HTTP retry code, adapted from the urllib3 feature with some customization. The way they work is by exposing (among other things) a list of HTTP status codes that should be retried. Aside from preventing obvious successful responses (e.g. 200, 301, 302, ...) from being retried, it also prevents hammering a server when there is something like invalid credentials, resulting in a 401. The tenable_io default is set to 429, 501, 502, 503 and 504

I have an application that utilizes tenable_io daily to pull reports. It has run for ~6 months without any issues but I noticed yesterday it had failed. I went to look why and I found that a call to `tio.scans.results()` had resulted in a 500 error, and that resulted in a fatal exception:

```
tenable.errors.ServerError: xxxxxxxxxxxxxxxxxxxxxxxxxxxx:500 {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred. Please wait a moment and try your request again."}
```

Because this is a temporary failure that is often recoverable via a delay and retry, will you please consider adding HTTP 500 to the list of retry status codes? Right now I need to write a loop with exception handlers and it's very clunky. Because the infrastructure for retries is already in tenable_io, it seems to make sense to allow it to handle HTTP 500 as if it was any of the other codes in the list

The list of status codes is here:

https://github.com/tenable/pyTenable/blob/d2b673a2dee89763687a159ac7231fb97166eccd/tenable/base/v1.py#L476
 
I would like `retry_codes` to be `[429, 500, 501, 502, 503, 504]`. It would have saved my automated reporting in this case, and it will allow me to remove clunky try/except clauses and a for loop that I needed to add to handle this in the future

Because the error response above from the Tenable service even explicitly states that this is a temporary condition ("Please wait a moment and try your request again.") it seems that this shouldn't be much of a debate?
 
 As an alternative to changing the hard-coded list, would you please consider exposing the `retry_codes` as a kwargs to the `TenableIO` constructor, so that I can manually set it? Both the `backoff` and `retries` are already exposed- these are 2/3 of the parameters required for the retry adapter
 
 Thanks

**To Reproduce**

This can not be reproduced reliably. The server was probably undergoing some unusual load or was in some other odd condition temporarily

**Expected behavior**

I would have preferred if this was retried internally within tenable_io, the same as a 501 or 502 would be

**Comment by SteveMcGrath** [comment]
Sadly, 500s also occur in some error conditions on the server end, and when it was originally tested to include 500s as a retry, it created issues.  Ideally, the requests that respond with 500s should overload the retry logic to address this, however these edge cases were discovered later on in the development.

I agree with you, 500s should be retried, however some testing should be performed with the library to ensure that those edge cases (if they still exist) are accounted for.

**Comment by mzpqnxow** [comment]
> Sadly, 500s also occur in some error conditions on the server end, and when it was originally tested to include 500s as a retry, it created issues. Ideally, the requests that respond with 500s should overload the retry logic to address this, however these edge cases were discovered later on in the development.
> 
> I agree with you, 500s should be retried, however some testing should be performed with the library to ensure that those edge cases (if they still exist) are accounted for.

Thank you for the explanation, I thought that might be the case

As opposed to simply adding 500 to the list and hoping for the best (which I agree is not the right thing to do) what do you think about starting by exposing the `retry_codes` as a kwarg? It could be undocumented and/or it could have a `warnings.warn()` wrapped around it, to notify users that it's in an experimental state

**Comment by SteveMcGrath** [comment]
Im not opposed to this, however it would have to be as part of a larger refactor, as currently most methods don't expose things in a way to support this universally.

**Comment by mzpqnxow** [comment]
I see, thanks again for looking into it and keeping it open

May I ask if there are any plans for (even partial) refactors or non-trivial additions at the moment, or is the current focus primarily maintenance and QA?

**Comment by SteveMcGrath** [comment]
currently discussing forward direction.  hold tight ;)

**Comment by SteveMcGrath** [comment]
so with the migration to using RESTfly in the backend, all of the APIErrors now inherit the ability to overload the the retry logic at the exception class level:

https://github.com/SteveMcGrath/restfly/blob/master/restfly/errors.py#L177-L181

So to do this for a given piece of code, you should be able to do the following:

```python
from restfly.errors import ServerError

# Set the retryable flag to True for 500 errors.
ServerError.set_retryable(True)

# my code with needed retry logic here

# Set the retryable flag to False for 500 errors.
ServerError.set_retryable(False)
```

Further if there are issues with this, may I point you to open an issue in the restfully lib and we can route it down there.
