### ISSUE TITLE
A method to delete select audit files from a compliance scan

### ISSUE THREAD

**Issue by john-lowry** [tenable/pyTenable#404]
**Is your feature request related to a problem? Please describe.**
Being able to either selectively remove an audit file from a compliance scan or just removing all existing audit files in order to add the ones I want in a later action would be very handy.

**Describe the solution you'd like**
in TenableIO.scans.configure(compliance=<a way to remove audit files.>

**Describe alternatives you've considered**

**Additional context**
I am writing a utility to manage all of our compliance scans from a CI/CD workflow via python. So after a change is made to the audit file, it is checked into a git projects, run through some tests, and then the CI/CD server will run the script to upload the new audit file(s) and need to also remove the old ones.

**Comment by tushar-balwani** [comment]
@john-lowry 

you can remove selected or all audit file references from scan by passing 
```
compliance = {"custom": { "delete" : <list-of-audit-file-ids>}}
```
to get details of existing audit file in scan, you can use 
```
scan = tio.scans.details(scan_id)
```

**note** : while removing all audit files from scan, at least one audit must be added to this policy in the 'Compliance' section
