### ISSUE TITLE
tio.assets.asset_import - documentation doesnt match behavior

### ISSUE THREAD

**Issue by lmbrianp** [tenable/pyTenable#405]
**Describe the bug**
The documentation does not match the behavior. 
https://pytenable.readthedocs.io/en/stable/io.html

"Imports a list of asset definition dictionaries"

"Parameters: 
*assets (list) – The list of asset dictionaries
source (str) – An identifier to be used to upload the assets."

The documentation example says:
```
>>> tio.assets.asset_import('example_source', {
...     'fqdn': ['example.py.test'],
...     'ipv4': ['192.168.254.1'],
...     'netbios_name': 'example',
...     'mac_address': ['00:00:00:00:00:00']
... })
```
This is a 2 parameter import with a string and dictionary (ie not a list of dictionaries). 

The developer.tenable.com documentation says that asset imports can do a bulk import.  Seems like the pyTenable code is whats wrong and needs correcting.
https://developer.tenable.com/reference#assets-import

**To Reproduce**
assets_to_import = list()
assets_to_import.append({'ipv4':['10.0.0.1']})
assets_to_import.append({'ipv4':['10.0.0.2']})
tio.assets.asset_import('example_source', assets_to_import)

Exception=> asset is of type list.  Expected dict.

**Expected behavior**
A list of asset dictionaries should be able to import bulk assets as per documentation.

**System Information (please complete the following information):**
MacOS Big Sur
python 3.8
pyTenable 1.3.3

**Additional context**
Trying to import more than 1 asset at a time (bulk import)

**Comment by tushar-balwani** [comment]
@lmbrianp for bulk import of assets, you can pass multiple assets dictionary separated by comma. 
below is example for your reference
```
asset = tio.assets.asset_import(
    'source_example',
    {'ipv4': ['10.0.0.1']},
    {'ipv4': ['10.0.0.2']},
    {'ipv4': ['10.0.0.3']}
)
```

**Comment by lmbrianp** [comment]
Ok thanks.  Can the documentation be clarified? It says a "list of dictionaries".  I interpreted as a python list of dictionaries.  The provided example should include your example.  Thanks

**Comment by dheerajrp** [comment]
Hi @lmbrianp 
I have updated the documentation in the commit of above PR. 
thanks
