### ISSUE TITLE
how to link pyTenable to Tenable io ?

### ISSUE THREAD

**Issue by Eriola** [tenable/pyTenable#406]
Hello,
I would like to automate the scans and the reports exportation to a specific SharePoint repository. So I'm exploring pyTenable but I don't know where and how to run this Python Code to do so.

Please can you tell me how is it supposed to work without a manual trigger each time ?
Thank y'all

**Comment by SteveMcGrath** [comment]
the TenableIO class can be instantiated either by using the access_key and secret_key arguments at instantiation, or by using the TIO_ACCESS_KEY and TIO_SECRET_KEY environment variables.
