### ISSUE TITLE
Support host.target filter in exports.vulns

### ISSUE THREAD

**Issue by yoniaxonius** [tenable/pyTenable#407]
**Is your feature request related to a problem? Please describe.**
Hi, as seen on the following docs:
https://developer.tenable.com/docs/retrieve-vulnerability-data-from-tenableio

I see there is a possibility to filter the export to run on specific assets using host.target filter. currently, this is not supported via the python API.

<img width="848" alt="Screen Shot 2021-08-04 at 18 33 49" src="https://user-images.githubusercontent.com/74133577/128264283-980d7f24-e734-4be6-9156-71f6e199ec1c.png">

**Describe the solution you'd like**
Run export on specific assets

**Comment by SteveMcGrath** [comment]
I have confirmed that this appears to be a doc issue, as that was transposed from the workbench APIs.  the only ways to filter assets in the vulnerabilities export apis is via tags and networks.
