### ISSUE TITLE
accept-risk 'expires' parameter expects timestamp, not days

### ISSUE THREAD

**Issue by javimox** [tenable/pyTenable#415]
**Describe the bug**
The documentation on https://pytenable.readthedocs.io/en/stable/sc.html#accept-risks has imho a mistake. The following is given as an example under `accept_risks` section:

```
Create a rule to accept 97737 on 2 IPs for 90 days.
>>> rule = sc.accept_risks.create(97737, [1],
...     ips=['192.168.0.101', '192.168.0.102'], expires=90)
```
For what I could test, `expires` expects a timestamp. Passing the value '90' like in the example above just sets the Tenable rule expirations date to Unix epoch (1 January 1970).

**To Reproduce**
Run the example.

**Expected behavior**
The documentation about accept_risks - expires parameter should specify timestamp instead of days.

__Unless__ there is a system configuration value that changes the behavior of `expires`.

**Comment by shcoderepo** [comment]
Looks ok

**Comment by dheerajrp** [comment]
Hi @javimox 
I have made the changes asked for. Please do check.
thanks
