### ISSUE TITLE
Filter sumseverity returns sometimes namedb.db (msg: No such file or directory)

### ISSUE THREAD

**Issue by javimox** [tenable/pyTenable#417]
**Describe the bug**
When using the function sc.analysis.scan with the filter **sumseverity** in scans that take long, Tenable returns sometimes the following error:

`16.08.21 04:59:31  tenable.errors.APIError: None:403 {"type":"regular","response":"","error_code":143,"error_msg":"Unable to process Vuln Query.\nTenable.sc could not process the vulnerability filter string (SC_ROOT=\/opt\/sc \/opt\/sc\/bin\/showvulns-individual +orgid \"1\" +groupid \"5\" +tool 'sumseverity' +scanid '8417' +datedir \"2021-08-16\" +view 'all' +repository \"14\"  -acceptRisk).\nError opening file for buffer data \/opt\/sc\/orgs\/1\/VDB\/2021-08-16\/8417.namedb.db (msg: No such file or directory).\n","warnings":[],"timestamp":1629082737}
`

**To Reproduce**
```
    def get_scan_results(self):
        scan_result = self.sc.analysis.scan(int(self.running_scan_id), tool='sumseverity')
        return scan_result
```

**Expected behavior**
Obtain the result for an specific scan (and not the cumulative)

**Additional context**
I doubt that there is something to do from the pyTenable side, but any feedback would be welcome.

**Comment by dheerajrp** [comment]
- Reason for taking longer time to run, might be you are having wider scan zone wherein you have more number of IPs that are to be scanned.  

- Reason for the error may be if the scan zone is narrow, the number of IPs that are to be scanned will be lower in number. So, when we try to get the analysis report, the scanning might have done. On the contrary, if the scan zone is bigger, the time for scanning will increase because of more number of IPs. Under such circumstances, if we try to get the analysis of the scan, it will throw the error since the scan is not complete for the specified IP range.

Please try to query the analysis of the completed scans.

**Comment by SteveMcGrath** [comment]
Have you checked to see that the import status of the scan is in a completed state before traversing down the results?

**Comment by javimox** [comment]
Hi,

thanks for the following up. I tried to check the status like following, but I still get the same error sometimes. I may not be checking the status properly. Any suggestions/code changes are welcome.


```
    def get_scan_status_by_id(self):
        if int(self.running_scan_id) > 0:
            scan = self.sc.scan_instances.details(int(self.running_scan_id),fields=['running'])
            scan_status = scan['running']
            return scan_status

    def get_scan_results(self, scan_result_id):
        scan_result = self.sc.analysis.scan(scan_result_id, tool='sumseverity')
        return scan_result

scan_status = runner.get_scan_status_by_id()

## when scan is running, scan_status is true
if scan_status != "true":
    results = runner.get_scan_results(scan_result_id)
```

**Comment by SteveMcGrath** [comment]
you should check the "status" and "importStatus" fields.

**Comment by javimox** [comment]
At the end I solved it like following:

```
if scan_status == 'Completed':
            time.sleep(60)  # namedb.db being written to disk
            results = runner.get_scan_results(scan_result_id)
```

The sleep was needed. Thanks for the help.

**Comment by SteveMcGrath** [comment]
I'd argue you're in a race condition in that situation.  you should really just wait for import status to come back as well.  Should be pretty simple to wire into a while loop to check until completed.  A larger scan may take more than a minute to complete.  Also you aren't accounting for scans that may have errored.

**Comment by javimox** [comment]
@SteveMcGrath : thanks for your reply. I will also check `importStatus`, as suggested.
