### ISSUE TITLE
Documentation: missing example for vpr filtering in tio.export.vulns()

### ISSUE THREAD

**Issue by mohnkern** [tenable/pyTenable#422]
**Describe the bug**
In the documentation for exports.vulns() it says:
vpr (dict, optional) –
Restricts the results to the export to only vulnerabilities that match the VPR criteria specified. As this supports a range of operations, it’s worth detailing a couple of examples:

VPR Scores greater than or equal to 7.0:

VPR Score less than 7, but not 5:

No examples are given.

See https://pytenable.readthedocs.io/en/stable/io.html#exports

**Comment by mohnkern** [comment]
Still not displaying.   See screenshot 
![DBE86EC7-F4DC-44E5-AE41-9021C559CF3D](https://user-images.githubusercontent.com/11297297/131200062-ee5adaa2-1805-48da-9c5a-7bc84fbeb7e5.jpeg)

**Comment by dheerajrp** [comment]
Hi @mohnkern 

The changes will reflect in the documentation when the above PR is merged and we do the new release. We will let you know when we do the new release.

thanks
