### ISSUE TITLE
Update the support the proxy for allowing the script to query either tenable.io/tenable.sc

### ISSUE THREAD

**Issue by williamtwar** [tenable/pyTenable#435]
**Is your feature request related to a problem? Please describe.**
The syslog server is in isolated network. Unable to bypass the proxy due to security policy. 
Hence, this script need the proxy function in order to query the tenable.io/tenable.sc

**Describe the solution you'd like**
It would be good if you can include the proxy support for allowing this script to query.

**Comment by SteveMcGrath** [comment]
Pretty support is included already.  just pass a Requests-compliant proxies dictionary to the proxies parameter at instantiation:

https://2.python-requests.org/en/master/user/advanced/#proxies

https://pytenable.readthedocs.io/en/stable/io.html#tenable.io.TenableIO

```python
from tenable.io import TenableIO
tio = TenableIO(proxies={
    'http': 'http://localhost:3128',
    'https': 'http://localhost:3128'
})
