### ISSUE TITLE
pytenable generating error 'No tenable.sc instance at {}:{}'.foramt(host, port)) when tenable instance exists and is properly configured

### ISSUE THREAD

**Issue by prestonSeaman2** [tenable/pyTenable#443]
**Describe the bug**
Whenever I try to connect to and login to the tenable instance I get an error.  I have already checked that the tenable instance is configured correctly and is running.  After further inspection it looks like there may be a bug in the Tenable.sc function around below mentioned code.  The bug may be around how the urllib request was implemented.

# We will attempt to make the first call to the Tenable.sc instance
        # and get the system information.  If this call fails, then we likely
        # aren't pointing to a SecurityCenter at all and should throw an error
        # stating this.
        try:
            self.info = self.system.details()
        except:
            raise ConnectionError('No Tenable.sc Instance at {}:{}'.format(host, port))

Requests Error: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: <tenable instance url> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156786DA940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Requests Error: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: <tenble instance url> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156786DA430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Requests Error: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: <tenable instance url> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156786DA160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
No Tenable.sc Instance at <tenable instance url>
Traceback (most recent call last):
  File "C:\Users\preston.seaman\AppData\Local\Programs\Python\Python39\lib\site-packages\pytenable-1.3.3-py3.9.egg\tenable\sc\__init__.py", line 242, in __init__
  File "C:\Users\preston.seaman\AppData\Local\Programs\Python\Python39\lib\site-packages\pytenable-1.3.3-py3.9.egg\tenable\sc\system.py", line 42, in details
  File "C:\Users\preston.seaman\AppData\Local\Programs\Python\Python39\lib\site-packages\pytenable-1.3.3-py3.9.egg\tenable\base\v1.py", line 591, in get
  File "C:\Users\preston.seaman\AppData\Local\Programs\Python\Python39\lib\site-packages\pytenable-1.3.3-py3.9.egg\tenable\base\v1.py", line 573, in _request
UnboundLocalError: local variable 'resp' referenced before assignment

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".\Documents\Tennable API\nesussscanapi\tennableApiQuery.py", line 71, in <module>
    sc = TenableSC(<tenable instances url> cert=<cert_chain>, access_key=<access_key>, secret_key=<secret_key>)
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\pytenable-1.3.3-py3.9.egg\tenable\sc\__init__.py", line 244, in __init__.py", line 244, in __init__
tenable.errors.ConnectionError: No Tenable.sc Instance at 

**To Reproduce**
1. I run this code. 
 sc = TenableSC(<tenable instance url>, cert=<cert_chain>)
    sc.login(access_key=<access key>, secret_key=<secret_key>)
2. I get the above listed bug

**Comment by SteveMcGrath** [comment]
on step one, how are you passing the URL for Tenable.sc?

**Comment by prestonSeaman2** [comment]
Sorry I accidently deleted it from the report.  It looks like this, sc = TenableSC(url, cert=<certchain>)

**Comment by SteveMcGrath** [comment]
are you passing the hostname?  or the URL?  you should be passing the hostname/ip.

e.g.:

```
sc = TenableSC('tsc.company.tld', access_key=akey, secret_key=skey)
```

NOT

```
sc = TenableSC('https://tsc.company.tld', access_key=akey, secret_key=skey)
```

**Comment by prestonSeaman2** [comment]
I tried with both hostname and url, but I get the same error telling me there is no tenable instance at that location.

**Comment by SteveMcGrath** [comment]
well the URL won't work.  and the example errors you sent:

```
Requests Error: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000156786DA430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

Clearly states that the host "https" doesn't exist.  You could attempt to turn on debug logging and paste the transaction, from there we can evaluate further.  I simply cannot replicate this issue without more information.

**Comment by prestonSeaman2** [comment]
Could you please send me your tenable email.  Also are you lookin for the python script or the server?

**Comment by SteveMcGrath** [comment]
As the older host mythology is being deprecated in favor of the url param in 1.4 going forward, closing this issue as no longer relevant.
