### ISSUE TITLE
Please fix documentation for Container Security

### ISSUE THREAD

**Issue by mmf-Github** [tenable/pyTenable#450]
Hi all, 
https://pytenable.readthedocs.io/en/stable/cs.html#repositories states "Methods available on cs.repositor**ies**" and all the examples are for cs.repositor**y**.* This is consistently wrong throughout the whole of the ContainerSecurity class documentation.

Could you please update the documentation?

Thanks,
MMF

**Comment by SteveMcGrath** [comment]
Note This should be addressed once #459 and #460 are approved and merged
