### ISSUE TITLE
Export/Email tenable.sc scan report in PDF/CSV format which is possible from only console currently 

### ISSUE THREAD

**Issue by itskaranshah** [tenable/pyTenable#458]
**Is your feature request related to a problem? Please describe.**
Trying to make use of this package to automate scans and then send the scan result to the user who ran the scan in a readable format.

**Describe the solution you'd like**
Capability to pass args for report type:
https://pytenable.readthedocs.io/en/stable/sc.html#:~:text=email%40company.tld')-,export_scan,-(id%2C%20fobj%3DNone

https://pytenable.readthedocs.io/en/stable/sc.html#:~:text=finishTime'%5D)%0A%3E%3E%3E%20pprint(scan)-,email,-(id%2C%20*emails)%5Bsource
**Describe alternatives you've considered**

**Additional context**

**Comment by SteveMcGrath** [comment]
Those links go nowhere, so can you elaborate on what you're looking for?

**Comment by itskaranshah** [comment]
Basically, I'm trying to send out email reports(PDF/CSV) of the scan result using pytenable. I'm able to send it with sc.scan_instances.email(scan_id, email) which is a .nessus file in a zip.

Please ignore the links pointing to available methods in the docs.

**Comment by SteveMcGrath** [comment]
If you're looking to have the scan email a report upon completion, you would need to run a report with the scan as the data source.  another option is to link a report to the scan object and have the scan itself generate the report automatically upon completion and email that out for you.
