### ISSUE TITLE
totalRecords for tenable.sc vulns seems to return as 1

### ISSUE THREAD

**Issue by horner00** [tenable/pyTenable#467]
**Describe the bug**
Using the sumip tool, the ITERATOR.total always seems to equal 1.
Not sure if limited to this tool.
I've worked around the issue by returning the  json and grabbing it that way, which does have the correct total.
Also tried setting limit to 999999 thinking it might be a workaround, but no luck

**To Reproduce**
```

vulns = sc.analysis.vulns(
    ('repository', '=', [{'id': repo['id']}]),
    ('pluginID', '=', '19506'),
    ('lastSeen', '=' , '0:21'), limit=999999, tool='sumip'
    )
pprint(vulns.total)

```

**Expected behavior**
vulns.total = the total records of the query

**System Information (please complete the following information):**
 - OS: LINUX RHEL
 - Architecture 64-bit
 - Version 7.9

**Additional context**

**Comment by SteveMcGrath** [comment]
This is expected as the first call has yet to be made.  For example:

```python
>>> from tenable.sc import TenableSC
>>> sc = TenableSC()
>>> vulns = sc.analysis.vulns(tool='sumip')
>>> vulns.total
1
>>> vulns.next()
{'ip': '0.0.228.153', 'uuid': '4add65d0-27fc-491c-91ba-3f498a61f49e', 'score': '307', 'total': '150', 'severityInfo': '131', 'seve
rityLow': '0', 'severityMedium': '9', 'severityHigh': '4', 'severityCritical': '6', 'macAddress': '00:00:00:47:05:0d', 'policyName
': 'Basic Agent Scan', 'pluginSet': '201901281542', 'netbiosName': 'UNKNOWN\\RNKMIGAUV2L8ZEYF.EXAMPLE', 'dnsName': 'rnkmigauv2l8ze
yf.example', 'osCPE': 'cpe:/o:microsoft:windows_10:::x64-home', 'biosGUID': '9e8c4d43-982b-4405-a76c-d56c1d6cf117', 'tpmID': '', '
mcafeeGUID': '', 'lastAuthRun': '', 'lastUnauthRun': '', 'hostUniqueness': 'repositoryID,ip,dnsName', 'uniqueness': 'repositoryID,
ip,dnsName', 'repository': {'id': '2', 'name': 'Staged-Large', 'description': '', 'sciID': '1', 'dataFormat': 'IPv4'}}
>>> vulns.total
102283
>>>
```

**Comment by horner00** [comment]
ah, yes! Suppose if you don't make the first request you don't get the total. Thanks for the response. Makes a lot of sense now.. appreciate it.
