### ISSUE TITLE
Add latest vuln export filters to exports vulns function

### ISSUE THREAD

**Issue by nkeuning** [tenable/pyTenable#47]
**Is your feature request related to a problem? Please describe.**
I need the ability to use the latest filter fields available for the vuln export apis. 

**Describe the solution you'd like**
Update exports.vulns to supports all new filter fields. 

**Describe alternatives you've considered**
Writing my own wrapper to test all this. 

**Additional context**
RDC-3860

**Comment by SteveMcGrath** [comment]
This issues ended up being improper instantiation of the iterators.  Addressed it globally within pyTenable so all iterators subclassed from the base one will inherit the correct logic.
