### ISSUE TITLE
cannot find tenable sc instance

### ISSUE THREAD

**Issue by rennurb3000** [tenable/pyTenable#471]
**Describe the bug**
hi, i wanted to try the tenable sc rest client for our tenable sc server (which is hosted at some ip 123.123.123.123 (example format))
and on a different port 8****
The server is running, since i can get all reports over the ui
sc = TenableSC("123.123.123.123", port=8***, username="username", password="password",scheme="https")
however i get
GET https://123.123.123.123:8***/rest/system >> None:404 {"error":"The requested file was not found."}
No Tenable.sc Instance at 123.123.123.123:8***
previously we used direct get requests like https://123.123.123.123:8***/scans/scanid/export ... 
to optain the wanted data
am i missing something?

**To Reproduce**
1. try example for tenable.sc servers
2. login
3. Error as described above

**Expected behavior**
It would be possible to login

**System Information (please complete the following information):**
 - OS: Server: Windows , client windows with wsl running
 - Architecture 64bit
 - Version 1.3.3
 - Memory 8G

**Comment by SteveMcGrath** [comment]
any reason your not just letting it use the default port?

**Comment by rennurb3000** [comment]
hi pickle rick ;) !
well the reason is, that i am not in the department, which are hosting it and they are not willing to change it.
reasons can be : 
- hosting multiple services on one server
- using a different port instead of the obvious one for security reason
- it has always been this way
- no reason at all, just they wanted it 
also why should i not use a different port ?
The docs say, that it will be deprecated in favour of a unified url parameter (so i guess something like urllib ??)
however not that i cant use it
greets t

**Comment by SteveMcGrath** [comment]
sorry I must have missed that you were running SC on a non-standard port.  The updated format for 1.4.0 and later is to use the following syntax in your case:

```python
from tenable.sc import TenableSC

sc = TenableSC(url='https://123.123.123.123:8443', access_key='', secret_key='')
```

**Comment by rennurb3000** [comment]
Ok thanks!, but still no success -.-
[404: POST] https://***.***.***.***:8***/rest/token body=b'{"error":"The requested file was not found."}'
we are using nessus professional 10.0.0 (#283) WINDOWS
sry i am not that deep into the subject, since i recently got the job to polish some older scripts where requests where directly used. so i thought it would be a great opportunity to use the official client.
greetings, t

**Comment by SteveMcGrath** [comment]
Nessus != Tenable.sc.  Currently there isn't a package for Nessus yet.

**Comment by rennurb3000** [comment]
Ah ok sry, i got it explained like this (that those are tenable.sc instances) , thx
