### ISSUE TITLE
Version 1.4.0 is broken

### ISSUE THREAD

**Issue by conmurray** [tenable/pyTenable#477]
**Describe the bug**
pip installed pytenable.
Now when I try to 
from tenable.io import TenableIO
or even
from tenable.sc import TenableSC

I get import errors.

Rolled back to 1.3.3 and all is working fine with the older version.

**Comment by SteveMcGrath** [comment]
confirming on io the package this is the case.

```python
❯ python
Python 3.9.6 (default, Oct  7 2021, 12:58:22)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tenable.io import TenableIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/smcgrath/.pyenv/versions/pyten14/lib/python3.9/site-packages/tenable/io/__init__.py", line 57, in <module>
    from .cs.api import ContainerSecurity
ModuleNotFoundError: No module named 'tenable.io.cs'
>>> from tenable.sc import TenableSC
>>>
```

**Comment by SteveMcGrath** [comment]
Identified the issue for the IO package was related to the package bundler not including the updated CS and exports packages.  I'm not seeing any errors on the SC package however, can you please report what the import error is for SC?

**Comment by SteveMcGrath** [comment]
1.4.0 was yanked as a bad package.  with the issue identified, 1.4.1 should be out within an hour or two.
