### ISSUE TITLE
Cant pull asset workbenches filtered on tags

### ISSUE THREAD

**Issue by arseassin** [tenable/pyTenable#481]
Asset workbenches appear to have an issue when filtering the pull by custom-made tags. 
This is all done in pycharm:

`for asset in tio.workbenches.assets(('tag.Locations', 'set-has', 'sitexyz - ST')):
print(asset)` 
produces no results and no error

The tags are referenced properly, because if you mistype sitexyz - ST it will throw an exception and provide the list of items it is expecting. Same with set-has vs match etc.

`for asset in tio.workbenches.assets(('tag.Locations', 'set-hasnot', 'sitexyz - ST')):
print(asset)` produces results, including ones that should not be there, such as assets with tag.Locations > sitexyz - ST

To troubleshoot I tried some of the built in functions, such as:
`tio.workbenches.assets(('operating_system', 'match', 'Windows'))`
which works as intended.

I've also tried other tags, such as ones that don't contain spaces as I thought maybe that was the issue, such as:
`tio.workbenches.assets(('tag.Agent', 'set-has', 'Yes'))`
which also produces no results and no error

**Expected behavior**
I'm certain this was working a few weeks ago as I've pulled some one-off asset workbenches for various tasks in the past. 
This should provide a workbench asset snapshot for the specified tags

**Comment by SteveMcGrath** [comment]
id suggest using the asset exports instead.  the workbench APIs are legacy APIs designed to drive the UI and are artificially limited.

https://pytenable.readthedocs.io/en/stable/api/io/exports.html#tenable.io.exports.api.ExportsAPI.assets
