### ISSUE TITLE
scan_instances list start / end period

### ISSUE THREAD

**Issue by ve2tmq** [tenable/pyTenable#483]
**Describe the bug**
start_time and end_time should be int, regarding doc but API doesn't return anything less than 30 days.

def list(self, fields=None, start_time=None, end_time=None, optimize=True):
        '''
        Retrieves the list of scan instances.

        :sc-api:`scan-result: list <Scan-Result.html#ScanResultRESTReference-/scanResult>`

        Args:
            fields (list, optional):
                A list of attributes to return.
            start_time (int, optional):
                Epoch time to start search (searches against createdTime and defaults to now-30d)
            end_time (int, optional):
                Epoch time to end search (searches against createdTime and defaults to now)
            optimize (bool, optional):
                Informs Tenable.sc to optimize completed scan results.  If left
                unspecified, the default is `True`.

        Returns:
            :obj:`dict`:
                A list of scan instance resources.

        Examples:
            * Retrieving all of the manageable scans instances:

            >>> for scan in sc.scan_instances.list()['manageable']:
            ...     pprint(scan)
        '''

**To Reproduce**
>>> SC.scan_instances.list(start_time=7)['manageable']
return list, but period of time doesn't match.

**System Information (please complete the following information):**
 - OS: MacOS, Linux
 - Architecture 64bit
 - Version python 3.9, pytenable 1.4.2
 - Memory 16G

**Comment by SteveMcGrath** [comment]
the time must be sent in epoch (unix timestamp).  Using arrow you would achieve this like so:

```python
import arrow

ts = int(arrow.now().shift(days=-7).timestamp())
scans = sc.scan_instances.list(start_time=ts)['manageable']
```

**Comment by ve2tmq** [comment]
Thanks you so much, it's working for me.  Maybe it should good to add it on doc...
