### ISSUE TITLE
Import error with tenable.nessus

### ISSUE THREAD

**Issue by neeljinwala** [tenable/pyTenable#485]
I am trying to run the below import command with python version 3.9.8
`from tenable.nessus import Nessus`
and it ends up the error
`ImportError: cannot import name 'Nessus' from 'tenable.nessus' (/path_to_home_folder/.local/lib/python3.9/site-packages/tenable/nessus/__init__.py)`

The pytenable package was installed using
`pip3 install pytenable`

**Comment by SteveMcGrath** [comment]
The Tenable Nessus package is still under active development and is currently not in the mainline distribution yet.  Please refer to:

https://github.com/tenable/pyTenable/tree/feature/nessus_pkg
