### ISSUE TITLE
Version 1.4.2 facing issue with 'typing_extensions' module

### ISSUE THREAD

**Issue by SatishAP** [tenable/pyTenable#488]
**Describe the bug**
When trying to run pyTenable-1.4.2 and using
'from tenable.io import TenableIO' 
facing error with 'from typing_extensions import Literal'
ModuleNotFoundError: No module named 'typing_extensions'

Working fine with the previous pyTenable-1.3.3 version

**Expected behavior**
install pytenable without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/88878511/145026556-7469f577-c698-4165-8848-ce0de7a0aefe.png)

**System Information (please complete the following information):**
 - OS: Amazon Linux 2 LTS w/ docker
 - AMI id - ami-0a6ff93f1da8f8f0b

**Additional context**

**Comment by SteveMcGrath** [comment]
thanks for the report.  working on a correction as we speak.  apparently it was a missing comma in the setup.py file.  feel free to just pip install the "typing-extensions" package for now, I hope to have a new build out within a few days.
