### ISSUE TITLE
restfly.errors.BadRequestError not caught by TioExportsError

### ISSUE THREAD

**Issue by curbengh** [tenable/pyTenable#506]
**Describe the bug**
I tried to PDF export a list of scan reports. One of the report is >35 days, so PDF report is not available. Even though my script tried to catch it using `TioExportsError`, but `restfly.errors.BadRequestError` was thrown.

**To Reproduce**
1. Have a scan report that is >35 days.\
2. PDF export it.
``` py
try:
  tio.scans.export()
except TioExportsError as err:
  print('Unable to export')
```
3. See error
```
Traceback (most recent call last):
  File "tenable-io",
    tio.scans.export()
  File "lib/python3.8/site-packages/tenable/io/scans.py", line 986, in export
    fid = self._api.post('scans/{}/export'.format(scan_id),
  File "lib/python3.8/site-packages/restfly/session.py", line 631, in post
    return self._req('POST', path, **kwargs)
  File "lib/python3.8/site-packages/restfly/session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: POST] https://cloud.tenable.com/scans/xxx/export?history_id=xxx body=b'{"error":"Scan results with history_uuid xxx are older than 35 days. Exports are supported in .nessus and .csv formats only."}'
```

**Expected behavior**
should be caught by `TioExportsError`. Currently I catch it with `restfly.errors.BadRequestError` as a workaround.

**System Information:**
 - OS: Ubuntu 20.04 WSL
 - Architecture: x64
 - Version: 1.4.3
 - Memory: 16G

**Comment by SteveMcGrath** [comment]
The TioExportsError only relates to the asset and Vuln exports, not to the scan exports.  This is expected behavior.

**Comment by SteveMcGrath** [comment]
Scans older than 35 days are archived.  Archived scans only have the Nessus can report available to them until the scan is unarchived.

https://docs.tenable.com/tenableio/Content/Scans/ExportScanResults.htm?Highlight=archived%20scan

https://developer.tenable.com/reference#scans-details
