### ISSUE TITLE
Invalid Instance

### ISSUE THREAD

**Issue by NamesNotImportant45** [tenable/pyTenable#513]
**Describe the bug**
After the upgrade of Tenable SC to  5.20.0 the pyTenable API calls result in an error  Invalid instance
ERROR:tenable.errors.ConnectionError:Invalid Tenable.sc Instance

the API key works using Curl command
curl -X GET -k --header "x-apikey: accesskey=05............b6a160940cca2dab96; secretkey=3a..............a60c208122768732" https://serverip/rest/system

Debug of python program shows 

DEBUG:tenable.sc.TenableSC:{"method": "GET", "url": "https://'serverip:443/rest/system", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): serverip:443
DEBUG:urllib3.connectionpool:https://ap0005tsc01.hbi.int:443 "GET /rest/system HTTP/1.1" 200 None
ERROR:tenable.errors.ConnectionError:Invalid Tenable.sc Instance

Trace back shows.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tenable/sc/__init__.py", line 248, in __init__
    self.version = self.info['version']
KeyError: 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./myprogram.py", line 195, in <module>
    main()
  File "./Pmyprogram.py", line 74, in main
    sc = TenableSC('serverip', access_key='05............b6a160940cca2dab96', secret_key='3a..............4a60c208122768732')
  File "/usr/local/lib/python3.8/dist-packages/tenable/sc/__init__.py", line 259, in __init__
    raise ConnectionError('Invalid Tenable.sc Instance')

**To Reproduce**
1. python porgram 
2. sc = TenableSC('serverip', access_key='05............b6a160940cca2dab96', secret_key='3a..............0c208122768732')

**Expected behavior**
should set up instance for calls later.
never sets up to be able to execute call sc.analysis.vulns
**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: [ubuntu sever]
 - Architecture [64bit]
 - Version [18.04]
 - Memory [e8G]

**Additional context**
None

**Comment by SteveMcGrath** [comment]
Are you on the latest version of pyTenable?  1.4.3 should have this fix already:

https://github.com/tenable/pyTenable/pull/475

**Comment by NamesNotImportant45** [comment]
i was not and now have upgraded. thank you for the assist. We are up and running again.
