### ISSUE TITLE
pyTenable & Tenable.sc v5.20 - Invalid Tenable.sc Instance

### ISSUE THREAD

**Issue by aneeq011** [tenable/pyTenable#514]
**Describe the bug**
pyTenable 1.4.3 python running into exception against a tenable.sc running v5.20

**To Reproduce**
Steps to reproduce the behavior
Seems to be only affecting tenable.sc v5.20
```
>> from tenable.sc import TenableSC
>> sc = TenableSC('SECURITYCENTER_NETWORK_ADDRESS')
ERROR:tenable.errors.ConnectionError:Invalid Tenable.sc Instance
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenable/sc/__init__.py", line 248, in __init__
    self.version = self.info['version']
KeyError: 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/srafiuddin/PycharmProjects/Netbox/tenable_helper.py", line 53, in __init__
    self.TENABLE_SC = TenableSC(self.HOST)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenable/sc/__init__.py", line 259, in __init__
    raise ConnectionError('Invalid Tenable.sc Instance')
tenable.errors.ConnectionError: Invalid Tenable.sc Instance
```

**Expected behavior**
expect tenable to initialize so we can proceed to login. 

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by SteveMcGrath** [comment]
Can you confirm you are on 1.4.3?  This is a breaking api issue in SC that we had addressed in 1.4.x

**Comment by xiaoweiwu12701** [comment]
We are seeing the same thing on Centos 7. Our pyTenable is 1.2.5.

**Comment by xiaoweiwu12701** [comment]
> We are seeing the same thing on Centos 7. Our pyTenable is 1.2.5.

We have updated the pyTenable to 1.4.3. Now we get a warning. 

/usr/local/lib/python3.6/site-packages/tenable/base/platform.py:171: AuthenticationWarning: Starting an unauthenticated session
  AuthenticationWarning)
WARNING:tenable.sc.TenableSC:Starting an unauthenticated session.

**Comment by SteveMcGrath** [comment]
instead of using the older authentication strategy of `TenableSC.login`, which was deprecated back in 1.2.x (but still supported), instead you can just pass the username & password to the object constructor like so:

```python
sc = TenableSC(url='https://tenablesc.company.ltd', username='username', password='password')
```

Ideally, you should be using API keys, which have been the preferred method since SC 5.13

```python
sc = TenableSC(url='https://tenablesc.company.ltd', access_key='KEY', secret_key='KEY')
```

Also new in 1.4.x, the Tenable.sc package now (finally) supports environment variables as well.

* `TSC_URL` == Tenable.sc URL
* `TSC_ACCESS_KEY` == API Access Key
* `TSC_SECRET_KEY` == API Secret Key

I am noticing that the doc updates supporting these env vars seem to be absent, along with the over-reaching doc updates switching the documented connection param to use url.  We can work to get these addressed for the next release.

**Comment by xiaoweiwu12701** [comment]
> instead of using the older authentication strategy of `TenableSC.login`, which was deprecated back in 1.2.x (but still supported), instead you can just pass the username & password to the object constructor like so:
> 
> ```python
> sc = TenableSC(url='https://tenablesc.company.ltd', username='username', password='password')
> ```
> 
> Ideally, you should be using API keys, which have been the preferred method since SC 5.13
> 
> ```python
> sc = TenableSC(url='https://tenablesc.company.ltd', access_key='KEY', secret_key='KEY')
> ```
> 
> Also new in 1.4.x, the Tenable.sc package now (finally) supports environment variables as well.
> 
> * `TSC_URL` == Tenable.sc URL
> * `TSC_ACCESS_KEY` == API Access Key
> * `TSC_SECRET_KEY` == API Secret Key
> 
> I am noticing that the doc updates supporting these env vars seem to be absent, along with the over-reaching doc updates switching the documented connection param to use url. We can work to get these addressed for the next release.

thank you. I don't see the warning message anymore after updating the suggested.

**Comment by aneeq011** [comment]
thanks, updating to 1.4.3 and changing to the preferred authentication method resolved all errors.
