### ISSUE TITLE
delete scan throws an error

### ISSUE THREAD

**Issue by f00dikator** [tenable/pyTenable#53]
**Describe the bug**
when deleting a scan, the scan deletes but it throws an error

**To Reproduce**
    new = sc.scans.create(name=name, repo=repoID, policy_id=policy_id,
        targets=[target_ip], description=description, max_time=max_time)

    new_scan_id = int(new['id'])

    running = sc.scans.launch(new_scan_id)
    print('The Scan Result ID is {}'.format(running['scanResult']['id']))
    sc.scans.delete(id=new_scan_id)

**Expected behavior**
the scan does delete, it just throws the following error

**Screenshots**
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tenable/sc/scans.py", line 424, in delete
    ).json()['response']['scans']

**System Information (please complete the following information):**
bash-3.2# uname -a
Darwin tns4361l.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Additional context**

**Comment by SteveMcGrath** [comment]
addressed in 0.3.6
