### ISSUE TITLE
Asset SSL certificate information 

### ISSUE THREAD

**Issue by newbeeeeeee** [tenable/pyTenable#532]
**Describe the bug**
I am looking to grab SSL certificate information of the asset but when I query asset_list() or details() I cannot find this information.

**To Reproduce**
assets = tio.assets.list()
for asset in assets:
  uuid = asset['id']
   asset_details = tio.assets.details(uuid)
   print(asset_details)

**Expected behavior**
Should contain asset ssl certificate details including expiry

**Comment by ChadKlunck** [comment]
Warning: I'm familiar with T.sc and the API but my T.io knowledge is limited, so no guarantee of accuracy.

Certificates don't get reported in the top-level Asset information. They're treated like any other detected vulnerability (plugin result) on the asset. An asset could have zero, one, or many services running on various ports and presenting different certificates.

The plugins most helpful for your use case are probably:

- 15901 (certificate has already expired)
- 42981 (certificate will expire within X days, as specified in the scan policy)
- 10863 (all available information about the certificate)

There are other certificate information plugins as well - searching for <a href="https://www.tenable.com/plugins/search?q=certificate+AND+sensor%3A(nessus)">"certificate"</a> or <a href='https://www.tenable.com/plugins/search?q="ssl+certificate"+AND+sensor%3A(nessus)'>"ssl certificate"</a> in the Plugins list will show most of them.

**Comment by newbeeeeeee** [comment]
Is there an example code that you can share?
