### ISSUE TITLE
Edit Tag Endpoint - Filter Payload failing

### ISSUE THREAD

**Issue by Mooey28** [tenable/pyTenable#539]
**Describe the bug**
I had some code which edited a tag's dynamic rules (filters), it used to work last time I ran it in middle of 2021, but now does not, instead it gives a restfly error:

restfly.errors.UnexpectedValueError: filters is not a filterable option

 I cannot see any difference in my payload production when looking at the API docs: https://developer.tenable.com/docs/apply-dynamic-tags (I have tried adding the "filters" JSON key at the start, which wasn't required previously either, but still the same error).

**To Reproduce**
I was producing filter payload, and trying to edit the tag rule as follows (ipAddressList is a list of IP addresses read in from a CSV file and then comma delimited, uuid is passed into this payload function as a parameter too):

```
payload = {"asset": {"and": [

{

"field": "ipv4",

"operator": "eq",

"value": ipAddressList

}

]}}

tio.tags.edit(uuid,filters=payload)
```

First it wanted it as a list not a dict so I updated the code to convert:

```
payload = {"asset": {"and": [

{

"field": "ipv4",

"operator": "eq",

"value": ipAddressList

}

]}}

payload_list = list(payload.items())

tio.tags.edit(uuid,filters=payload_list)
```

**Expected behavior**
The tag with the given uuid should update it's dynamic rules to contain a list of IP addresses for the tag to be applied against.

**System Information (please complete the following information):**
 - OS: Windows 10
 - Architecture 64bit
 - Version 1.4.3

**Comment by inayathulla** [comment]
Hi @Mooey28, 

Please try as below.
`tio.tags.edit(uuid, filters=( [ ('ipv4', 'eq', ['1.1.1.1', '10.10.10.10'] ) ] ))`

Replace `1.1.1.1` and `10.10.10.10` with the corresponding ip addresses you like.

For more info refer -> https://pytenable.readthedocs.io/en/stable/api/io/tags.html
