### ISSUE TITLE
Can't install on RHEL7 machine, pip issue with 'requests' module

### ISSUE THREAD

**Issue by raspinall** [tenable/pyTenable#54]
**Describe the bug**
When attempting to install on a RHEL7 machine, we get the following error:

Installing collected packages: requests, python-dateutil, lxml, pytenable
  Found existing installation: requests 2.6.0
Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

The pip version installed is 8.1.2-6, from EPEL, as package python2-pip

**To Reproduce**
1. pip install pytenable
2. See error

**Comment by SteveMcGrath** [comment]
This is likely unrelated to anything other than pip.  Can you upgrade pip first?

    pip install -U pip

Then try again.  if still nogo, you may want to consider running within a virtual environment or a non-system python environment.
