### ISSUE TITLE
readthedocs - scans

### ISSUE THREAD

**Issue by Satisfaption** [tenable/pyTenable#542]
Hey guys,
minor error in Documentation for Scans (https://pytenable.readthedocs.io/en/stable/api/sc/scans.html)
Tried editing policy with the name provided in the edit section (policy) which resulted in error 142.
Using the one from the create section (policy_id) worked.

**Comment by inayathulla** [comment]
Thanks for letting us know about the issue @Satisfaption ! We will update the doc soon.
