### ISSUE TITLE
Call "TeanbleException"

### ISSUE THREAD

**Issue by iamchiho** [tenable/pyTenable#543]
Hi all, may I know if "TenableException" being removed? How to make the change if exiting script using this call?

Thanks

**Comment by SteveMcGrath** [comment]
TenableException was removed in 1.4 as the lower-level connection logic was moved instead to the restfly library as it's more reusable there.

To replicate similar behavior in 1.4+, you can replace the import for tenable Exception using the following line:

```python
from restfly.errors import RestflyException as TenableException
```

Note the RestflyException is documented here:

https://restfly.readthedocs.io/en/latest/api/errors.html#restfly.errors.RestflyException

I apologize for the confusion, however a lot of this effort was revolving around testability of the codebase moving forward and re-usability of the underlying connection logic that can be used in other libraries or SDKs as well.

**Comment by iamchiho** [comment]
Thanks for your help @SteveMcGrath
