### ISSUE TITLE
Having issue running tenable-jira --options

### ISSUE THREAD

**Issue by bizznasty** [tenable/pyTenable#557]
Hello,

I am able to do the basic run by just "tenable-jira config.yaml"

However I am trying to run it with the options available -s and -f. However whenever I try to run
tenable-jira -f -s $(date -v-1d +%s) config.yaml

I get an error:

tenable-jira -f -s $(date -v-1d +%s) tenable_jira.yaml
Get-Date : A parameter cannot be found that matches parameter name 'v-1d'.
At line:1 char:27

tenable-jira -f -s $(date -v-1d +%s) tenable_jira.yaml
                      ~~~~~
CategoryInfo : InvalidArgument: (:) [Get-Date], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetDateCommand
Usage: tenable-jira [OPTIONS] [CONFIGFILE]
Try 'tenable-jira --help' for help.

Error: Invalid value for '--observed-since' / '-s': 'tenable_jira.yaml' is not a valid integer.

Please advise.

Thank you

**Comment by SteveMcGrath** [comment]
This isn't a pytenable issue and should be raised in the jira cloud integration repo.
