### ISSUE TITLE
TenableSC.scans.list() not working as expected

### ISSUE THREAD

**Issue by securitytime** [tenable/pyTenable#560]
Hello,
We are running Tenable.sc (Core). In the Web UI (under Scans > Active Scans) we have configured a couple of scans.
What I would like to archive using PyTenable is 1) to list all available scans (name + ID) and 2) to launch a particular scan.
The second part is easy: TenableSC.scans.launch(18). I could find out a scan's ID in the web UI.
However, the first part seems tricky. I tried TenableSC.scans.list() but that returns only two strings: **usable** and **manageable**.
Is this a bug or am I doing something wrong?

**Comment by ChadKlunck** [comment]
`TenableSC.scans.list()` returns a JSON object:

```
{'manageable': [{'description': 'Monthly scan',
                 'id': '1',
                 'name': 'Company.com Monthly Scan',
                 'status': '0'},
                {'description': 'Temporary scan - delete this later',
                 'id': '2',
                 'name': 'Temp Scan',
                 'status': '0'}],
'usable': [{'description': 'A scan which your account doesn't have permission to manage',
            'id': '4',
            'name': 'John - Test Scan',
            'status': '0'}]}
```

So 'usable' and 'manageable' are not *strings*, each one is a *list* containing multiple dictionaries (one dict for every scan).

Some sample code to print a list of scans:

```
scans = TenableSC.scans.list()
all_scans = [*scans['manageable'], *scans['usable']]

for item in all_scans:
    print(f'{item["id"]:>4}   {item["name"]}')
```

which should produce something like:

```
   1   Company.com Monthly Scan
   2   Temp Scan
   4   John - Test Scan
```

**Comment by securitytime** [comment]
Thanks for your reply. I just tried it again and this time I got a JSON object similar to yours. I'm not sure what I did wrong the first time.

So everything is working as expected. Sorry for this unnecessary post and thanks again.
