### ISSUE TITLE
Use list of strings for CPE's returned from sc.plugins.details()

### ISSUE THREAD

**Issue by 00willo** [tenable/pyTenable#601]
**Is your feature request related to a problem? Please describe.**
Upon getting the relevant cpe's that apply to a plugin, the results for multiple entries are presently returned as a single string with `\n` separating the cpe entries.  While this makes it easy to use with something like `pprint` for just displaying the output, it does not feel like the correct type to use here for any further processing of the data.

**Describe the solution you'd like**
Having details return a list of strings would work better for the `cpe` key in the details dict that is returned by the `sc.plugin.details` method call.  

**Describe alternatives you've considered**
For almost any use case beyond just displaying the `cpe` output would require all usages to separate the output on `\n`, which feels messy and repetitive.  Testing for how many are present would be 

**Additional context**
Currently it looks like this
```
>>> from tenable.sc import TenableSC
>>> sc = TenableSC(<url>)
>>> sc.login(<username>,<password>)
>>> vuln_cpes = sc.plugins.details(159571)['cpe']
>>> print(vuln_cpes)
'cpe:/o:apple:mac_os_x\ncpe:/o:apple:macos'
```
My suggestion would yield this instead
```
>>> from tenable.sc import TenableSC
>>> sc = TenableSC(<url>)
>>> sc.login(<username>,<password>)
>>> vuln_cpes = sc.plugins.details(159571)['cpe']
>>> print(vuln_cpes)
['cpe:/o:apple:mac_os_x', 'cpe:/o:apple:macos']
```
Apart from the obvious for `vuln_cpe in vuln_cpes` type iteration over a list of vulnerable cpes to further process them, I'm thinking when asking questions of the data `len(vuln_cpes)` is very clear.  Also consider performing `set` or test for `in` the list, such as `if "cpe:/o:apple:macos" in vuln_cpes:` style conditional tests.

**Comment by SteveMcGrath** [comment]
The upstream SC API presents the data in this way and the library is just transparently returning back what the API presents.

If you want to separate it out, try the following:

```python
vuln_cpes = sc.plugins.details(159571)['cpe'].split('\n')
```
