### ISSUE TITLE
Dashboards in Tenable.sc

### ISSUE THREAD

**Issue by Gmunker** [tenable/pyTenable#603]
**Is your feature request related to a problem? Please describe.**
Unable to hit the Dashboards in Tenable.sc with PyTenable

**Describe the solution you'd like**
Modules to work with the Dashboards

**Describe alternatives you've considered**
Using the Tenable.sc API, although PyTenable hitting the Dashboards would make things a lot easier.

**Comment by SteveMcGrath** [comment]
You can use the base HTTP verbs using the TenableSC class today, but yes they aren't naturalized today.  Note the documentation that all of the product classes share below.

https://pytenable.readthedocs.io/en/stable/api/base/platform.html
