### ISSUE TITLE
limit parameter in the list method in agents API for Nessus not work as expected

### ISSUE THREAD

**Issue by Barnoux** [tenable/pyTenable#605]
**Describe the bug**
The parameter 'limit' of the method 'list' related to agents API in Nessus.agents is not implementd as expected.

In the documentation, when you use the limit parameter to get a list of agents, If you want only one result to return after you made q query you have to put a limit of 1. Today, it's seems that you have one agent per page?

**To Reproduce**
1. Have 5 group of agents with the respective name ['Group_A', 'Group_B', 'Group_C', 'Group_D', 'Group_E'] and one instance of nessus manager,
2. Have a list 10 agents,
3. Each agents linked to nessus manager should be assigned to only one group, 
4. execute the code bellow:
```python
from tenable.nessus import Nessus
AGENT_GROUP_NAME = ['Group_A', 'Group_B', 'Group_C', 'Group_D', 'Group_E']
nessus = Nessus(username='username', password='password', url='url')
chosen_groups = [group for group in nessus.agent_groups.list() if group.get('name') in AGENT_GROUP_NAME]
for group in agent_groups:
  filtered_agents = nessus.agents.list(limit=1, filters=[('groups', 'eq', group.get('name'))])
    for agent in filtered_agents:
    print(agent)
```

**Expected behavior**
After executing the code bellow, i expect to have in the variable filtered_agents: list[dict]  a lenght of 1. And it's not the case...

**Screenshots**
Difference from the PyTenable documentation and the API documentation in Nessus Manager from the GUI.
![image](https://user-images.githubusercontent.com/47791676/181766736-a7030287-b9c6-4e6f-8f30-1ef27c7794c5.png)
![image](https://user-images.githubusercontent.com/47791676/181767207-fcca144f-4217-475a-9725-41e54da81d45.png)

**System Information:**
 - OS: Windows 10 20H2 (19042.1826)
 - Architecture : 64 bit
 - Version: Python 3.9.6
 - Memory: 8G

**Comment by SteveMcGrath** [comment]
Limit refers to the number of elements per page.  as an iterator object is returned, its referring to the number of elements that are loaded into the iterator before it needs to query the API again.  If you turn on the debug logging you'll notice this behavior.

**Comment by Barnoux** [comment]
Thank for the answer, do you know how can i do then to have only the exact number of agents based on the limit parameter ?

**Comment by Barnoux** [comment]
With some time, i finally find a solution. I just have to break the loop when i have the number of agents that i want.

**Comment by aseemsavio** [comment]
Closing.
