### ISSUE TITLE
It is taking too long to show the vulnerability data based on specified filter value.

### ISSUE THREAD

**Issue by CyberTeam4321** [tenable/pyTenable#609]
**Describe the bug**
If I include the source to show vulnerability such as  Cumulative or Mitigated and filter the result based on Severity such as Critical, high, medium and low except Informational, the result is talking a long time to process. It is still pending around 7 hours..

**To Reproduce**
sc = TenableSC('IPADDRESS')
sc.login(access_key='redacted', secret_key='redacted')
for vulns in sc.analysis.vulns(source='cumulative'):
    if (vulns['severity']['id']) != '0':
        print(vulns)

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows Server 2019 Datacenter 
 - Architecture 64bit
 - Version pyTenable==1.4.6
 - Memory 16 GB
 - Processor 2 processor 2.10 Ghz
**Additional context**

**Comment by SteveMcGrath** [comment]
Firstly, you should do as much of your filtering server-side, and not on the client.

```python
with TenableSC(url='https://IPADDRESS', access_key='AKEY', secret_key='SKEY') as sc:
    for vuln in sc.analysis.vulns(('severity', '=', '1,2,3,4')):
        print(vuln)
```

That _should_ run faster right off the bat.  If you need more speed, try increasing the page limit so more items get returned per page:

```python
with TenableSC(url='https://IPADDRESS', access_key='AKEY', secret_key='SKEY') as sc:
    for vuln in sc.analysis.vulns(('severity', '=', '1,2,3,4'), limit=1000):
        print(vuln)
```

If things are still quite slow, take a look at the Tenable.sc instance and see if it's performing correctly.  If it's being overtaxed then it may have problems serving the data within a reasonable timeframe.
