### ISSUE TITLE
severity filter not working in sc.analysis.vuln

### ISSUE THREAD

**Issue by CyberTeam4321** [tenable/pyTenable#610]
**Describe the bug**
If I include severity in filters, then pyTenable throws an error

It stated an error below.
sc.py", line 18
for vulns in sc.analysis.vulns((source='cumulative'),('severity', '!=','0')):
^
SyntaxError: expected ':'

**To Reproduce**
from tenable.sc import TenableSC
sc = TenableSC('ipaddress')
sc.login(access_key=<access_key_value>, secret_key=<secret_key_value>)
for vulns in sc.analysis.vulns((source='cumulative'),('severity', '!=','0')):
print(vuln)
sc.logout()

**Expected behavior**
It should show cumulative vulnerability data which severity should be critical, high, medium and low.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows Server
 - Architecture 64 bit
 - Version pyTenable==1.4.6
 - Memory 16 GB

**Additional context**

**Comment by ChadKlunck** [comment]
The severity tuple is a filter argument; the source _looks_ like a filter argument but it's actually a keyword argument. Filters need to appear before keyword arguments.

The following modification should work:

```
for vulns in sc.analysis.vulns(('severity', '!=', '0'), source='cumulative'):
    print(vulns)
```

While there's no harm in including source='cumulative', that is the default value for the source parameter, so it doesn't need to be explicitly specified.
