### ISSUE TITLE
Get Lists of Credentials currently in Tenable.sc

### ISSUE THREAD

**Issue by ekmixon** [tenable/pyTenable#611]
**Is your feature request related to a problem? Please describe.**
I cannot seem to get the credentials currently in tenable.sc  unless I have the id. 

**Describe the solution you'd like**
I would like to create a list of credentials that I have and all of their settings based on what certain attributes equal.  

**Describe alternatives you've considered**
I think I can do this using the actual API, but I cannot seem to do it with the python wrapper, pyTenable. 

**Additional context**

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/api/sc/credentials.html#tenable.sc.credentials.CredentialAPI.list
