### ISSUE TITLE
Error when setting Tenable.sc Credentials with Cisco privilege escalation

### ISSUE THREAD

**Issue by nkoleske** [tenable/pyTenable#618]
**Describe the bug**
The pyTenable Tenable.sc Credentials API (and the Tenable.sc docs) have the incorrect value listed for Cisco privilege escalation. Trying to set the privilege escalation with the suggested `sc.credentials.edit("1000001", privilege_escalation="cisco")` results in an error from the API: "Map not found for privilegeEscalation 'cisco'.

**To Reproduce**
using pyTenable 4.1.7 with Tenable.sc 5.19:
1. Establish an authenticated Tenable.sc session
2. Create a credential entry
3. `sc.credentials.edit("1000001", privilege_escalation="cisco")`

**Expected behavior**
The credential's privilege escalation setting should be set to Cisco 'Enable', and not throw an error

**System Information (please complete the following information):**
 - pytenable 4.1.7 with python 3.7 on Windows 10 64 bit
 - Tenable.sc 5.19

**Additional context**
Getting the credential details `sc.credentials.details("1000001")` from a credential with Cisco 'Enable' set via the GUI shows 'privilegeEscalation': "Cisco 'enable'"

**Comment by inayathulla** [comment]
@SteveMcGrath, 

In credentials.py we have the customer name `cisco` added, just curious to check if adding a name is appropriate in this file, do we add other customer names as well? please correct me if I'm wrong.

**Comment by inayathulla** [comment]
Post discussion with @SteveMcGrath, it is evident to use "Cisco 'enable'" as API recognizes it and pyTenable is mimicking the same behavior.
