### ISSUE TITLE
Implement Export scan results and Download exported scan for WAS v2

### ISSUE THREAD

**Issue by fullofentropy** [tenable/pyTenable#622]
**Is your feature request related to a problem? Please describe.**
See Title: API features are not yet implemented and I would like them.
https://developer.tenable.com/reference/was-v2-scans-export
https://developer.tenable.com/reference/was-v2-scans-download-export

**Describe the solution you'd like**
Fork this repo and implement these API endpoints per the spec and do a pull request.
Plan:   rework : ./tenable/io/scans.py->ScansAPI>export()
- add additional scan_type string/flag 'web-app2'  in order to flag WASv2 scan
- refactor add logic to ensure this doesn't mess up what already exists
- add conditional to direct code flow if 'web-app2' is passed as 'scan_type'
- mirror a similar flow/style to what is already implemented for code readability.

**Describe alternatives you've considered**
waiting until someone else implements WAS v2 API specifications:  
https://developer.tenable.com/reference/was-v2-scans-export

**Additional context**

**Comment by aseemsavio** [comment]
Closing as a Feature Request.

**Comment by SteveMcGrath** [comment]
WAS bulk export API support has been mainlined and a new version of the library is anticipated before Dec.
