### ISSUE TITLE
Issue with "from .base import SCEndpoint"

### ISSUE THREAD

**Issue by mthakk3793** [tenable/pyTenable#627]
For [Tenable.SC](https://tenable.sc/), working on pytenable I have been having issues with the import that was recommended on the [tenable.sc](https://tenable.sc/) documentation. One of the imports is "from .base import SCEndpoint, SCResultsIterator". I am getting the error : "ImportError: attempted relative import with no known parent package." Can someone please explain how I bypass this? I don't know if I need some sort of pip install or update, but I cannot find a solution after searching for hours.

**Comment by ChadKlunck** [comment]
The `from .base` import statement is used internally by the pyTenable package, and probably isn't what you're looking for.

For basic Tenable.sc tasks, importing TenableSC is normally enough:

```python
from tenable.sc import TenableSC
sc = TenableSC(hostname, access_key, secret_key)

# Do stuff with the 'sc' object, such as:
vulns = sc.analysis.vulns(('pluginID', '=', '19506'))
```
