### ISSUE TITLE
Question - How do you list the scans result ?

### ISSUE THREAD

**Issue by Barnoux** [tenable/pyTenable#634]
Hello,

I didn't find how to do it in the documentation.

I would like to have an object where i can find the attributs bellow, in the result scan section of tenable sc:
Start Time
Finish Time
Status
Duration
Import Start
Import Finish
Import Status
Import Duration
Owner
Group
ID

Something like this:
```python
for scan in sc.result.list():
     pprint(scan)
```

Regards,

BBA

**Comment by SteveMcGrath** [comment]
https://pytenable.readthedocs.io/en/stable/api/sc/scan_instances.html#tenable.sc.scan_instances.ScanResultAPI.list

**Comment by Barnoux** [comment]
Thanks! :)
