### ISSUE TITLE
installing pyTenable installs a "tests" package

### ISSUE THREAD

**Issue by brianmedigate** [tenable/pyTenable#642]
**Describe the bug**
When I install pyTenable into a clean virtual environment, it apparenly also installs a `tests` package. This is problematic because it pollutes the namespace and prevents me from importing a local tests module.

**To Reproduce**
```
(venv) $ pip install pytenable
(venv) $ ls venv/lib/python3.8/site-packages/tests/
io  nessus  ot  reports  sc
(venv) $ 
```

**Expected behavior**
I doubt the intention was to publish the tests along with the package.

**Comment by varap11** [comment]
Changes are present in https://github.com/tenable/pyTenable/pull/648
