### ISSUE TITLE
Login "Type" under account not reflecting cert

### ISSUE THREAD

**Issue by nessusnerd** [tenable/pyTenable#647]
**Describe the bug**
Admin account successfully created via pyTenable shows "TNS" instead of "Cert" under Users screen.
Admin successfully logs into SC with cert.  No issues except that his account still shows "TNS."

**To Reproduce**
1. Write script for sc.users.create with appropriate API key
2. Provide required parameters (username, password, role ID, group ID)
3. Provide optional parameters (in this case, 'fingerprint')
4. Have Admin login with browser and ensure that Cert is valid

![image](https://user-images.githubusercontent.com/96888499/202283159-114a1a47-f53c-451f-a1b4-a0f4e0d7ab5f.png)

**Expected behavior**
The account should show "Cert" instead of "TNS" on the Users screen.

My Admin has not experienced any difficulty doing anything in SC.   However, we can't get the login Type to update to 'Cert'
Not a problem for him, but our team relies on this for troubleshooting Users who are locked out.

**Comment by inayathulla** [comment]
@nessusnerd Thanks for raising your concern, 

users.py under tenable/sc in pyTenable  sets `auth_type` to `tns` if no value is passed, make sure to pass appropriate value, in your case `cert` and check again.

Below us line which sets 
` kw['auth_type'] = kw.get('auth_type', 'tns')` inside `def create(self, username, password, role, **kw):`

**Comment by nessusnerd** [comment]
@inayathulla thank you for the response.  I was aware of the 'auth_type' parameter when developing the script, but the documentation only mentions _ldap, legacy, saml, tns._  If _cert_ is a valid option, I will certainly try that.

**Comment by inayathulla** [comment]
@nessusnerd, you are right, the current version of Tenable.SC API doesn't support, in fact from many years, but cert type can be associated as below.

Refer:- `[link](https://docs.tenable.com/tenablesc/api/Current-User.htm#CurrentUserRESTReference-/currentUser/associateCert)`

`/currentUser/associateCert

Methods

POST

Associates a certificate that was presented to the server with the user’s account, allowing for auto-login.
Note: When askAboutCert=“true”, then the F/E would allow you to save your fingerprint.
Note: Certificates cannot be associated with linked users.`
