### ISSUE TITLE
Need pytenable library to export config compliance scan data for tenable.sc

### ISSUE THREAD

**Issue by virenukey** [tenable/pyTenable#655]
We have an API endpoint to get the config data from tenable.sc - https://docs.tenable.com/tenablesc/api/Configuration.htm

To support the above config API in pytenable, we need a library that will be as same as vulnerability under analysis "analysis.vulns"

**Comment by SteveMcGrath** [comment]
Config and compliance data is provided under the analysis.vulns endpoint, you just have to present the correct filters to get just compliance data.
