### ISSUE TITLE
Accept and pass kwargs to _api.get()

### ISSUE THREAD

**Issue by efojs** [tenable/pyTenable#665]
I get `500` sometimes when requesting `/assets/<uuid>`.

Error message recommends to retry: "Please wait a moment and try your request again"
I want to retry by passing `retry_on` to RESTfly's `APISession._req`: 
```py
retry_codes = kwargs.pop('retry_on', []).
```
via
```py
tenableio.assets.details(uuid, retry_on=[500])
```

But `AssetsAPI.details()` accepts only `uuid`: https://github.com/tenable/pyTenable/blob/414cd4a698f208ce0aae7bd4f24ee2d3404a4360/tenable/io/assets.py#L55

Would be great to accept and pass `kwargs` in all methods with `return self._api.get()`

**Or is there a reason that I don't see why `kwargs` are not passed?**

**Comment by SteveMcGrath** [comment]
Note, that if you want to have a specific exception type retried, then you can always modify the class retry like so:

```python
from restfly.errors import NotFoundError

NotFoundError.retryable = True
```
