### ISSUE TITLE
SC Organization Endpoint

### ISSUE THREAD

**Issue by underwateroverlander** [tenable/pyTenable#666]
**Describe the bug**
The sc.organization.create call requires vulnScoringSystem to be included. There is currently no defined parameter for this and documentation needs to be updated.

**To Reproduce**
1. Try to create repository with `org = sc.organization.create('MainOrg')` returns: `ERROR:restfly.errors.APIError:[403: POST] https://localhost:443/rest/organization body=b'{"type":"regular","response":"","error_code":142,"error_msg":"Please specify a valid vulnerability scoring system for this Organization.\\nThe attribute \'vulnScoringSystem\' is required.`

**Expected behavior**
With the parameter built in and documented, Org should be created.

**System Information (please complete the following information):**
 - OS: [e.g. MacOS] MacOS (Docker)
 - Architecture [e.g. 64bit, 32bit] 64bit
 - Version [e.g. 2.7.9] pyTenable 1.4.11 (latest), Tenable.sc 5.23.1 
 - Memory [e.g. 4G] 16GB

**Comment by SteveMcGrath** [comment]
The error notes what's missing here:

```python
org = sc.organization.create('MainOrg', vulnScoringSystem='CVSSv3')
```

The module should likely be updated to include that by default, as it is the default scoring system used.
