### ISSUE TITLE
Tenable CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [tenable/pyTenable#668]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Tenable plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Tenable APIs/data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by aseemsavio** [comment]
@yevgenypats You can create a feature request here: https://www.tenable.com/partners/tech-alliances-application

**Comment by yevgenypats** [comment]
> @yevgenypats You can create a feature request here: https://www.tenable.com/partners/tech-alliances-application

Sounds good! Creating. Thank you!

**Comment by aseemsavio** [comment]
@yevgenypats An update - 

Feature requests go here: https://suggestions.tenable.com/

To become a vendor partner, you can submit your request here: https://www.tenable.com/partners/tech-alliances-application

**Comment by aseemsavio** [comment]
That's okay.  The request you must have created in the tech alliances application should be enough.
