### ISSUE TITLE
analysis.scan(id) ignores id and returns cumulative after upgrade to tenable.sc 6

### ISSUE THREAD

**Issue by javimox** [tenable/pyTenable#673]
**Describe the bug**
After upgrading tenable.sc to version 6 I see the following issue:
`sc.analysis.scan(scan_id)` returns information about vulnerabilities found in all the repositories.
It returns all the vulnerabilities found in cumulative, not only in `scan_id`

**To Reproduce**
```
for vuln in sc.analysis.scan(scan_id):
  pprint(vuln)
```

**Expected behavior**
Expected information specific to the scan provided by its id (in other words, information only about the scanned machine(s) in the specified repository).

From the documentation:
https://pytenable.readthedocs.io/en/stable/api/sc/analysis.html
scan_id ([int](https://docs.python.org/3/library/functions.html#int)) – If a scan id is specified, then the results fetched will be from the scan specified and not from the cumulative result set.

**System Information (please complete the following information):**
 - Tenable.sc
 - Version 6

**Comment by ash-bs** [comment]
+1
We just upgrade to SC 6 this morning. Spent the past 4 hours troubleshooting my script - that uses sc.analysis.scan(scan_id)
I am seeing the same behavior that you mentioned above. (analysis.scan(id) ignores id and returns cumulative)

I still have another SC instance on 5.22 and the same analysis.scan(id) works there like intended.

**Comment by SecOpsQC** [comment]
+2
Same issue here. Everything was working fine until update to Tenable 6.X. scanid is ignore and return cumulative result.

I've tried to use vulns() with scan_id and I got the same result

**Comment by SteveMcGrath** [comment]
PR (linked above) addressing the issue is currently in review.  It was an undocumented change to the SC 6 API.

**Comment by aseemsavio** [comment]
Thanks, @SteveMcGrath!

pyTenable 1.4.12 with this fix has been released.

**Comment by javimox** [comment]
Tested. Thank you!
