### ISSUE TITLE
Query on Tenable.sc API - Analysis

### ISSUE THREAD

**Issue by stiong-p** [tenable/pyTenable#680]
Hi, I would like to understand the definitions of the API analysis output data below, or there other documentation that I may refer to?: 
1. The difference between "ips" and "ip".

2. The last_seen_after and last_seen_before are null, why would it be null? 
last_seen : (epoch-timestamp)
last_seen_after: null 
last_seen_before: null

Thank you in advance!

**Comment by aseemsavio** [comment]
Hi, is [this](https://docs.tenable.com/tenablesc/api/Analysis.htm#AnalysisRESTReference-/analysis) the API you're referring to?

**Comment by aseemsavio** [comment]
Could you also mention the version of Tenable.sc you're using?

**Comment by stiong-p** [comment]
It is with reference to https://pytenable.readthedocs.io/en/stable/api/sc/analysis.html, using T.sc 5.23.1.

**Comment by aseemsavio** [comment]
Here's the response to the question from T.sc team.

> The ip field is the IP address of the host (in IP repos it’s the IP address stored in the .hdb file).  The ips field is all the IP addresses stored in the namedb for that host. May be “last_seen_after” and “last_seen_before” fields were from old implementation. I don’t see any reference to these fields in SC current code base.
