### ISSUE TITLE
tenable.nessus: agent_groups.list() exception: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dsobon** [tenable/pyTenable#683]
**Describe the bug**

For tenable.nessus module, "api.agent_groups.list()" fails if there are no agent groups configured on the Nessus Manager.

**To Reproduce**

```
from tenable.nessus import Nessus
api = Nessus(url=...)
api.agent_groups.list()
```

**Current behaviour**

```
  File "./test.py", line 244, in get_agents_metadata
    api.agent_groups.list()
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**

No exception triggered.

**Comment by aseemsavio** [comment]
The `nessus.agent_groups.list()` function returns a nullable list of dictionaries, and not an iterator. Hence the possible None values should be dealt with in the client side.
