### ISSUE TITLE
Tenable.sc create policies not working for template id 25 (advanced agent scan).

### ISSUE THREAD

**Issue by huubverheyen** [tenable/pyTenable#688]
**Describe the bug**
When creating a policy, using the parameters name and template_id, template id 25 (Advanced Agent Scan) returns an error. For other template id's it works as intended.

**To Reproduce**
1. Go to https://pytenable.readthedocs.io/en/stable/api/sc/policies.html
2. Call the "create" method / function
3. Do use the parameters name and template_id. Template id 25 to be specific
4. See error "TypeError: preference:staggered_start_mins:value is of type int.  Expected str"

**Expected behavior**
Create a TenableSC policy with the provided name and template_id (25 --> Advanced agent scan)

**System Information (please complete the following information):**
 - OS: Ubuntu
 - Architecture 64bit
 - Version 20.04
 - Memory [8 GB]

**Comment by 6illess** [comment]
Hi, any update on this please?

**Comment by SteveMcGrath** [comment]
@huubverheyen apologies for the delay, have you tried recasting the value of `staggered_start_mins` as a string?

**Comment by SteveMcGrath** [comment]
can you please paste an example of the code thats throwing the error?

**Comment by huubverheyen** [comment]
You can copy paste the following basic code to see it yourself:
`if __name__ == '__main__':
    tenablesc = TenableSC(host="xxxxxxxxx", access_key="xxxxxxxxx", secret_key="xxxxxxxxx")
    tenablesc.policies.create(name="test_policy_template_id", template_id=25)`


You can try it as well with other template id's. those just works as intended. For example:
1 - Advanced scan
2 - Host Discovery
3 -  Basic Network Scan
7 - Policy compliance auditing 
12 - PCI Quarterly External Scan

**Comment by 6illess** [comment]
@SteveMcGrath any update on this issue?
If it's not related to pyTenable but to the Tenable SC API, please let us know so we can open up a support case.

**Comment by huubverheyen** [comment]
Hi @SteveMcGrath, this indeed worked. 
Thank you for your help and clear explanation! :)
