### ISSUE TITLE
tenablesc scan_instances export_scan, add PDF format for export file

### ISSUE THREAD

**Issue by TheITRx** [tenable/pyTenable#689]
Currently, tenablesc scan_instances does not support export to pdf. It only is able to export to .nessus format. 

--> https://pytenable.readthedocs.io/en/stable/_modules/tenable/sc/scan_instances.html#ScanResultAPI.export_scan

**Describe the solution you'd like**
A parameter discribing pdf as an option for the export file format. 

**Describe alternatives you've considered**
tenablesc currently does not have the report resource. Perhaps create one as well for that.

**Comment by aseemsavio** [comment]
I'm afraid PDF isn't supported. The supported formats are Nessus, zip, and a diagnostic db file.

**Comment by aseemsavio** [comment]
I'm afraid PDF isn't supported by Tenable.sc. The supported formats are Nessus, zip, and a diagnostic db file.
