### ISSUE TITLE
Question: Sudden 400 error when exporting vulnerabilities

### ISSUE THREAD

**Issue by cyber-galactica** [tenable/pyTenable#691]
Our script has been using exports.vulns with vpr_score, first_seen and state filters passed. It has been running without issues then suddenly we are getting this error. Our developer suspects issues with the API endpoint. Has anyone run into this problem?

BadRequestError: [400: GET] https://cloud.tenable.com/vulns/export/xxxxxxx-g454g-wtwec/status body=b'Unrecognized field &quot;empty&quot; (class com.tenable.service.vmexport.model.NumericFilter), not marked as ignorable'

**Comment by marcwtm** [comment]
I have the same issue.

**Comment by rucksacklabs** [comment]
Apologies, we got a bit carried away with input validation there. 😄 
We are going to deploy a fix shortly and your exports should work as expected again.

**Comment by cyber-galactica** [comment]
Hi @rucksacklabs - do you have an ETC for this please?

**Comment by rucksacklabs** [comment]
> Hi @rucksacklabs - do you have an ETC for this please?

A fix went out that same day.

**Comment by cyber-galactica** [comment]
thank you, confirmed to be working now
