### ISSUE TITLE
[Nessus] No output to console for query to Nessus "scans" endpoints

### ISSUE THREAD

**Issue by stiong-p** [tenable/pyTenable#693]
I have set py code as follows, to test some of the scans endpoint: 
```
from tenable.nessus import Nessus
nessus = Nessus(url='https://IP_ADDRESS:8834',
                access_key='ACCESS_KEY',
                secret_key='SECRET_KEY'
                )
nessus.scans.details(7)
nessus.scans.plugin_output(7, 2, 19506)
nessus.scans.plugin_output(
        scan_id=7,
        host_id=2,
        plugin_id=19506)
nessus.scans.export_formats(7)
```
python3 <py.file> ran without issue, but there was also no output. 

By drilling into the specific host(_id) vulnerability details - the URL states: https://IP_ADDRESS:8834/#/scans/reports/**7**/hosts/**2**/vulnerabilities
and have verified to contain 19506 finding. 

Hence, there should be output to console. 

Does anyone have any idea?

**Comment by aseemsavio** [comment]
All of these functions give back dictionaries. You might want to capture them in a variable, and visualise it's contents (example, printing it). For example,

```
details = nessus.scans.details(7)
print(details)
```

**Comment by stiong-p** [comment]
Thanks a lot, @aseemsavio all good.
