### ISSUE TITLE
ChunkedEncodingError on Specific Scan Exports

### ISSUE THREAD

**Issue by chennin7** [tenable/pyTenable#703]
**Describe the bug**
We have encountered a bug where we get the following error when attempting to export one of our scans using pytenable:
`urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)`. We recently had this issue open with Tenable support. Tenable has resolved the issue when making HTTP calls to the API, but the issue persists when using the pytenable library. Tenable support has instructed us to make this ticket.

**To Reproduce**
The following code results in the error 
```
from tenable.io import TenableIO
from os.path import abspath
accessKey = "<redacted>"
secretKey = "<redacted>"

tio = TenableIO(accessKey, secretKey)
scan = "<redacted>"
EXPORT_FILTERS = [
    ("severity", "eq", "Medium,High,Critical"),
    # Pull the nessus info plugin, used for getting asset details,
    # saves needing a separate call to the assets endpoint
    ("plugin.id", "eq", "19506")
]
with open(abspath("scan.csv"), 'wb+') as fh:
    tio.scans.export(scan, format="csv" ,fobj=fh, filters=EXPORT_FILTERS, filter_type="or")
```
When we attempt an equivalent export using the API and HTTP requests we do not get the error:
create export:
```
import requests
url = "https://cloud.tenable.com/scans/<redacted>/export"

payload = {"format": "csv",
           "filter.0.filter": "severity",
           "filter.0.quality": "eq",
           "filter.0.value": "high",
           "filter.1.filter": "severity",
           "filter.1.quality": "eq",
           "filter.1.value": "critical",
           "filter.2.filter": "severity",
           "filter.2.quality": "eq",
           "filter.2.value": "medium",
           "filter.3.filter": "plugin.id",
           "filter.3.quality": "eq",
           "filter.3.value": "19506",
           "filter.search_type": "or"
}
headers = {
    "accept": "application/json",
    "content-type": "application/json",
    "X-ApiKeys": "accessKey=<redacted>;secretKey=<redacted>"
}

response = requests.post(url, json=payload, headers=headers)

print(response.text)
```
download export:
```
import requests

url = "https://cloud.tenable.com/scans/<redacted>/export/<redacted>/download"

headers = {
    "accept": "application/octet-stream",
    "X-ApiKeys": "accessKey=<redacted>;secretKey=<redacted>"
}

response = requests.get(url, headers=headers)
print(response.text)
```
**Expected behavior**
We expect the export to work in PyTenable without the error.

**System Information (please complete the following information):**
 - OS: MacOS
 - Architecture: 64bit
 - Version: 12.x
 - Memory: 16GB

**Additional context**
It looks like the error only occurs when we have filters on the export. If we remove the filters, the export does not error out.

**Comment by aseemsavio** [comment]
This was a bug in the upstream API, which should be fixed by now. This is unrelated to pyTenable.

**Comment by chennin7** [comment]
Hi @aseemsavio, this issue still occurs when I use the library vs. when I use https requests as I detailed above. I was told by Tenable support to pursue this issue on this project.

**Comment by SteveMcGrath** [comment]
Using the exact same filterset you used in the example, it seems to work fine.  Here is the example code and how i ran it below:

```python
#!/usr/bin/env python
"""
Export Scan Exmaple
"""
from typing import Optional, List, Tuple
from pathlib import Path
from tenable.io import TenableIO
import logging
import typer


def export_scan(scan_id: int,
                report: Optional[Path] = None,
                access_key: Optional[str] = None,
                secret_key: Optional[str] = None,
                filter_type: str = 'and',
                filters: List[str] = typer.Option(
                    [], '--filter', '-f'
                ),
                debug: bool = False
                ):
    """
    Export Scan ID using predefined filters
    """
    filters = [f.split(':') for f in filters]
    if debug:
        # If debug is enabled, then turn on debug logging to log
        # all output to the console.
        logging.basicConfig(level=logging.DEBUG)

    if not report:
        # If no report path is specified, then generate a default path using
        # the scan id in the current working path.
        report = Path(f'scan-{scan_id}.csv')

    tio = TenableIO(access_key=access_key, secret_key=secret_key)
    with report.open('wb') as fobj:
        tio.scans.export(scan_id,
                         fobj=fobj,
                         filters=filters,
                         filter_type=filter_type
                         )


if __name__ == '__main__':
    typer.run(export_scan)
```


```bash
❯ ./example_scan_csv_export.py 9 --debug --report example.csv -f severity:eq:High -f severity:eq:Critical -f severity:eq:Medium -f plugin.id:eq:19506 --filter-type or
DEBUG:tenable.io.TenableIO:Request: {"method": "GET", "url": "https://cloud.tenable.com/filters/scans/reports", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cloud.tenable.com:443
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /filters/scans/reports HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Request: {"method": "POST", "url": "https://cloud.tenable.com/scans/9/export", "params": {}, "body": {"filter.0.filter": "severity", "filter.0.quality": "eq", "filter.0.value": "High", "filter.1.filter": "severity", "filter.1.quality": "eq", "filter.1.value": "Critical", "filter.2.filter": "severity", "filter.2.quality": "eq", "filter.2.value": "Medium", "filter.3.filter": "plugin.id", "filter.3.quality": "eq", "filter.3.value": "19506", "format": "nessus", "chapters": "vuln_by_host", "filter.search_type": "or"}}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "POST /scans/9/export HTTP/1.1" 200 None
DEBUG:tenable.io.TenableIO:Initiated scan export SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus
DEBUG:tenable.io.TenableIO:Request: {"method": "GET", "url": "https://cloud.tenable.com/scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status HTTP/1.1" 200 20
DEBUG:tenable.io.TenableIO:Request: {"method": "GET", "url": "https://cloud.tenable.com/scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status HTTP/1.1" 200 20
DEBUG:tenable.io.TenableIO:Request: {"method": "GET", "url": "https://cloud.tenable.com/scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/status HTTP/1.1" 200 18
DEBUG:tenable.io.TenableIO:Request: {"method": "GET", "url": "https://cloud.tenable.com/scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/download", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://cloud.tenable.com:443 "GET /scans/9/export/SSEF-51bd42a2-22e9-41e3-af67-9b2c4485bb3d-F:5e4299a50e0d095bb7de3dc76f2-nessus/download HTTP/1.1" 200 1922017
```

**Comment by chennin7** [comment]
Hey @SteveMcGrath, this is only happening with some of our larger scan reports. Our smaller scans can export perfectly fine. The original thought was that the pytenable library was attempting to pull some of the corrupted scan results that were related to the API issue on the Tenable side, however we've deleted all generated scan reports and the issue is still happening.

**Comment by SteveMcGrath** [comment]
Without knowing the scan export ID, I can't track what happened internally, however the protocol error is upstream from the library.  The library itself is using requests quite similarly to how you are, the only difference is that its streaming the data to the FileObject instead of downloading the whole response at once.

https://github.com/tenable/pyTenable/blob/master/tenable/io/scans.py#L1002-L1014

We'd need the debug logs from the library at the time of the issue to fully understand whats happening.

**Comment by chennin7** [comment]
Hey @SteveMcGrath  Yeah, so there's a specific set of scans that we need to keep records of outside of the platform in CSV format on a monthly basis. What I provided was a snippet of the actual script we use, but we essentially loop through each of the scans we need stored reports for and run a scan export on each.

I don't think we knew this, but is the recommendation to run exports from the export vulnerabilities api instead of the scan export api? I guess we didn't realize there was large difference or preference for a specific one based on size. 

Once the current incident with scan exports is resolved I will reproduce the bug and try to get the logs for both methods over to y'all through our CSM. 

Thanks

**Comment by SteveMcGrath** [comment]
The export API is based on the aggregate index, not the individual scans.  I'm wondering if the issue your running into is directly related to the fact that you're pulling a large number of scan reports at the same time.

If using the vuln and asset export APIs, you could instead focus on pulling reported based on the assets/tags within the system instead of by scan.  You'd be gaining some additional datapoints as well (a lot of the temporal data is is not stored in the individual scan information, AES/ACR scored are only stored in the aggregate, VPR data, etc.).  It also gived you the ability to pull more data (or less data) based on what you really want.  The scan CSV reports in IO aren't very flexible, and you're limited to what fields are available.  With the vuln and asset exports APIs, you could conceivably export every field associated to the finding (not sure if Excel would like that however).

The vuln and asset export APIs are also async, so they are feeding data in smaller, more manageable chunks for any computer.  The scan exports APIs return the data as a single monolithic response (hence why the library processes the data as a stream, and not as a single object in memory, like your non-pytenable example is doing).  As you can imagine, those files can easily get into the Gigabytes with larger scans.

**Comment by chennin7** [comment]
Got it, appreciate the additional context on this. We're now facing different API issues with the export so we're not able to reproduce the issue for now. I'll circle back around if we see it again. Thanks for the time with this.
