### ISSUE TITLE
tio.exports.vulns no longer returning vulnerabilities

### ISSUE THREAD

**Issue by kwwv** [tenable/pyTenable#706]
**Describe the bug**
We have consistently used the tio.exports.vulns() to retrieve vulnerabilities from our environment. This endpoint has stopped working for us and no longer returns anything. Have other users seen this behavior?

**To Reproduce**
1. Authenticate and then call  tio.exports.vulns() (e.g. `tio.exports.vulns(severity=['Critical', 'High', 'Medium', 'Low'])`
2. An ExportsIterator should be returned. Iterate on this for vulnerability data. Instead an empty iterator is returned. 

Example code:
```
  vulns = tio.exports.vulns(severity=['Critical', 'High', 'Medium', 'Low'])
  q = []
  for x in vulns:
      q.append(x)
```

**Comment by aseemsavio** [comment]
It is possible your export is stuck in the processing state at Tenable.io.

**Comment by kwwv** [comment]
@aseemsavio 

> It is possible your export is stuck in the processing state at Tenable.io. 

This was the issue. That is a recent problem for us. For months it was <1 min to process an export, as of today it's 30+ minutes.
