### ISSUE TITLE
agent_name is not a filterable option

### ISSUE THREAD

**Issue by ButlerJoseph** [tenable/pyTenable#712]
**Describe the bug**
Unable to use the agent_name filter when editting or creating tags.

**To Reproduce**
1. tio.tags.edit(tag_uuid, [("agent_name", "eq", "hostname"]
2. agent_name is not a filterable option

**Expected behavior**
I can use agent_name as a filter on the website frontend and when querying tio.tags.details(tag_uuid) I can see that it is set.

**System Information (please complete the following information):**
 Using pyTenable 1.4.13

**Comment by SteveMcGrath** [comment]
Closing as there was no response

**Comment by asreich** [comment]
@SteveMcGrath Following up on this, I've been trying to apply some filters on tags but am finding that my filters are being categorized as `legacy_filters` and when I save things like "Licensed equals Yes" in the UI, the details show `('is_licensed', 'eq', 'true')` but I can't seem to figure out how I set the non-legacy filters? I'd like to make sure I can filter on Licensed as well but get a similar error to the OP. Any help is appreciated.

**Comment by SteveMcGrath** [comment]
I'd need more context here.  what APIs are you querying, how are you querying them, etc.

**Comment by asreich** [comment]
@SteveMcGrath Yeah my bad, I've filed #768 with background information.
