### ISSUE TITLE
[Tenable.io] Filtering assets workbench by tag category/value throws 400 error

### ISSUE THREAD

**Issue by SiLo222** [tenable/pyTenable#719]
Issue
---
I am attempting to pull all assets that have a specific tag assigned to them from the Assets workbench. When I run the code snippet below, I receive a 400 error in the GET request. The tag category is set to 'NetOps' and the value I want to pull from is set to 'Cisco Network Devices' in the Tenable.io console.

Based on the filters in the URL (see the error message below), it appears to be the correct format according to this example in the Tenable documentation - https://developer.tenable.com/docs/list-assets-for-specific-tag-tio

Note: The 'eq' operator in the documentation above is not a valid filter for tags.

Code Snippet
---
from tenable.io import TenableIO

tio = TenableIO(<my access key>, <my secret key>)

network_assets = tio.workbenches.assets(('tag.NetOps', 'set-has', 'Cisco Network Devices'))
print(network_assets)

Error Message Output
---
[400: GET] https://cloud.tenable.com/workbenches/assets?filter.0.filter=tag.NetOps&filter.0.quality=set-has&filter.0.value=Cisco+Network+Devices&all_fields=full body=b'{"statusCode":400,"error":"Bad Request","message":"Error"}'
Traceback (most recent call last):
 ...
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\tenable\io\workbenches.py", line 104, in assets
    return self._api.get('workbenches/assets', params=query).json()['assets']
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\restfly\session.py", line 603, in get
    return self._req('GET', path, **kwargs)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python310\lib\site-packages\restfly\session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: GET] https://cloud.tenable.com/workbenches/assets?filter.0.filter=tag.NetOps&filter.0.quality=set-has&filter.0.value=Cisco+Network+Devices&all_fields=full body=b'{"statusCode":400,"error":"Bad Request","message":"Error"}'

System Information
---
 - OS: Windows 10 Enterprise
 - Architecture: x64bit
 - Version: 10.0.19045
 - Memory: 32G
 - Python Version: 3.10.2

**Comment by rabbie** [comment]
@SiLo222 I was struggling with finding assets too..

Try this? 

You'll need to pass this function your 'asset_name' as a string (eg: 'Cisco Network Devices')

so to call this:

```
results = find_tag_data_by_asset('NetOps', 'Cisco Networking Devices')
```

```
def find_tag_data_by_asset(search_category: str, search_name: str):
    tag_data = list(tio.tags.list(('category_name','eq',search_category),('value', 'eq', search_name),limit=1))
    if len(tag_data) > 0:
        return tag_data[0]
    else:
        return None
```

**Comment by SteveMcGrath** [comment]
Is there any reason you arent just doing an asset export based on the tag?

```python
for asset in tio.exports.assets(tags=[('NetOps', 'Cisco Networking Devices']):
    print(asset)
```
