### ISSUE TITLE
V3 Assets example documentation is incorrect

### ISSUE THREAD

**Issue by rabbie** [tenable/pyTenable#720]
**Describe the bug**
The "Assets" documentation is incorrect and is missing the 'explore' property.

**To Reproduce**
1. Go to https://pytenable.readthedocs.io/en/stable/api/io/v3/explore/findings.html

**Expected behavior**
The example states:

```tio.v3.assets.search_all(filter=('netbios_name', 'eq', 'SCCM'),```

but should state

```tio.v3.explore.assets.search_all(filter=('netbios_name', 'eq', 'SCCM'),```

**Additional context**

**Comment by SteveMcGrath** [comment]
As the explore APIs have been undocumented, we ask that you please discontinue use.
