### ISSUE TITLE
V3 Findings documentation is missing filter options

### ISSUE THREAD

**Issue by rabbie** [tenable/pyTenable#721]
**Describe the bug**
The finding documentation expplains how to use the filter in the v3 api, but it doesn't list any of the filter keys available for use.

Without these keys, the api only returns the summary information about the asset.

The only way to obtain the keys available for the filter is to inspect requests to the web api through the tenable interface.

**To Reproduce**
1. visit https://pytenable.readthedocs.io/en/stable/api/io/v3/explore/findings.html

**Expected behavior**
Filter key options should be documented, including:

```
["severity",
"definition.name", 
"definition.id", 
"definition.family", 
"port", 
"protocol", 
"definition.vpr.score", 
"definition.cvss3.base_score", 
"origin", 
"asset_cloud_resource.region", 
"asset_cloud_resource.account_id", 
"inventory_live_scan", 
"state", 
"first_observed", 
"last_seen", 
"id", 
"asset.id", 
"asset.name", 
"risk_modified", 
"definition.severity"
]
```

**Comment by SteveMcGrath** [comment]
The V3 APIs have been deprecated upstream and usage should be discontinued.
