### ISSUE TITLE
Hosts Asset

### ISSUE THREAD

**Issue by MAngel666** [tenable/pyTenable#723]
Hi

you have closed both issues with this feature request:

https://github.com/tenable/pyTenable/issues/614 <- this is closed and points to the second one:
https://github.com/tenable/pyTenable/issues/631 <- this is closed as a duplicate of 614

I think it is a misunderstanding? Or it is not planed to implement this feature?

Greetings

**Comment by SteveMcGrath** [comment]
Hosts API was flagged as BETA (And as of 6.1 still is) and as such is not included in the library.  Once the beta flags have been removed from the API, it’ll be considered for inclusion.

**Comment by MAngel666** [comment]
in the last version of API documentation: https://docs.tenable.com/security-center/api/Hosts.htm
it is not marked as BETA anymore.

**Comment by 6illess** [comment]
#614 is still open actually, I think we can continue from there and close this one?

would indeed be nice to include the hosts API-endpoint within pytenable.

**Comment by 6illess** [comment]
@SteveMcGrath  any update on this perhaps? Thanks!

**Comment by aseemsavio** [comment]
@6illess closing this and continuing in #614.
