### ISSUE TITLE
Calling `scan.details(<UUID>)` returns an error. 

### ISSUE THREAD

**Issue by perfectra1n** [tenable/pyTenable#729]
**Describe the bug**
Either I'm losing my mind, or calling a `scan` via `UUID` isn't working as expected.

**To Reproduce**
```py
tio = TenableIO(secrets['TIO_ACCESS_KEY'], secrets['TIO_SECRET_KEY'])
print(tio.scans.details("bd721b19-31c9-4d12-8ba7-abca89aa60f0"))
```

Returns:
```
[400: GET] https://cloud.tenable.com/editor/scan/bd721b19-31c9-4d12-8ba7-abca89aa60f0 body=b'{"error":"Invalid \'id\' field: invalid type \'string\', expecting \'int\' / invalid uuid format"}'
```

However, in the [documentation](https://github.com/tenable/pyTenable/blob/4e31049891f55016168b14ae30d332a965523640/tenable/io/scans.py#L783-L814):
```
        Args:
            scan_id (int or uuid): The unique identifier for the scan.
```

I tried converting it to the Python UUID type, and submitting it:
```py
tio = TenableIO(secrets['TIO_ACCESS_KEY'], secrets['TIO_SECRET_KEY'])
print(tio.scans.details(UUID("bd721b19-31c9-4d12-8ba7-abca89aa60f0")))
```

It still returned an error.

**Expected behavior**
Be able to fetch scan details via UUID: https://developer.tenable.com/reference/scans-details

**System Information (please complete the following information):**
pyTenable 1.4.13

**Comment by SecOpsQC** [comment]
lol I'm crazy or it's the opposite of : https://github.com/tenable/pyTenable/issues/726#issuecomment-1768463544

![image](https://github.com/tenable/pyTenable/assets/96326023/a602654f-efae-4375-89f2-70fcf3945208)

On SC we need to force it to be a string, it was an int before.

**Comment by miguelvalente** [comment]
Any update on this? @SteveMcGrath

**Comment by SteveMcGrath** [comment]
working on this.  working through the massive backlog of PRs and issues.

**Comment by SteveMcGrath** [comment]
> lol I'm crazy or this issue is the exact opposite of : [#726 (comment)](https://github.com/tenable/pyTenable/issues/726#issuecomment-1768463544)
> 
> ""error":"Invalid 'id' field: invalid type 'string', expecting 'int' "
> 
> ![image](https://private-user-images.githubusercontent.com/96326023/276437977-a602654f-efae-4375-89f2-70fcf3945208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjYwODAsIm5iZiI6MTcxODcyNTc4MCwicGF0aCI6Ii85NjMyNjAyMy8yNzY0Mzc5NzctYTYwMjY1NGYtZWZhZS00Mzc1LTg5ZjItNzBmY2YzOTQ1MjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE1NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNWEyNWYyZDMzOTYzMjYwNWFhYjc3MzczY2ZkNGVlNjU2NTFlNDFiYjliM2M2MTNiYWRmYjFmMzlmMDdlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DpZrOvjPQZCfVsvj3tCOFDpxFF8bInHNfsrCTe4Srzw)
> 
> On SC we need to force it to be a string, it was an int before.

This is actually a very different issue thanks to some error handling that was erroneously introduced into the Tenable SecurityCenter API that required the integers to be string formatted.

As for the issue relating to the TVM scan.details method, that method routed through the editor API, which currently only accepts an integer value.

scans.details attempts to recreate the config of the scan using the editor API: https://pytenable.readthedocs.io/en/stable/api/io/scans.html#tenable.io.scans.ScansAPI.details

the API's "scan details" is actually a truncated JSON report of the last scan that was run with some config data thrown in as well.  To use that API, refer to the scans.results method instead.

https://pytenable.readthedocs.io/en/stable/api/io/scans.html#tenable.io.scans.ScansAPI.results

**Comment by SteveMcGrath** [comment]
yes, in the SDK/library re linked that API to "results" as its a more correct name to what it's doing.  "details" is a term we reserve for the configuration of that object.  The Nessus and TVM `GET /scans/<ID>` call currently does not conform to REST guidelines, so we try to remap it to the appropriate action name.
