### ISSUE TITLE
Analysis API Error When Referencing Scan ID

### ISSUE THREAD

**Issue by fib0nacci** [tenable/pyTenable#73]
**Describe the bug**
Attempting to iterate through the analysis results of any individual scan produces the following error:
APIError: None:403 {"type":"regular","response":"","error_code":142,"error_msg":"Please specify a view for the individual data source.\n","warnings":[],"timestamp":1552330629}

**To Reproduce**
Note, the values used in the following examples are generic.
Run the following lines:

```
from tenable.sc import TenableSC
sc = TenableSC('sc.mycompany.com')
sc.login('username','password')
```
Then run either of the following:
```
analysisResults = sc.analysis.scan(1234)
```
OR
```
analysisResults = sc.analysis.vulns(scan_id=1234)
```
Then attempt to iterate through the results:
```
for vuln in analysisResults:
     print(vuln)
```

**Expected behavior**
A printout of each vulnerability from the referenced analysis should be shown on the screen.

**System Information (please complete the following information):**
 - OS: Ubuntu
 - Architecture 64bit
 - Version 16.04.1

**Additional context**
Based on the error returned, and Tenable's API documentation [here](https://docs.tenable.com/sccv/api/Analysis.html), these calls are missing a value for the **view** parameter, which must be included when specifying a **sourceType** of 'individual,' which both of the referenced methods are doing.

**Comment by SteveMcGrath** [comment]
The commit alleviates the problem, however I'll be waiting to release a new version until I can at least test out what I have been working on.  In the meantime you can always pull directly from the github repo as mentioned on the readme.

**Comment by d78ui98** [comment]
Try changing sourcetype from `individual` to `cumulative`
worked for me.
