### ISSUE TITLE
Tag creation method does not accurately reflect the option in the Tag API

### ISSUE THREAD

**Issue by dworkman1** [tenable/pyTenable#732]
**Describe the bug**
Currently when trying to create a tag in Tenable using the AWS Region filter I cannot use all of the regions that are currently in the Tenable UI. I instead get the following error: (<class 'restfly.errors.UnexpectedValueError'>, 'filter_value has value of me-central-1. Expected one of ap-south-1,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,sa-east-1,eu-central-1,eu-west-1,eu-west-2,eu-west-3,ca-central-1,us-east-1,us-east-2,us-west-1,us-west-2', <traceback object at 0x103c043c0>)

**To Reproduce**
1. Using create tags method (ie. tio.tags.create) submit a request with a filter trying to to set "AWS Region" (using the proper name of the filter in the SDK) to "me-central-1".
2. You will receive the error in the bug description.

**Expected behavior**
A tag is created like happens in the API.

**System Information (please complete the following information):**
 - System agnostic (this happens in both Windows and Linux).

**Comment by SteveMcGrath** [comment]
Sadly this is an issue with the upstream API within TVM itself.
