### ISSUE TITLE
Tenablesc 6.2.0 and API recordkeeping error.

### ISSUE THREAD

**Issue by tinomhp** [tenable/pyTenable#736]
Hello, I urgently need an idea.
After the update to Tenable.sc 6.2.0 we always get this error when creating reports via pyTeanable.

API recordkeeping error. api_total=None, api_count=None, page_size=0, iter_total=51697

What could be the reason?

Greetings Tino

**Comment by SteveMcGrath** [comment]
can you give more details?  whats the call being made?  whats the full response?

**Comment by SteveMcGrath** [comment]
Closed, lack of input
