### ISSUE TITLE
Documentation and implementation differ when creating a scan with credentials.

### ISSUE THREAD

**Issue by SaltySolomon** [tenable/pyTenable#74]
**Describe the bug**
I have encountered the bug using the part of the libary to talk with nessus.sc, the following bug report is about this, not sure about the other sub parts.

The documentation and the actual code for adding Credentials to Scans are different. The docs say you have to use the parameter "Credentials" to add credentials, but in the code its "Creds".

**To Reproduce**
Attempt to create a scan with credentials and follow the documentation and use the parameter Credentials. This will create a scan without an credential attached.

**Expected behavior**
A scan with credentials should be created

**System Information (please complete the following information):**
 - Tested with the latest version of the Library and nessus.sc

**Comment by SaltySolomon** [comment]
Wow, thanks for the quick response!

**Comment by SteveMcGrath** [comment]
Thanks for noting the doc issue.  I try to keep the parameter names for what the module uses for naturalization different from what the API uses directly.  This means that you should be able to generally pass the raw API call in the keyword arguments.  unfortunately i don't always catch this little things when im in the zone coding them up ;)

If you see anything else, just fire off another issue and I'll run it down as soon as I'm able to ;)
