### ISSUE TITLE
{"error":"API is not available"}

### ISSUE THREAD

**Issue by talsh5528** [tenable/pyTenable#757]
using Nessus expert(trial)
try to trigger the scan using the SDK.
get error 
{"error":"API is not available"}.
I check the API doc, and i see that:
<img width="364" alt="image" src="https://github.com/tenable/pyTenable/assets/118183238/90f9ebaa-e6c9-4999-b488-4f30e69e0c52">
I don't understand, when this API is available, and how I can use that.

**Comment by SteveMcGrath** [comment]
I would recommend contacting Tenable support for this one, as it doesn't have anything to do with the library itself, but rather the Nessus product.

In general, however, the scan launch APIs aren't available within Nessus Pro & Expert, and instead the focus is around the apis necessary to download the completed reports.  If you're looking to automate scanning for an organization, the general recommendation is to look at either Tenable Security Center or Tenable Vulnerability Management as they are specifically designed to handle data state, asset tracking, etc.
