### ISSUE TITLE
SecurityCenter scans.create(max_time: int) issue on value

### ISSUE THREAD

**Issue by ve2tmq** [tenable/pyTenable#760]
Max_time in API use hours, but pytenable documentation indicate in seconds.  I tried to create scan with max_time=1 and see on web SecurityCenter, I got max duration = 1 hour.

In documentation it's write: "max_time ([int](https://docs.python.org/3/library/functions.html#int), optional) – The maximum amount of time that the scan may run in seconds. 0 or less for unlimited. The default is 3600 seconds."

In reality, it's not on seconds, but in hours.
I use SecurityCenter version 6.1.0

**To Reproduce**

from tenable.sc import TenableSC
import configparser
import warnings
warnings.filterwarnings("ignore")

class connectSC:
    SC = dict()
    uri = dict()

    def __init__(self, filename = 'connectSC.cfg'):
        cfg = configparser.ConfigParser()
        cfg.read(filename)
        sections = cfg.sections()
        for section in sections:
            self.uri[section] = cfg[section]['uri']
            self.SC[section] = TenableSC(self.uri[section])
            keys = list()
            for key in cfg[section]:
                keys.append(key)

            if 'access_key' in keys and 'secret_key' in keys:
                self.SC[section].login(access_key=cfg[section]['access_key'], secret_key=cfg[section]['secret_key'])
            elif 'username' in keys and 'password' in keys:
                self.SC[section].login(username=cfg[section]['username'], password=cfg[section]['password'])

sc = connectSC()
sc.SC['my_org'].scans.create(name='Test', repo=6, max_time=1, policy_id=1000290, asset_lists=['1978'])

now check on web SecurityCenter the scan Test max duration is 1 hour.  If I set to 3600, it's "Nothing Selected"

**Comment by aseemsavio** [comment]
@ve2tmq  pyTenable is inline with the public documentation for the [POST /scan API](https://docs.tenable.com/security-center/api/Scan.htm#[data-colorid=n2lag17te4]color:#333333%20html[data-color-mode=dark]%20[data-colorid=n2lag17te4]color:#cccccc[data-colorid=h2qn50612y]color:#3d3d3d%20html[data-color-mode=dark]%20[data-colorid=h2qn50612y]color:#c2c2c2[data-colorid=dm0shrh2jq]color:#3d3d3d%20html[data-color-mode=dark]%20[data-colorid=dm0shrh2jq]color:#c2c2c2scan_POST). I'll get back to you after getting clarity on the API side of things.

**Comment by aseemsavio** [comment]
@ve2tmq - `max_time` should always accompany `inactivity_timeout`. `max_time` should be in multiples of 3600, and `inactivity_timeout` must be between 3600 and `max_time`.

**Comment by ve2tmq** [comment]
Hi

I understand that, but my observations indicates the unit should not be in seconds but in hours.  The function works, the issue is in the doc.  The doc is worng.
