### ISSUE TITLE
Let pyTenable retry requests when the API responds with retriable status codes

### ISSUE THREAD

**Issue by aseemsavio** [tenable/pyTenable#774]
**Is your feature request related to a problem? Please describe.**
Currently, pyTenable doesn't seem to re-try requests when the VM APIs respond with a re-triable status code (503 for example)

**Describe the solution you'd like**
The HTTP client used by pyTenable should retry requests, employing exponential back off when faced with a re-triable status code.

**Describe alternatives you've considered**
Re-trying at the application level. But this functionality at the library is more elegant than the alternative.

**Additional context**
The Compliance Export API gives intermittent 503 status codes. A retry mechanism at pyTenable would be helpful for this and other APIs that intermittently give re-triable status codes due to temporary infra related issues.

**Comment by aseemsavio** [comment]
Looks like pyTenable does this without logging. Just found the code in `sessions.py` in the `restfly` library.
We have `_retries = 5` in `platform.py` in pyTenable.

**Comment by SteveMcGrath** [comment]
If debug logging is turned on, the retries should be returned.
