### ISSUE TITLE
Issue with sc.credentials.edit function for 'cyberark' authType credentials in Tenable.sc

### ISSUE THREAD

**Issue by devepatil** [tenable/pyTenable#775]
**Description**
I can't get sc.credentials.edit function to edit  'cyberark' authType credential to update/edit 'pam_client_cert' and  'pam_private_key' typeFields. It produce following error while attempting to edit;
"
[403: PATCH] https://x.x.x.x:443/rest/credential/1000016 body=b'{"type":"regular","response":"","error_code":106,"error_msg":"Modification of Credential #1000016 during Edit Credential failed.\\nError moving CyberArk client cert to application storage.\\n","warnings":[],"timestamp":1715500762}\n'
"
The same sc.credentials.edit function work as expected editing ' vault_cyberark_client_cert' and 'vault_cyberark_private_key' typeFields for 'cyberarkLagacy' authType. 

**To Reproduce**

1. Login and authenticate
2. Identify the credentials of 'cyberark' authType for selected pam_safe
3. Get the input for 'pam_client_cert' and 'pam_private_key' files.
4. Update credentials for 'cyberark' AuthType for provided 'pam_client_cert' and 'pam_private_key' files using the code snippet below,

    for credential in cyberark_credentials:
        credential_id = credential['id']
        try:
            # Update the credential
            sc.credentials.edit(
                credential_id,
                pam_client_cert=client_cert_path,
                pam_private_key=private_key_path
            )
            updated_credentials.append(credential['name'])
        except Exception as e:
            failed_credentials.append((credential['name'], str(e)))

    return updated_credentials, failed_credentials

**Expected behavior**
I should be able to edit the credentials of 'cyberark' authType same as of 'cyberarkLegacy' authType.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows 11
 - Architecture: 64bit
 - Version: 22H2
 - Memory: 32GB

**Additional context**
Attached the python script used for this testing. The main intent of the script is to list and edit cyberark (cyberarkLegacy, cyberark) creds in Tenable.sc of specific cyberark safe for updating renewed pam/cyberark client certificate key pair used for mutual authentication. Given the multitude of credentials we possess, manually updating the key pair via the Web UI is a laborious task. Hence, trying to build this script to simplify the 
[CYB_Cred_update_v3.5.1.txt](https://github.com/tenable/pyTenable/files/15302285/CYB_Cred_update_v3.5.1.txt)
process.

**Comment by SteveMcGrath** [comment]
pam_client_cert && pam_private_key are files, and need to be uploaded by the files API.

https://pytenable.readthedocs.io/en/stable/api/sc/files.html#tenable.sc.files.FileAPI.upload

Pass the returned filename into those parameters and it should work.

As a side note, I would recommend a few little things that may help you with your script.

1. Don't use the login/logout method for api keys, just pass all the parameters at instantiation.  The use of login is mostly there for backwards compatibility at this point.
2. There isn't any need to pull TSC_URL, TSC_ACCESS_KEY, or TSC_SECRET_KEY.  The library will pull those automatically for you.
3. You can ask for the typeFields field in the credential list API, which would mean you wouldn't need to hit the details API for every cred.
4. You could also dramatically reduce your main function if you embraced something like typer or click for the CLI management.  Both are awesome libraries, I have a heavy preference to typer myself.
