### ISSUE TITLE
tio.was.export forget endpoint in documentation ?

### ISSUE THREAD

**Issue by kalidor** [tenable/pyTenable#797]
**Describe the bug**
I didn't find the documentation related to an endpoint used by the SDK, and i fear a potential bug.

**To Reproduce**
- requesting an export using `tio.was.export`
example: 
```python
for export in tio.was.export(
        single_filter=(
            "scans_status",
            "contains",
            ["completed"],
        )
):
    # add logic here
```
- see requests targeting `/was/v2/scans/{scan.id}/vulnerabilities/by-targets/search?limit=200&offset=0`

I looked in the documentation (https://developer.tenable.com/reference/was-v2-scans-search) and I didn't find `by-targets` in any was related endpoint.

**System Information (please complete the following information):**
 - Version 1.4.22

**Comment by SteveMcGrath** [comment]
Resolved as part of docs cleanup and TIE addition

**Comment by kalidor** [comment]
I'm sorry, I think closing this is a mistake.
I checked last few commits and i don't see any relation between my ticket on TIO WAS and TIE documentation.
