### ISSUE TITLE
Version 1.4.2 package has incorrect dependency configuration in setup.py

### ISSUE THREAD

**Issue by sreelathasankaranarayanan** [tenable/pyTenable#798]
**Describe the bug**
Version 1.4.2 package has incorrect dependency configuration in setup.py, this is causing errors in projects that use pytenable as a dependency and with pip 24.0 dependency resolver this problem is hard to avoid as it seems to download older versions of dependencies to find the best compatibility match.

**To Reproduce**
2. Call  '....'
3. Do '....'

Run pip install pytenable==1.4.2

**Expected behavior**
The package should install successfully without errors in setup.py

**Screenshots**

Collecting pytenable==1.4.2
  Using cached https://na.artifactory.swg-devops.com/artifactory/api/pypi/wcp-auditree-pypi-virtual/packages/packages/8f/1e/96d67f77c8dd714e9194a766c9ea4784053a8d7370a2a8ed4b4e632b0585/pyTenable-1.4.2.tar.gz (161 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in pyTenable setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          typing-extensions>=3.10.0.2dataclasses>=0.8;python_version=="3.6"
                           ~~~~~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**System Information (please complete the following information):**
 - OS: [e.g. MacOS]
 - Architecture [e.g. 64bit, 32bit]
 - Version [e.g. 2.7.9]
 - Memory [e.g. 4G]

MacOS, Ubuntu

**Additional context**
Add any other context about the problem here.

**Comment by nkeuning** [comment]
Python 3.6 isnt supported.  
FYI - 3.7 support will be dropped in the next few months as well, it is EOL as well, but waiting on a few integration partners to upgrade. 3.8 will come shortly after that when it becomes EOL.

**Comment by sreelathasankaranarayanan** [comment]
@nkeuning can you check the setup.py for version 1.4.2 if it has a incorrect syntax as reported in the error? 

> error in pyTenable setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)

Just checking if this is something that can be corrected.

**Comment by jftanner** [comment]
The [config where the error occurs](https://github.com/tenable/pyTenable/blame/1.4.2/setup.py#L50-L51) was unchanged for three years as of v1.4.2 (and is still the same today on `master`), so I think it's probably safe to assume that this package isn't the problem. If `setup.py` were wrong, the issue wouldn't have appeared only today.

**Comment by nkeuning** [comment]
This builds fine for me locally. 
What version of python are you using? 
Can you try building without your artifactory as a pip cache? What happens then?

**Comment by nkeuning** [comment]
Also confirmed with python 3.12.2 and pip==24 that pip install pytenable==1.4.22 works. 

Actually are you trying to install 1.4.2 or 1.4.22(latests)? Just realized your title says 1.4.2 as well as cmd you posted.

**Comment by jftanner** [comment]
There was a minor syntax error introduced three years ago, just before v1.4.2: https://github.com/tenable/pyTenable/commit/a0e0d7ce409704001fc893d9a646e305d19eddf0

It appears that Python 3.12 w/ pip 24.0 seems to handle it gracefully, but Python versions older than that don't.

**Comment by nkeuning** [comment]
1.4.2 doesnt work and from 12/21. 1.4.22 is weeks old and works correctly.  Please use latest version.

**Comment by jftanner** [comment]
> Actually are you trying to install 1.4.2

Yes, 1.4.2. Though, the syntax error is present in every version since then as well. Newer versions of Python just don't seem to mind.

**Comment by sreelathasankaranarayanan** [comment]
@nkeuning 1.4.22 does not have a problem, 1.4.2 has the problem. Due to pip 24.0's feature to backtrack dependency versions we see that 1.4.2 is attempted to be downloaded and this is causing an issue.

**Comment by sreelathasankaranarayanan** [comment]
The incorrect code was fixed in this commit - https://github.com/tenable/pyTenable/commit/c3a777d94c7b2e078ebea28712eef7fac6985981

**Comment by jftanner** [comment]
Ugh. You're absolutely right. Don't debug at 1:30am. 🤣 
Please ignore everything I've said.

**Comment by nkeuning** [comment]
We've all been there! Have a good night!

**Comment by sreelathasankaranarayanan** [comment]
@nkeuning any thoughts on yanking version 1.4.2 or fixing the setup.py?

**Comment by nkeuning** [comment]
Personally see all these sails version on GitHub and pypi I'd like to yank a bunch of old stuff.  Will need to chat with @SteveMcGrath about this when he is back.

**Comment by sreelathasankaranarayanan** [comment]
Thanks @nkeuning that would help if we could yank atleast the one version that has a know error.
