### ISSUE TITLE
Removal of v1.4.2 as it has a broken setup.cfg, causing errors due to this version being fetched during dependency resolution by pip v24.0

### ISSUE THREAD

**Issue by sreelathasankaranarayanan** [tenable/pyTenable#799]
**Describe the bug**
Removal of v1.4.2 as it has a broken setup.cfg, causing errors due to this version being fetched during dependency resolution by pip v24.0. Pinning of the package to latest version is not helping due other errors in dependency resolution.  This package is not useful especially given its faulty setup.cfg file, is it possible to remove this from PyPi so that it is not available during the dependency resolution runs?

Related issue - https://github.com/tenable/pyTenable/issues/798
**To Reproduce**
2. Call  '....'
3. Do '....'

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. MacOS]
 - Architecture [e.g. 64bit, 32bit]
 - Version [e.g. 2.7.9]
 - Memory [e.g. 4G]

**Additional context**

**Comment by SteveMcGrath** [comment]
1.4.2 removed, however please consider pinning to a more recent version.
