### ISSUE TITLE
Bug with the parameter "last_modified" in the method "list" of tenable.io scans.py

### ISSUE THREAD

**Issue by megavexus** [tenable/pyTenable#810]
**Describe the bug**
Sin this change, a few weeks ago, the method "list" of "scans.py" of "Tenable IO" is not working with the parameter "last_modified".
![imagen](https://github.com/tenable/pyTenable/assets/5712587/c05bd386-d7f9-4f6c-87c9-a1dedfa48c18)

**To Reproduce**
1. Call the method "list" of scans.py of the library "io"
2. Add a paramether with a datetime:
```python
list_scans = api.scans.list(
            last_modified=datetime.today()
)
```
4. See error: 
```
  File "XXXX/site-packages/tenable/io/scans.py", line 1205, in list
    lm = int(time.mktime(last_modified).timetuple())
AttributeError: 'float' object has no attribute 'timetuple'
```

**Expected behavior**

**System Information (please complete the following information):**
 - OS: Ubuntu budgie 
 - Architecture: 64bit
 - Version 22.04
 - Memory 16GB

**Additional context**
To fix it, you only have to replace the affected line with:
```python
     lm = int(time.mktime(start_time.timetuple()))
```

**Comment by SteveMcGrath** [comment]
As you are already aware of the issue and the fix, do you want to file a PR to fix as well?
