### ISSUE TITLE
Security Center Plus API terminates before all data is returned

### ISSUE THREAD

**Issue by ewing-bpl** [tenable/pyTenable#823]
**Describe the bug**

We were pulling some data from the Security Center Plus API using pyTenable version 1.5.0. We got the following error:

> API Recordkeeping error. api_total=127255, api_count=10000.052631578947, page_size=10001, iter_total=1

The data pull would stop at that point.

Here's a debug line that shows you what API call we were using:

>2024-07-30 15:04:15,859 DEBUG Request: {"method": "POST", "url": "https://redacted.net:443/rest/analysis", "params": {}, "body": {"type": "vuln", "sourceType": "cumulative", "query": {"tool": "vulndetails", "type": "vuln", "filters": [{"filterName": "lastSeen", "operator": "=", "value": "0:180"}, {"filterName": "iavmID", "operator": "=", "value": "A-,B-"}, {"filterName": "xref", "operator": "!=", "value": "IAVA|*-S,IAVB|*-S"}, {"filterName": "wasVuln", "operator": "=", "value": "excludeWas"}], "startOffset": 10000, "endOffset": 20000}}}

self._limit is set to 10000, so it's odd that the API was returning 10001 records. It also seems strange that the returnedRecords field is not an integer.

Here's part of the JSON data returned from the API call:

```
{'type': 'regular',
 'response': {'totalRecords': '127255',
              'returnedRecords': 10000.052631578947,
              'startOffset': '0',
              'endOffset': '10000',
```

We are running:

Security Center Plus
Version: 6.3.0
Server Build ID: 20240212225233

**System Information (please complete the following information):**
 - OS: Alpine Linux 3.19.0, MacOS 13.6.7
 - Architecture 64bit
 - Memory 32Gb

**Comment by SteveMcGrath** [comment]
This is definitely interesting...  Have you filed an issue with Tenable support as well?

**Comment by ewing-bpl** [comment]
> This is definitely interesting... Have you filed an issue with Tenable support as well?

Not yet, but we plan to do so today.

**Comment by SteveMcGrath** [comment]
when you do so, can you please also email me the ticket info as well smcgrath _at_ tenable.com.

**Comment by ewing-bpl** [comment]
Trying the new code out now. I no longer have access to a malfunctioning SecuityCenter server, but it appears to me the fix in commit 6c7c8a16 doesn't solve the problem I was having.

Here's the situation I had:

``` 
total_records = 127255
records = 10000.052631578947
page_size = 10001
self.limit = 10000
```

The code in my pull request (824) sets `self.total` to 127255, which allows `AnalysisResultsIterator` to continue pulling pages of data until it's gotten all the data. The code in commit 6c7c8a16 sets it to `self.count + self._limit + 1`, which is the same as what happened in the code before commit 6c7c8a16. This causes `AnalysisResultsIterator` to stop after reading the first page of results.

**Comment by SteveMcGrath** [comment]
I'm hesitant to make a change here that may impact other things and the issue does sound like something is unhappy with the SC console itself.

I would recommend using smaller page sizes and see if the issue continues, also I would recommend contacting Tenable support to see if they can troubleshoot whats happening to the SC instance itself.

**Comment by ewing-bpl** [comment]
Understood. And you're right: this is a problem with SC. We have reported it to Tenable, but I haven't heard anything back so far.

We plan to continue using our patch. I hope was hoping not to have to maintain it long-term, but it's not that big of a deal. 

Thanks for your work on this issue.
