### ISSUE TITLE
nessus api error

### ISSUE THREAD

**Issue by BeneficialCode** [tenable/pyTenable#840]
**Describe the bug**
The nessus scans create api don't work correctly. It cannot create a scan.

**To Reproduce**
```
nessus = Nessus(url=url,access_key=access_key, secret_key=secret_key)
resp = nessus.editor.template_list('scan')
print(resp)
uuid = resp[1]['uuid']
resp = nessus.scans.create(uuid=uuid,
                           settings = {
                            'name': 'test scan python',
                            'enabled': True,
                            'text_targets': '192.168.65.1',
                            'agent_group_id': []
                        })
print(resp)
```

**Expected behavior**
nessus.scans.create's response is correct.

**Bugs**
Requests Library Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Requests Library Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**System Information (please complete the following information):**
 - OS: CentOS 7
 - Architecture: 64bit
 - Version: CentOS-7-x86_64-Everything-2009
 - Memory: 6G

**Additional context**
Version10.8.3  LINUX

**Comment by SteveMcGrath** [comment]
Please note that most Nessus installs will have this API disabled, which is likely the issue.

**Comment by SteveMcGrath** [comment]
The scan launch API isn't available for Nessus Pro & Expert.
