### ISSUE TITLE
Unable to list scanners 'ScannerAPI.list()' based on specific fields (authType,certInfo).

### ISSUE THREAD

**Issue by devepatil** [tenable/pyTenable#844]
I'm looking for assistance with a use case involving pyTenable. I have multiple scanners connected to Tenable SC, mostly using authType as "certificate" with the same client certificate for mutual authentication. However, whenever the client certificate gets renewed, I have to manually update each scanner with the new certificate.

I want to automate this process using the pyTenable Scanner and file endpoints. I started by trying to identify and list the scanners that meet the condition of having authType: certificate and where the CN in certInfo contains a specific certificate. Unfortunately, I'm consistently encountering an issue where authType is returning None, and I’m unable to find any scanners using the certificate as the authType, despite having over 70 scanners connected to SC with this configuration.

Here’s the code I’ve been working with:

import os
from tenable.sc import TenableSC

# Set up your API keys
os.environ['TSC_ACCESS_KEY'] = 'xxxx'
os.environ['TSC_SECRET_KEY'] = 'xxxx'

# Instantiate a TenableSC object
sc = TenableSC('xxxxx', port=443)
sc.login(access_key='xxxx', secret_key='xxxx')

# Function to list SSL certificate-authenticated scanners with specific CN in certInfo
def list_filtered_scanners(target_cn):
    all_scanners = sc.scanners.list()

    # List to store the names of the filtered scanners
    filtered_scanner_names = []

    for scanner in all_scanners:
        # Check if the 'authType' key exists and if it is 'certificate'
        if 'authType' in scanner and scanner['authType'] == 'certificate':
            cert_info = scanner.get('certInfo', {})
            # Check if 'subject' exists in certInfo and 'CN' is present
            if 'subject' in cert_info and 'CN' in cert_info['subject']:
                # Check if the specified CN is in the certInfo subject
                if target_cn in cert_info['subject']['CN']:
                    filtered_scanner_names.append(scanner['name'])

    return filtered_scanner_names

# Main function
def main():
    target_cn = 'clientcert.com'  # Specify the CN to search for

    # List scanners that meet the conditions
    filtered_scanners = list_filtered_scanners(target_cn)

    if not filtered_scanners:
        print("No scanners found with the specified authentication type and CN.")
    else:
        print("Scanners with authType 'certificate' and CN containing specified value:")
        for name in filtered_scanners:
            print(f" - {name}")

# Execute the main function
if __name__ == "__main__":
    main()

I would really appreciate it if someone could help me identify the problem and fix the code. Thanks in advance for your assistance!

**Comment by SteveMcGrath** [comment]
For reference (as I have never deployed a scanner with a cert auth) can you post some example responses?

**Comment by devepatil** [comment]
Using this function to list all the scanners with all the attributes, 

def list_all_scanners():
    all_scanners = sc.scanners.list()  # This fetches all scanners

    if not all_scanners:
        print("No scanners found.")
        return

    # Print attributes of each scanner
    for scanner in all_scanners:
        scanner_id = scanner['id']
        scanner_details = sc.scanners.details(scanner_id)  # Get details for each scanner

        print("\nAttributes of Scanner:")
        for key, value in scanner_details.items():
            print(f"{key}: {value}")

It produce all listed scanner with all attributes, following is sample redacted scanner detail using certificate as authType

Attributes of Scanner:
id: 2
name: Test Scanner
description:
ip: testscanner.com
port: 8834
sciScannerID: 1
useProxy: false
enabled: true
verifyHost: false
managePlugins: false
authType: certificate
nessusType: Nessus Scanner (SC)
cert: scfile_Li5asH
username:
password: None
agentCapable: false
wasCapable: false
accessKey: None
secretKey: None
version: 10.8.3
webVersion: 10.8.3 (Build 10)
admin: true
msp: false
numScans: 1
numHosts: 2
numSessions: 1
numTCPSessions: 6
loadAvg: 0.12
uptime: 256188
status: 1
statusMessage: None
pluginSet: 202410271341
loadedPluginSet: 202410271341
wasLoadedPluginSet: None
licenseFeatures: {"features":{"policies":true,"report":true,"remote_link":true,"cluster":false,"users":true,"vpr":false,"offline":true,"plugin_rules":true,"api":true,"scan_api":true,"folders":true,"local_scanner":true,"logs":false,"smtp":true},"type":"sc_scanner","expiration_date":0,"ips":2147483647,"restricted":true,"agents":0,"mode":1048578,"scanners":0,"scanners_used":0,"agents_used":0,"name":"Nessus Scanner (SC)"}
serverUUID: 938ba33b-e74c-5b98-7fd4-47285966644059e7c636b01d9c69
createdTime: 1605481148
modifiedTime: 1729614020
zones: [{'id': '121', 'name': 'WORKLOAD', 'description': '', 'uuid': '4FEDVAE9-9B7E-4B3C-59CA-2E3409C3117A'}, {'id': '122', 'name': 'WORKLOAD2', 'description': '', 'uuid': '15B0B528-92E4-4D63-AFA7-516BF9285764'}, {'id': '137', 'name': 'CNT', 'description': '', 'uuid': '0FD473DA-7C19-49D3-BE3E-1344A0FAAE17'}, {'id': '138', 'name': 'CNT2', 'description': '', 'uuid': '4DCF165A-4194-40AF-A433-8209777E2C60'}, {'id': '143', 'name': 'AWS', 'description': 'Development:\n\nDMD VPC: 13.121.145.0/20\nISD VPC: 12.121.127.0/20\n\n\nNon Prod:\n\nDMD VPC: 13.210.31.0/19\n13.210.96.0/19\nISD VPC: 13.017.128.0/17\n13.108.128.0/17\n13.109.128.0/17', 'uuid': 'C403C602-38DC-4260-8E12-1E405FB25A7E'}, {'id': '156', 'name': 'WIB', 'description': 'Legacy', 'uuid': 'AB5AE4D7-3C6E-467E-BBEB-E1C4794007E6'}, {'id': '165', 'name': 'EDGE', 'description': 'test', 'uuid': 'C5B8FC3D-4174-4E38-8CAC-B1C8119DAF50'}]
nessusManagerOrgs: []
eolDate: -1
eouDate: -1
certInfo: {'name': '/C=US/ST=ST/L=NY/O=Corporation/OU=SDS/CN=testscanner.com', 'subject': {'C': 'US', 'ST': 'ST', 'L': 'NY', 'O': 'Corporation', 'OU': 'SDS', 'CN': 'testscanner.com'}, 'hash': '215bb262', 'issuer': {'C': 'US', 'ST': 'ST', 'L': 'NY', 'O': 'Corporation', 'OU': 'Certificates Services', 'CN': 'SSL CA'}, 'version': 2, 'serialNumber': '0x1F0005AFCF69CC2F70B014134900000001DCFC', 'serialNumberHex': '1F0005AFCF69CC2F70B014134900000001DCFC', 'validFrom': '240227005515Z', 'validTo': '250226000857Z', 'validFrom_time_t': 1708995315, 'validTo_time_t': 1740528537, 'signatureTypeSN': 'RSA-SHA256', 'signatureTypeLN': 'sha256WithRSAEncryption', 'signatureTypeNID': 668, 'purposes': {'1': [True, False, 'sslclient'], '2': [False, False, 'sslserver'], '3': [False, False, 'nssslserver'], '4': [False, False, 'smimesign'], '5': [False, False, 'smimeencrypt'], '6': [False, False, 'crlsign'], '7': [True, True, 'any'], '8': [True, False, 'ocsphelper'], '9': [False, False, 'timestampsign']}, 'extensions': {'keyUsage': 'Digital Signature, Key Encipherment', 'extendedKeyUsage': 'TLS Web Client Authentication', 'subjectAltName': 'DNS:testscanner.com', 'subjectKeyIdentifier': 'FC:98:98:D3:BF:D3:9B:FB:DC:73:F9:E0:AD:90:5A:8B:4A:0C:E5:BC', 'authorityKeyIdentifier': '5D:7E:DF:1A:56:CE:03:84:DE:11:6C:A5:5B:B2:DF:9E:28:DC:80:66', 'crlDistributionPoints': 'Full Name:\n  URI:http://usca.pki2.srv.com/SDP/CD%20SHA2%20SSL%20CA%20NY/USc%20SHA2%20SSL%20CA%20NY.crl\n  URI:ldap:///CN=US%20SHA2%20SSL%20CA%20NY,CN=st2004sp1765,CN=CDP,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=US,DC=NY,DC=com,DC=us?certificateRevocationList?base?objectClass=cRLDistributionPoint', 'authorityInfoAccess': 'CA Issuers - URI:http://us.pki2.srv.com/AIA/US%20SHA2%20SSL%20CA%20NY/US%20SHA2%20SSL%20CA%20NY.crt\nCA Issuers - URI:ldap:///CN=US%20SHA2%20SSL%20CA%20NY,CN=AIA,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=wbcau,DC=US,DC=com,DC=au?cACertificate?base?objectClass=certificationAuthority', 'basicConstraints': 'CA:FALSE', '1.3.6.1.4.1.311.21.7': '0-\x06%+\x06\x01\x04\x01 7\x15\x08 \u07b3% \x0b э)   z \x13 X   \x02   R\x02\x01d\x02\x01\r', '1.3.6.1.4.1.311.21.10': '0\x0c0\n\x06\x08+\x06\x01\x05\x05\x07\x03\x02', 'certificatePolicies': 'Policy: 1.3.6.1.4.1.3603.1000.2.3\n  CPS: http://uspki2.srv.US.com/USPolicy/WBC_CPS2.pdf\nPolicy: 1.3.6.1.4.1.3603.1000.1.1.4\n  CPS: http://uspki2.srv.US.com/USPolicy/WBC_CP2.pdf\nPolicy: 1.3.6.1.4.1.3603.1000.1.1.1\n  CPS: http://uspki.srv.US.com/USPolicy/WBC_ITSP.pdf'}, 'scIssuer': 'C=AU, ST=NSW, L=Sydney, O=US Corporation, OU=Digital Certificates Security Services, CN=US SHA2 SSL CA NY', 'scNotBefore': 'Tue, 27 Feb 2024 00:55:15 GMT', 'scNotAfter': 'Wed, 26 Feb 2025 00:08:57 GMT', 'scSubjectDN': 'C=AU, ST=NSW, L=Sydney, O=US Banking Corporation, OU=SPS, CN=a00892scanadminprod.US.com'}
SCI: {'id': '1', 'name': 'Local', 'description': 'This Tenable.sc system'}
