### ISSUE TITLE
documentation for field status on scan zone api result

### ISSUE THREAD

**Issue by widnyana** [tenable/pyTenable#93]
Hi Steve,

when I perform an HTTP GET call to [scan_zone endpoint](https://docs.tenable.com/sccv/api/Scan-Zone.html#ScanZoneRESTReference-/zone), the response containing field `status` as a child of `scanners`

```json
{
    "type" : "regular",
    "response" : {
        "id" : "3",
       ...
        "scanners" : [
            {
                "id" : "11",
                "name" : "Cent5x64-NessC1",
                "description" : "",
                "status" : "1025"    <-- this one
            }
        ],
    ...
    },
 ...
}
```

some value that I found on docs was:
- 4
- 1025

since I didnt know what does it mean, where I can find documentation about that value? 

ps: thank you for this library!

**Comment by widnyana** [comment]
adding more info:

I'm using this version
```
Version: 5.8.0
Server Build ID: 201810303290
```

**Comment by widnyana** [comment]
oops, found it: https://community.tenable.com/s/article/SecurityCenter-API-scanner-status-codes

**Comment by SteveMcGrath** [comment]
Awesome, glad you found it.
